### ISSUE TITLE
Wrong/Bad code

### ISSUE THREAD

**Issue by Attackly** [discordjs/guide#1014]
Hey, I read the guide and came across this code 

```
rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands })
	.then(() => console.log('Successfully registered application commands.'))
	.catch(console.error);
```

But in the Client ID you need the Application_id and guildId in order to get it working 

I find that clientId is a bit misleading when the Application_id is meant.

**Comment by imranbarbhuiya** [comment]
dup of #963
