### ISSUE TITLE
Canvas Erorr

### ISSUE THREAD

**Issue by HunterWilson56** [discordjs/guide#102]
(node:681) UnhandledPromiseRejectionWarning: TypeError: Canvas.createCanvas is not a function

at Client.client.on (/app/server.js:48:24)
i keep getting this error and i'm new to canvas so i'm not sure what to do

**Comment by Lewdcario** [comment]
The guide is specifically targeted at a certain version of canvas, please install canvas@next.

**Comment by HunterWilson56** [comment]
i have installed Canvas

**Comment by Lewdcario** [comment]
There are different versions of canvas - like I said, you need canvas@next for this guide to work. You will see the error you are currently getting if you install another version.

**Comment by HunterWilson56** [comment]
ok thank you
