### ISSUE TITLE
Timer countdown in Embed Message

### ISSUE THREAD

**Issue by lsminter** [discordjs/guide#1023]
**Is your feature request related to a problem? Please describe.**
I made a small event bot and one of the fields is `Time till event` then using the UNIX TIMESTAMP `<t:unixtimestamp:R>` to determine how many minutes until the event. When it is in a non-embed message, the timer will count down automatically but when it's in an embed message, it doesn't change from the initial value it was given. If the event is in 2 minutes, it will just stay two minutes forever until the embed message is changed somehow. 

**Describe the solution you'd like**
I'd like for the time to count down automatically as it does in non-embed messages. 

**Describe alternatives you've considered**
Creating an interval to go off every few seconds to `.edit` the embed message. 
I've tried both the `new MessageEmbed()` and as a regular object. 

**Additional notes**
Picture of the embed message: 
![Screen Shot 2022-02-02 at 6 57 29 PM](https://user-images.githubusercontent.com/26470581/152274092-20f9a8c1-a1ba-426b-8a63-cfd7c172b560.png)

**Comment by kyranet** [comment]
That's just a Discord bug, not a Discord.js bug. A workaround you can do for the time being is to also put the timestamp part outside the embed, it'll also make your embed have less empty space.
