### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by Akshit1025** [discordjs/guide#1024]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Make the guide available in multiple languages

**Describe alternatives you've considered**
[React.js](https://reactjs.org) also supports multiple languages

**Additional notes**
Nope

**Comment by BenjammingKirby** [comment]
afaik, this has been discussed in the server multiple times and the answer was always that we can't support multiple languages for the guide
the support server is english only and supporting multiple languages would be tough

**Comment by Akshit1025** [comment]
oh ok, no problem thanks for replying !!
