### ISSUE TITLE
Make An App For Visual Scripting

### ISSUE THREAD

**Issue by HarshuboiPlayz** [discordjs/guide#1033]
**Is your feature request related to a problem? Please describe.**
No, I Just Want Visual Scripting

**Describe the solution you'd like**
No, I Just Want Visual Scripting

**Describe alternatives you've considered**
Idk

**Additional notes**
nope

**Comment by AuroraTook** [comment]
It can't get this much simple also visual scripting is a game development thing and integrating it in discord apps will be a hard job for no reason probably. The functionality might be limited while using visual scripting

**Comment by monbrey** [comment]
This request really bears no relevance to the discord.js guide. You're probably looking for a tool like [Discord Bot Maker](https://store.steampowered.com/app/682130/Discord_Bot_Maker/) though I really can't recommend it.
