### ISSUE TITLE
Discord.js Rate Limit

### ISSUE THREAD

**Issue by suntong** [discordjs/guide#1054]
### Part of the guide or code sample the question is about

Not found. feature request.

### Question

I know that Discord's API has rate limits --
https://discord.com/developers/docs/topics/rate-limits

However, as a bot developer, what we do about it? 

> Because we may change rate limits at any time and rate limits can be different per application, rate limits should not be hard coded into your bot/application. In order to properly support our dynamic rate limits, your bot/application should parse for our rate limits in response headers and locally prevent exceeding the limits as they change

1. This will be such a common task that every single bot developer will be doing, so I'm wondering if there is already ready-build npm modules that is doing that already. 
1. The reason that I'm asking that is, according to [here](https://stackoverflow.com/a/66095270/2125837) --

> ... I had the notion `discord.js` natively handled rate limits by queuing actions accordingly (see [here](https://github.com/discordjs/discord.js/blob/stable/src/rest/RequestHandler.js)), so I'm unsure you have to handle this by yourself.

So, 

1. Do we have to handle this by ourselves? And
2. If "yes", then if there are any existing npm modules that is doing that already, since it is such a common task that every single bot developer will be doing.

thanks

**Comment by megatank58** [comment]
1. No, Ratelimits are handled by the library.
2. No need to

**Comment by suntong** [comment]
Thanks for the confirmation!
