### ISSUE TITLE
Tutorial should refer to "application id" instead of "client id"

### ISSUE THREAD

**Issue by ahSOLO** [discordjs/guide#1057]
### Part of the guide or code sample the question is about

https://github.com/discordjs/guide/blob/main/guide/creating-your-bot/creating-commands.md#registering-commands

### Question

The tutorial is slightly misleading as it talks about copying information from a user's profile. For greater clarify it should refer ID for the bot as "application ID", instead of "client ID".

**Comment by megatank58** [comment]
#1052
