### ISSUE TITLE
have sound under windows, but no sound under linux

### ISSUE THREAD

**Issue by UchihaYuki** [discordjs/guide#1061]
### Describe the bug

The same code, when running under windows 10, there is sound, but no sound when running under Linux. The files I play are mp3.

### To Reproduce

no

### Screenshots

no

### Device (please complete the following information)

My linux version (within docker):
Linux 6dc21aed4031 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 Linux

### Additional notes

Following are debug info by running console.log(generateDependencyReport()) under linux;:
```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.8.0
- prism-media: 1.3.2
Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found
Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5
FFmpeg
- version: 4.3.1-static https://johnvansickle.com/ffmpeg/ 
- libopus: yes
--------------------------------------------------
```
under windows:
```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.8.0
- prism-media: 1.3.2
Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found
Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5
FFmpeg
- version: 4.3
- libopus: yes
--------------------------------------------------
```

**Comment by almostSouji** [comment]
This is not an issue with the guide, if you are trying to report an issue in discord.js, see <https://github.com/discordjs/discord.js>, if this is still reproducible on the latest version (dev or stable).

Please provide a reproducible code sample, if you choose to report it there.
