### ISSUE TITLE
OAuth2 Problem?

### ISSUE THREAD

**Issue by Drelaky** [discordjs/guide#1084]
### Part of the guide or code sample the question is about

HTML: https://pastebin.com/e9gACGvB
BACKEND: https://pastebin.com/Uy1ZTVUA

Dont match the accesToken oauth-state.
![image](https://user-images.githubusercontent.com/53569746/162611645-35ae3e16-07df-4a9f-bb2c-089cb36d8b1f.png)

### Question

Why dont work the index.html? ExpressJS backend work this is very cool but frontend dead? Because i download the code and i use. Pls help me :D

**Comment by almostSouji** [comment]
I cannot reproduce this when using the guide code. This is not the right place for general support.
