### ISSUE TITLE
Weird stuff happening

### ISSUE THREAD

**Issue by Leakoni** [discordjs/guide#1090]
### Part of the guide or code sample the question is about

`const mongoCurrency = require('discord-mongo-currency');
const { MessageEmbed } = require('discord.js');
const { default: mongoose } = require('mongoose');
const mongo = require('mongoose')
const redeemKeySchema = require('../../schemas/redeem-key-schema')
const prefix = require(`discord-prefix`);

const characters ='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

function generateString(length) {
    let result = '';
    const charactersLength = characters.length;
    for ( let i = 0; i < length; i++ ) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}

module.exports = {
    name: "genredeem",
    category: "dev",
    aliases: ["gr"],
    description: "Generate a redeem key",
    usage: "[@user] [1:caps/2:bottles] [amount]",
    permissions: [],
    devOnly: true,
    run: async({client, message, args}) => {
        const member = message.mentions.members.first() || message.member;
        const prefixs = prefix.getPrefix(`${message.guild.id}`) || "!";

        const choice = args[1];
        const ammountToGenerate = args[2] || 0;

        let randomKeyGenerated;

        if(!choice) return message.channel.send(`Please specify a choice. \`1\` for caps, \`2\` for bottles ${prefixs}genredeem @user <1:caps/2:bottles> <ammount>`);
        if(ammountToGenerate.isNaN) return message.channel.send(`Please enter a valid number ${prefixs}genredeem @user <1:caps/2:bottles> <ammount>`)
        if(ammountToGenerate < 1) return message.channel.send(`Please enter a number greater than 0 ${prefixs}genredeem @user <1:caps/2:bottles> <ammount>`)
        if(!ammountToGenerate) return message.channel.send(`Please enter a number ${prefixs}genredeem @user <1:caps/2:bottles> <ammount>`)

        if(choice === "2"){
            randomKeyGenerated = "2la" + generateString(20) + "verne";
        }else{
            randomKeyGenerated = "1la" + generateString(20) + "verne";
        }

        const obj = new redeemKeySchema({
            redeemkey: randomKeyGenerated.toString(),
            ammount: parseInt(ammountToGenerate),
        })

        obj.save(function (err) {
            if (err){
                message.author.send(err.toString());
            } else{
                if(choice === "2"){
                    const generated = new MessageEmbed()
                    .setColor("#4287f5")
                    .setTitle(`Redeem Key`)
                    .addField("Key", `||**${randomKeyGenerated}**||`)
                    .addField("Bottles", `**${ammountToGenerate.toLocaleString('en-US')}** bottles key! \`!redeem {key}\``)

                    member.user.send({ embeds: [generated] })
                    return message.react('✅')
                }else{
                    const generated = new MessageEmbed()
                    .setColor("#4287f5")
                    .setTitle(`Redeem Key`)
                    .addField("Key", `||**${randomKeyGenerated}**||`)
                    .addField("Caps", `**${ammountToGenerate.toLocaleString('en-US')}** caps key! \`!redeem {key}\``)

                    member.user.send({ embeds: [generated] })
                    return message.react('✅')
                }
            }
        })
    }
}`

### Question

So, my old command was !genredeem <type> <amount> and it would send the redeem code to me, aka author. After some time I changed it so could mention the user and send it to them instead, which works with no problem. But once I uploaded new files to the server and started the bot, it somehow uses the old file that does not exist, and the command has to send it to me.

**Comment by almostSouji** [comment]
We do not provide support if your minimal reproducible sample needs to include a third-party library. Feel free to re-open if you can find this issue when using just the code the guide provides. Otherwise, this is not the right place for this issue.

The guide GitHub is not a platform to ask general questions about your bot. Please get in touch with the authors of the respective packages causing you issues instead.
