### ISSUE TITLE
Slash Command and Updating Permissions

### ISSUE THREAD

**Issue by mikecann** [discordjs/guide#1095]
### Describe the bug

Since the 27th of April (2 days ago) Discord have changed the way that permissions are updated for slash commands: https://discord.com/developers/docs/change-log#apr-27-2022

You are no longer able to use the bot to update permissions. This means that this section of the docs is no longer true: https://discordjs.guide/interactions/slash-commands.html#bulk-update-permissions

Im currently trying to work out how to make this work with the REST API.

I think maybe with the addition of `default_member_permissions` we no longer need to do the sepprate step of bulk updating permissions at all:

> Added default_member_permissions field, which is a bitwise OR-ed set of [permissions](https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags), expressed as a string. This replaces the default_permission field, which will soon be deprecated.

And now it can just be included when we [set commands](https://discordjs.guide/interactions/slash-commands.html#guild-commands);

### To Reproduce

1. Go to DiscordJS docs https://discordjs.guide/interactions/slash-commands.html#bulk-update-permissions notice that this is no longer true

### Device (please complete the following information)

All

**Comment by megatank58** [comment]
#1094
