### ISSUE TITLE
Add A Create Channel Section

### ISSUE THREAD

**Issue by GBrayJ** [discordjs/guide#1097]
### Is your feature request related to a problem? Please describe.

It's hard to figure out how to create a channel in Discord.JS and Categorize it, especially as a beginner.

### Describe the solution you'd like

It would show how to create a channel in Discord.JS and how to add it to a category. If you wanted, you could also add to to delete and rename channels.

**Comment by BenjammingKirby** [comment]
I really don't think it's really needed, the [method](https://discord.js.org/#/docs/discord.js/stable/class/GuildChannelManager?scrollTo=create)'s documentation has examples and I think that's sufficient

**Comment by jukkahell** [comment]
GuildChannelManager's create function is marked as deprecated. Is there an alternative way of creating a new channel?

**Comment by BenjammingKirby** [comment]
> GuildChannelManager's create function is marked as deprecated. Is there an alternative way of creating a new channel?

it is not, passing types like `GUILD_STORES` i believe is deprecated
the method isn't deprecated, pass another type and on ts you can pass the type on the generic but that's not needed

i repeat the method is NOT deprecated

**Comment by jukkahell** [comment]
Ah thanks, got it. My bot is a bit old and just needed some type updates.
