### ISSUE TITLE
fs.readdirSync() throwing ENOENT without modifications

### ISSUE THREAD

**Issue by Hades6578** [discordjs/guide#1103]
### Describe the bug

The code provided in "Handling commands" section is currently not working.  When I attempted to use it, was given the error ENOENT: no such file or directory.

### To Reproduce

1. Simply try to run the files provided(The github repo has all of them, be sure you have an actual installation) and it should pop up the error.

### Device (please complete the following information)

Device: Raspberry Pi Zero W
OS: Raspberry Pi OS(Raspbian)
Node.js - V17.0.0

### Additional notes

Modified the tutorial and included the line required to fix, see pull request #1102.

**Comment by megatank58** [comment]
#1069

**Comment by Hades6578** [comment]
Doesn't appear as if the changes were implemented, I did not see such a line in the tutorial.

**Comment by Hades6578** [comment]
Wrote new lines and smoothly integrated the new sections. Please provide feedback if you find something that just doesn't fit. #1102
