### ISSUE TITLE
Slash command permissions [guidance]

### ISSUE THREAD

**Issue by AlexandrosGounis** [discordjs/guide#1131]
### Part of the guide or code sample the question is about

Slash command permissions have been updated as of [April 27](https://discord.com/developers/docs/change-log#updated-command-permissions)

#1094 removed slash command permissions from the guide, without indicating how to handle this part.

For various reasons, I used to have both `global commands` (that do not change, available everywhere) and `guild commands` (available to a whitelisted set of discord servers). 
I also want to hide from the users some admin-only commands. 

I tried the following 
```ts
guildFoo.commands.set([...commands, { name, description, options, default_permission: true }])
// and
client.application.commands.set([...])
```
And I ended up with a bunch of globally cached commands, some work some do not, and I get `application did not respond errors`

### Question

How would someone go about registering slash commands & tweaking permissions using DiscordJs?
Could you please add that part to the guide?

**Comment by megatank58** [comment]
#1116
