### ISSUE TITLE
deploy-commands.js from "Creating commands page" creates error 50035 for me

### ISSUE THREAD

**Issue by TheRealEpic21** [discordjs/guide#1132]
### Describe the bug

```const { SlashCommandBuilder } = require('@discordjs/builders');
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');
const { clientId, guildId, token } = require('./config.json');

const commands = [
	new SlashCommandBuilder().setName('ping').setDescription('Replies with pong!'),
	new SlashCommandBuilder().setName('server').setDescription('Replies with server info!'),
	new SlashCommandBuilder().setName('user').setDescription('Replies with user info!'),
]
	.map(command => command.toJSON());

const rest = new REST({ version: '9' }).setToken(token);

rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands })
	.then(() => console.log('Successfully registered application commands.'))
	.catch(console.error);
```

This is the code from that file; I tried looking for similar problems about this, but it was all about the clientID vs applicationID. I'm using the applicationID, and the error is entirely different. When I try to run it using node deployCommands.js (just the different file name), this error message shows up:

### To Reproduce

Take code: 
```const { SlashCommandBuilder } = require('@discordjs/builders');
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');
const { clientId, guildId, token } = require('./config.json');

const commands = [
	new SlashCommandBuilder().setName('ping').setDescription('Replies with pong!'),
	new SlashCommandBuilder().setName('server').setDescription('Replies with server info!'),
	new SlashCommandBuilder().setName('user').setDescription('Replies with user info!'),
]
	.map(command => command.toJSON());

const rest = new REST({ version: '9' }).setToken(token);

rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands })
	.then(() => console.log('Successfully registered application commands.'))
	.catch(console.error);
```

Put it into a file called deploy-commands.js.

Make sure to have configure.json with this (replace clientID with applicationID): 
`
{
	"clientId": "123456789012345678",
	"guildId": "876543210987654321",
	"token": "your-token-goes-here"
}
`

Use "node deploy-commands.js" in cmd or terminal. (Have this command while in the directory of the project)

### Screenshots

![screenshotBotError1](https://user-images.githubusercontent.com/73008144/170418439-df9acc33-7292-4b2f-b641-869395cd09b3.jpeg)

### Device (please complete the following information)

On Acer ConceptD; using vs code; on ubuntu linux

**Comment by almostSouji** [comment]
![image](https://user-images.githubusercontent.com/26532370/170432482-eab421c0-11c9-4701-8991-610720fc8f04.png)
look at your file and imports again, you are passing undefined as both application as well as guild id
