### ISSUE TITLE
use more straight-forward example for autocomplete page

### ISSUE THREAD

**Issue by almostSouji** [discordjs/guide#1147]
### Is your feature request related to a problem? Please describe.

The current version seems to be using some extended tag command that doesn't really make sense as is. 

### Describe the solution you'd like

A less involved and confusing, more straight-forward example to demonstrate what autocomplete can do (with multiple autocomplete options)

### Describe alternatives you've considered

n/a

### Additional notes

n/a

**Comment by BenjammingKirby** [comment]
i think this is a bigger issue not limited to just this case, i think someone creative needs to go through the examples and make them easier to understand 
most of the examples are well thought out but there are some exceptions that stand out like this one and the current example on [command options](https://discordjs.guide/interactions/slash-commands.html#parsing-options). 
It's a  "ping" command that takes in several options.
The boolean option is named choice, confirmation or something based on the command would be better
there's a random "muted" role option on a ping command

maybe it's a minor thing but again the rest of the guide has good examples

**Comment by megatank58** [comment]
For the autocomplete page, perhaps we could have a tag command there and show options with emojis to the user (somewhat how djs docs does it) or aliases for names and the tag for value, for the options page, it might be good to have an `echo` command and have it practically send what it recieves
