### ISSUE TITLE
Text in voice channels

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/guide#1148]
### Is your feature request related to a problem? Please describe.

v13.8 version

### Describe the solution you'd like

Add page or section to faq about it

**Comment by Jiralite** [comment]
Does there really need to be? It's no different to any other text channel.

**Comment by almostSouji** [comment]
I do not really see a need for it, it's a channel, you send messages to it.
Difference is that it has no pins and threads, that's about it I think
