### ISSUE TITLE
Get MessageSelectMenu values in modalSubmit

### ISSUE THREAD

**Issue by MrEleffant** [discordjs/guide#1156]
### Is your feature request related to a problem? Please describe.

When building  a Modal, it is possible to add Message select menu as same as texts inputComponent
![image](https://user-images.githubusercontent.com/90548369/174491946-b76b7534-dbc2-422c-a273-120c44e69eb7.png)
![image](https://user-images.githubusercontent.com/90548369/174491933-eb32f058-95f0-46f4-8f91-ceffc94a2806.png)
but when trying to get the selections values after ModalSubmit, the value of the component is "undefined".
![image](https://user-images.githubusercontent.com/90548369/174492178-18e027fa-e056-49e4-ad8b-acab2db57fc9.png)

### Describe the solution you'd like

A solution could be to get values as same as select interaction, to get selec values

### Additional notes

Sorry if i'm not explaining this the right way, this is my first "ticket", I try to help the best.
Thank you for your comprehension

**Comment by Mateo-tem** [comment]
There is already a **Draft PR** in discord.js to support select menus in modals, [check it](https://github.com/discordjs/discord.js/pull/7974).

Also select menus in modals are not released yet, you can use it but are in development.

**Comment by Jiralite** [comment]
https://github.com/discordjs/discord.js/issues/8035#issuecomment-1218424881
