### ISSUE TITLE
Context Menu page not updated

### ISSUE THREAD

**Issue by thegrandslam2002** [discordjs/guide#1157]
### Describe the bug

The context menu page claims that the type of a context menu can be set as 'USER' or 'MESSAGE'. This is untrue - the type must be set with a number.

### To Reproduce

Go to "INTERACTIONS"
Click on "Context menus"
Read the section "Registering context menu commands"

### Device (please complete the following information)

Browser: Opera GX
Version: LVL 3 (core: 87.0.4390.58)

**Comment by megatank58** [comment]
This was initially correct in version 0.13.0 of builders but now, v13 uses 0.14.0 of builders, #1151

**Comment by almostSouji** [comment]
pr merged, forgot to link
