### ISSUE TITLE
Add a notice for the atom code editor

### ISSUE THREAD

**Issue by Boxit379** [discordjs/guide#1175]
### Is your feature request related to a problem? Please describe.

The atom code editor is being [sunset](https://github.blog/2022-06-08-sunsetting-atom/) and will be archived this December.

### Describe the solution you'd like

I think a notice should be added on the "Setting up a linter" page beside where it suggests the atom code editor just saying that you may not want to use it since it will be archived

**Comment by megatank58** [comment]
Perhaps it could be removed all together (since not a lot of people actually use atom and later it will also be have to removed when it's archived)
