### ISSUE TITLE
"Initial Files" code doesn't work

### ISSUE THREAD

**Issue by derekslenk** [discordjs/guide#1182]
### Describe the bug

When following the v13 guide, I get a type error when trying to run

### To Reproduce

Follow this guide: https://discordjs.guide/creating-your-bot/

The resulting code doesn't work
```
// Require the necessary discord.js classes
const { Client, Intents } = require('discord.js');
const { token } = require('./config.json');

// Create a new client instance
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });

// When the client is ready, run this code (only once)
client.once('ready', () => {
	console.log('Ready!');
});

// Login to Discord with your client's token
client.login(token);
```

### Screenshots

```
C:\Users\derek\dev\src\discord-bot\index.js:6
const client = new Client({ intents: [Intents.FLAGS.GUILDS] });
                                              ^

TypeError: Cannot read properties of undefined (reading 'FLAGS')
    at Object.<anonymous> (C:\Users\derek\dev\src\discord-bot\index.js:6:47)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.6.0
```

### Device (please complete the following information)

Windows 11, nodejs 18.6.0

### Additional notes

If I try adding the Guilds intents on the app page, it requests a callback url, which the code isn't listening for

**Comment by isaacKenyon** [comment]
What version of Discord.js are you using? Sounds like you're on v14.

**Comment by derekslenk** [comment]
14.0.3. That was the default of the install.

Take it I should manually change that to 13?

**Comment by Jiralite** [comment]
Yes. Although, you should have received an error stating discord.js does not provide an export named `Intents`, so this looks suspicious to me.

A note: https://v13.discordjs.guide/ is for browsing the guide in version 13.

**Comment by derekslenk** [comment]
It doesn't say to tag a version in that documentation - I don't know how I would have assumed I needed a tag tbh

**Comment by derekslenk** [comment]
Either way, pinning to 13.9.0 fixed it for me. Thank you!
