### ISSUE TITLE
[Request] Instructions without usage of @discordjs/builders

### ISSUE THREAD

**Issue by onekiguwolf** [discordjs/guide#1183]
### Is your feature request related to a problem? Please describe.

I have noticed an update from v13 up to v14, and I am eyeing making the switch very soon. One of the changes involves that the package `@discordjs/builders` is now implemented inside djs which that package can now be removed, however, it leaves confusion on the guide that is mostly using the aforementioned package now that it is recommended to remove it.

### Describe the solution you'd like

A solution that I can figure out from my confusion is to add an optional section in the guide in regards to updating the bot to no longer rely on the package, to allow bot developers that are reading the guide on how to make the smooth transition from using the package to the built-in one in djs v14.

### Additional notes

Though the solution is simple, I still welcome the decision made by djs guide developers and anyone willing to suggest other ideas on my concern. Thank you!

**Comment by Jiralite** [comment]
The guide is currently written in version 13. Version 14 comes with #1146.

**Comment by onekiguwolf** [comment]
got it, thanks!

**Comment by almostSouji** [comment]
Should be resolved, if not, feel free to make a follow-up issue or PR with the specific part of the guide that still needs updating.
