### ISSUE TITLE
Slash Command Deferred Example Throws "Invalid Webhook Token"

### ISSUE THREAD

**Issue by JordanSinko** [discordjs/guide#1191]
### Part of the guide or code sample the question is about

https://discordjs.guide/interactions/slash-commands.html#deferred-responses

### Question

I noticed my existing app started throwing recently. It's a pretty simple app, replying to interactions and editing the message with subsequent interactions. It seems that any "edits" to the original message are throwing `Invalid Webhook Token` now.

To make sure it wasn't my code (which hasn't changed in three weeks), I used the example of the deferred response from the guide. I am also getting the same response from Discord.js - Invalid Webhook Token. 

Did something change with the API with the recent Discord.js 14 release that would be breaking this functionality?

**Comment by almostSouji** [comment]
known upstream issue with discord, they are working on a fix

**Comment by JordanSinko** [comment]
Thanks @almostSouji!
