### ISSUE TITLE
Sweepers example

### ISSUE THREAD

**Issue by nyapat** [discordjs/guide#1196]
### Is your feature request related to a problem? Please describe.

No easy example to link when someone asks how to use sweepers, docs are a bit confusing

### Describe the solution you'd like

Example of how to use sweepers to limit cache sizes and reduce memory usage

**Comment by jaw0r3k** [comment]
Like example of it is v13 changes guide
https://discordjs.guide/additional-info/changes-in-v13.html#customizable-manager-caches
