### ISSUE TITLE
please add API version

### ISSUE THREAD

**Issue by dcsan** [discordjs/guide#1201]
### Is your feature request related to a problem? Please describe.

the library has many breaking changes between major versions, and I'm not sure what version these docs are based on. 
https://discordjs.guide/additional-info/changes-in-v14.html#before-you-start

### Describe the solution you'd like

Please add a `v13` or `v14` etc to the footer or somewhere? I couldn't see it anywhere.

### Describe alternatives you've considered

searching thru the repo to see a version somewhere, anywhere.

### Additional notes

not sure how you would track old versions.

**Comment by dcsan** [comment]
yes actually I meant which version of the discordJS package/api is being shown. It's hard to know, esp when there are 14.0 versions out, it's not clear if updated yet.

also this might need to be more granular, eg most of the guide may be unchanged but it's not worth holding back the whole guide until *everything* is updated. So it could be "last updated at..." on a tree/branch/page/feature level of the docs? Hopefully your docbuilder has support for this. eg using docusaurus:

![image](https://user-images.githubusercontent.com/514002/180621654-a0d79d65-d588-4c22-890c-d8b47ff20550.png)

**Comment by lolollllo** [comment]
> yes actually I meant which version of the discordJS package/api is being shown. It's hard to know, esp when there are 14.0 versions out, it's not clear if updated yet.
> 
> also this might need to be more granular, eg most of the guide may be unchanged but it's not worth holding back the whole guide until _everything_ is updated. So it could be "last updated at..." on a tree/branch/page/feature level of the docs? Hopefully your docbuilder has support for this. eg using docusaurus:
> 
> ![image](https://user-images.githubusercontent.com/514002/180621654-a0d79d65-d588-4c22-890c-d8b47ff20550.png)

Don't the guide pages already have last updated timestamps?
![20220724_020216](https://user-images.githubusercontent.com/99907738/180622819-4a1f7217-96fb-4887-a619-017b6914eda2.jpg)

**Comment by almostSouji** [comment]
the main guide on https://discordjs.guide always reflects the latest stable version +- a few days to apply updates and changes
accordingly, right now the docs are v14, if you want older major versions you need a subdomain like https://v13.discordjs.guide

**Comment by dcsan** [comment]
yes there's a date, but that would require cross-referencing with the release dates of versions.
also, there's often a lag. eg july means... which version? I'm not even sure if 14.x is GA currently or if the docs are still on 13.x

it seems like both are being updated as of this date
https://github.com/discordjs/discord.js/tags

**Comment by almostSouji** [comment]
> also this might need to be more granular, eg most of the guide may be unchanged but it's not worth holding back the whole guide until everything is updated

I heavily disagree with this. Introducing changes in some sections but not others (save the vXX-changes section, which we merge prematurely) introduces inconsistency. People do not expect to switch from a page and suddenly see a different version.

The library is on stable v14 now, v13 is still being maintained for a while and accepts backports.
If sections are changed that apply to v13 (on the guide) they are also updated - not doing so at this stage would be a bad decision in our eyes.

**Comment by almostSouji** [comment]
When you visit for the first time after a major update you should be getting a banner at the bottom as well:

![image](https://user-images.githubusercontent.com/26532370/180625906-ce81b463-96c9-400c-bfbf-7102fe79b4b0.png)

**Comment by dcsan** [comment]
ok i probably missed that footer. you could just add it as a permanent footer? just `v14` somewhere would be enough. I've been stumbling through an upgrade from 13->14 today and hitting various issues, esp since the docs are mostly JS and the TS is a bit more prickly.

**Comment by megatank58** [comment]
If you are on v13.discordjs.guide you are using v13, else the latest version,  not sure if im getting what's wrong
