### ISSUE TITLE
TypeError [ColorConvert]: Unable to convert color to a number.

### ISSUE THREAD

**Issue by DragosPV** [discordjs/guide#1213]
### Part of the guide or code sample the question is about

`embed.setColor('GREEN')`

### Question

Why am I getting this error?

![image](https://user-images.githubusercontent.com/98609931/181294047-c5891143-5fde-4487-8717-a994d177ab6a.png)

**Comment by MrCreepyCraft32** [comment]
Either use "Green" or "Colors.Green"
