### ISSUE TITLE
Webhook guide incorrect

### ISSUE THREAD

**Issue by Rogue-Ram** [discordjs/guide#1219]
### Describe the bug

The [guide for webhooks](https://discordjs.guide/popular-topics/webhooks.html#creating-webhooks-with-discord-js) is incorrect, when creating a webhook the guide proposes you do it like this:

`channel.createWebhook({
	name: 'Some-username',
	avatar: 'https://i.imgur.com/AfFp7pu.png',
})`

but when I was attempting to do this I found out that you actually need to do it like this:

`channel.createWebhook(
interaction.user.username,
{
 avatar: interaction.user.displayAvatarURL,
})`

otherwise it will result in a error since its not expecting the name and the avatar in the same object as mentioned in the guide

### To Reproduce

Go to https://discordjs.guide/popular-topics/webhooks.html#creating-webhooks-with-discord-js and scroll down to "Creating webhooks with discord.js" and look at the example.

### Screenshots

![image](https://user-images.githubusercontent.com/82464257/181996734-05c61318-9cf2-4e4d-b533-f17f3c41ebd2.png)
![image](https://user-images.githubusercontent.com/82464257/181996746-4465339c-c8c7-47c4-8bef-b6abde101263.png)
![image](https://user-images.githubusercontent.com/82464257/181996751-13a4009b-3093-4efd-81ce-6b37833d539a.png)

### Device (please complete the following information)

Device: Macbook Air
OS: MacOS
Browser: Brave

### Additional notes

I apologize if this is not the correct way to report this.

**Comment by Jiralite** [comment]
> but when I was attempting to do this I found out that you actually need to do it like this:
> 
> `channel.createWebhook( interaction.user.username, { avatar: interaction.user.displayAvatarURL, })`

This would indicate you are not on the version the guide is using. It seems you are using version 13 so please use https://v13.discordjs.guide/ to browse through the guide in version 13. Version 14, the latest stable, is what the guide defaults to.

**Comment by almostSouji** [comment]
it looks to me like you are using the v14 guide with v13 installed

**Comment by Rogue-Ram** [comment]
Ops, I thought i was running the latest version since I had just updated all my dependencies around a hour ago sorry.
