### ISSUE TITLE
How can someone access my server with a bot token?

### ISSUE THREAD

**Issue by Anime-Master** [discordjs/guide#1244]
### Part of the guide or code sample the question is about

https://discordjs.guide/preparations/setting-up-a-bot-application.html#token-leak-scenario

### Question

Hi I am looking at the list of possibilities in the Token leak scenario.
Spam every server your bot is on;
DM spam as many users as possible;
Delete as many channels as possible;
Kick or ban as many server members as possible;
Make your bot leave all of the servers it has joined;
**Access and damage the underlying infrastructure (your server).**
I understand why the first 5 things in the list are possible. However, I fail to see how it is possible to access my server with a bot token.

I could be wrong so feel free to correct me here, but my understanding is that a bot token simply represents an account on Discord's server. It is not connected to any third party instrastructure or my server. Since Discord does not have access my server, a person who has access to my bot token would not have access to my server either.

**Comment by jaw0r3k** [comment]
In some cases it can
but it's not really easy

**Comment by Anime-Master** [comment]
> In some cases it can but it's not really easy

Is it possible to be a bit more specific? What cases would they be?
I am asking not because I doubt what you say is true, but because I am genuinely curious about the technical details.

The only possible case I can imagine this being possible is, if someone set their server SSH password to be their discord bot token. In this case, the user chose to give meaning to their discord bot token which would not exist normally, so I don't think it's fair to make broad claims based on this case alone. Is there any other possibility I am overlooking?
