### ISSUE TITLE
Parsing mentions page is outdated

### ISSUE THREAD

**Issue by Jiralite** [discordjs/guide#1262]
### Describe the bug

The https://discordjs.guide/miscellaneous/parsing-mention-arguments.html page is outdated. It is using version 13 code. It should be using version 14 code.

### To Reproduce

1. Go to https://discordjs.guide/miscellaneous/parsing-mention-arguments.html#implementation

### Device (please complete the following information)

N/A

**Comment by Vinitvh** [comment]
Hi, I would like to work on this. Can anyone guide me how to go about it. Thank you.

**Comment by jaw0r3k** [comment]
Whole page just should be deleted 
1. MessageContent intent 🙄
2. Message#mentions exists *( which doent work in some cases like guide says )*
3. I dont think somebody even once will use it

**Comment by jaw0r3k** [comment]
So?

**Comment by Jiralite** [comment]
In the long run, removing the page may be a viable solution (slash commands > message commands) so yeah, remove it.
