### ISSUE TITLE
Uncompleted sentence.

### ISSUE THREAD

**Issue by Neodevils** [discordjs/guide#1267]
### Is your feature request related to a problem? Please describe.

Yes, it is related to a problem on Discord.js Guide.

### Describe the solution you'd like

![IMG_20220915_134956](https://user-images.githubusercontent.com/71941576/190644942-a304ff41-44fa-490c-9eca-70f2a8155347.jpg)

It's missing rest of the sentence.

**Comment by Jiralite** [comment]
Resolved with e6d1580b05ce34e7544fef43d33800b92ef490aa.
