### ISSUE TITLE
broken link on buttons page

### ISSUE THREAD

**Issue by mrhappyma** [discordjs/guide#1278]
### Describe the bug

> If you're using TypeScript you'll need to specify the type of components your action row holds. This can be done by specifying the component builder you will add to it using a generic parameter in [ActionRowBuilder](https://discord.js.org/#/docs/main/stable/class/ActionRowBuilder).

link doesn't show anything (404?)

### To Reproduce

- go to that page
- scroll down
- click

### Screenshots

![image](https://user-images.githubusercontent.com/55963440/192068828-fd8c7b84-8eee-4337-96fd-97c47468d499.png)

### Device (please complete the following information)

OS: Ubuntu 22.04.1
Browser: Firefox 105.0.1

**Comment by mrhappyma** [comment]
To clarify the page with said broken link is https://discordjs.guide/interactions/buttons.html#building-and-sending-buttons

**Comment by jaw0r3k** [comment]
um yeah ActionRowBuilder is in main docs
