### ISSUE TITLE
A lot of the typing is wrong following the guide

### ISSUE THREAD

**Issue by GabrielCartier** [discordjs/guide#1317]
### Describe the bug

I've been trying to follow the guide to build a bot with `commands` and `subcommands` and the typing returned will lead to errors.

It seems to me that the guide is built with JS which is fine, but clearly the current typing in the library is wrong. I'm also thinking there are better ways to do some of the various operations.

I'm only starting with `discord.js`, but typing has been a very big headache already. 

### To Reproduce

To give examples, from https://discordjs.guide/creating-your-bot/command-handling.html#executing-commands
In the second code block, it says to retrieve the command you should do the following:
`const command = interaction.client.commands.get(interaction.commandName);`

If you look at the `BaseInteraction` class (which is the type returned from the event `Events.InteractionCreate`, or at least that's what I understood), it has a `client` from `Base` class which is a `Client`. That class does not have a `commands`  variable. It seems to be from `ClientApplication` class, but it's not returned as per the guide. The guide seems to be taking a very odd approach to extract the `command` for an `interaction` anyway as a `BaseInteraction` can be typed to `CommandInteraction` via the `isCommand()` method which itself has the command. That's how I fixed this issue, but the guide is definitely not working as is with Typescript.

The other issue I'm running into is with `subcommands`. The guide for parsing subcommands (https://discordjs.guide/slash-commands/parsing-options.html#subcommands) says to use:
`interaction.options.getSubcommand()`
Although that seems to be the correct method, this does not work in Typescript because the `options` parameter is defined as:
```
public options: Omit<
    CommandInteractionOptionResolver<Cached>,
    | 'getMessage'
    | 'getFocused'
    | 'getMentionable'
    | 'getRole'
    | 'getAttachment'
    | 'getNumber'
    | 'getInteger'
    | 'getString'
    | 'getChannel'
    | 'getBoolean'
    | 'getSubcommandGroup'
    | 'getSubcommand'
  >;
```
Which essentially means the `options` of a `CommandInteraction` will **not** has a `getSubcommand` method. Of course, that's wrong because I use it, but the only way to do so with Typescript is to use a `ts-ignore` rule because the transpiler complains about it.

### Screenshots

Screenshots for errors and how I get around them:
Commands:
<img width="1174" alt="Screen Shot 2022-10-21 at 3 57 12 PM" src="https://user-images.githubusercontent.com/4060669/197280580-71ea0fcf-80b4-4378-9c96-9ba2ff2ef955.png">
<img width="951" alt="Screen Shot 2022-10-21 at 3 57 21 PM" src="https://user-images.githubusercontent.com/4060669/197280582-dad32e1e-04d7-46b4-b925-bfd37fcb94ad.png">

Subcommands:
<img width="1325" alt="Screen Shot 2022-10-21 at 4 08 53 PM" src="https://user-images.githubusercontent.com/4060669/197280669-53c9835f-473c-4337-ad39-392104d05eb6.png">
<img width="1282" alt="Screen Shot 2022-10-21 at 4 09 07 PM" src="https://user-images.githubusercontent.com/4060669/197280672-1edefb43-fbe6-4ace-a9c4-7ee256379b10.png">

### Device (please complete the following information)

`discord.js` ^14.6.0
`typescript` ^4.8.4

**Comment by monbrey** [comment]
Thanks for the issue. There used to be a tip on the page regarding `client.commands` that covered module augmentation in TypeScript - how you can add custom properties to existing types. It seems I've accidentally removed this so I'll make sure to add it back.

Regarding the second issue though, that's an error with your typeguarding. Please ensure you correctly typeguard using `interaction.isChatInputCommand()` and it should correctly resolve all options methods.

**Comment by GabrielCartier** [comment]
> Thanks for the issue. There used to be a tip on the page regarding `client.commands` that covered module augmentation in TypeScript - how you can add custom properties to existing types. It seems I've accidentally removed this so I'll make sure to add it back.
> 
> Regarding the second issue though, that's an error with your typeguarding. Please ensure you correctly typeguard using `interaction.isChatInputCommand()` and it should correctly resolve all options methods.

Thanks for the reply.

For the first part, ill check the PR, thx. 
As for the second part, yup, just double checked, works, thanks!
