### ISSUE TITLE
A very basic example on making a music system.

### ISSUE THREAD

**Issue by ThatTonybo** [discordjs/guide#133]
I'm not too sure if it'd even be worth the effort, if not, even I would be happy to PR a guide page, but a basic music guide would be cool (that contains queues, skipping, all that).

It is a bit of a big topic I guess, but it'd be useful for beginners.

**Comment by KingDGrizzle** [comment]
I'm willing to contribute to this guide as well, as I use ~~and break~~ broadcasts  a lot.

**Comment by Danktuary** [comment]
@ThatTonybo @KingDGrizzle You guys (and anybody else who wants to) are more than welcome to contribute to this! I think it's a topic that'd be nice to have on the guide. I personally don't use anything voice-related so I wouldn't be able to make the page myself, so contributions from others would be appreciated. 😄

**Comment by PLASMAchicken** [comment]
https://github.com/discordjs/guide/blob/master/CONTRIBUTING.md

**Comment by sasial-roblox** [comment]
I'm happy to help.
I also have an NPM package for lazy people. 😆 
[https://www.npmjs.com/package/easy-discord-music](https://www.npmjs.com/package/easy-discord-music)

**Comment by ThatTonybo** [comment]
> 
> 
> I'm happy to help.
> I also have an NPM package for lazy people. 😆
> https://www.npmjs.com/package/easy-discord-music

That just makes people not bother to learn it the right way and actually make it themselves.

I'm going to look into doing some work on this during my upcoming school break as well, I'd suspect if published it'd be a well used guide page.

**Comment by bdistin** [comment]
> I'm happy to help.
> I also have an NPM package for lazy people. 😆
> https://www.npmjs.com/package/easy-discord-music

This is really not a good idea since this is a shitty fork (not even a proper fork, just a re-upload) of my OhGodMusicBot where you have violated the OpenSource license by removing my copyright.

**Comment by almostSouji** [comment]
As this has been stale for quite some while:
With v12 becoming stable <https://discordjs.guide/voice/> (written by hydrabolt) is a good foundation for this! If you want to add a music system around the new voice lib guide feel free to do so.

**Comment by ThatTonybo** [comment]
Doesn't seem to be anything in the page you linked other than duplicated content.

**Comment by almostSouji** [comment]
I'm not too sure what you mean by "duplicated content"?
Version 12 has undergone a major rewrite of the voice library and as such the public facing API has changed in places, hydrabolt contributed a guide on the new system, which i wanted to bring to attention above, so people that might be interested in resolving this by contributing a music system section are aware of the changes.

**Comment by sasial-dev** [comment]
> > I'm happy to help.
> > I also have an NPM package for lazy people. 😆
> > https://www.npmjs.com/package/easy-discord-music
> 
> That just makes people not bother to learn it the right way and actually make it themselves.
> 
> I'm going to look into doing some work on this during my upcoming school break as well, I'd suspect if published it'd be a well used guide page.

Yeah, apologies about that. I wrote it before I understood copyright while first joining github. :/
I plan to re-do it with credit to your fork.

**Comment by conqr2** [comment]
The problem with adding music is you must have ffmpeg installed, and your host must have a large amount of standby cpu / memory available for use.
