### ISSUE TITLE
indenting in the menu is a little unclear

### ISSUE THREAD

**Issue by gloss-water** [discordjs/guide#134]
![image](https://user-images.githubusercontent.com/17156890/45564218-030bf100-b80d-11e8-91eb-99b204319d71.png)

I don't know if it's just me, but it's hard to see where one section ends and the next begins when we get to the sub-sub-topic level, since we're mixing whether the sub-articles get indented or not. It's more clear in the light mode version since bold stands out a bit more.

**Comment by Danktuary** [comment]
Yeah, the way it currently is isn't very ideal. But once I get through the last few current issues/PR(s), I'll be moving everything over to VuePress, which gives off a much better sidebar experience, making it [more obvious to tell the difference](https://i.imgur.com/OqPUfgW.png) ([live sample site](https://vuepress-theme-yuu.netlify.com)).

It's mostly just a matter of finding the time to get through these things... 😅 But it'll happen eventually.
