### ISSUE TITLE
Incorrect information in Slash command permissions regarding permission requirements

### ISSUE THREAD

**Issue by Sheepolution** [discordjs/guide#1340]
### Describe the bug

In [this article](https://discordjs.guide/slash-commands/permissions.html#member-permissions) the following is stated:

> For a kick command however, we can allow members with either BanMembers or KickMembers to execute the command, so we'll list both flags here joined by the bitwise OR operator.

This is incorrect, as Discord does not support one-of permission requirements for Slash commands. The example `.setDefaultMemberPermissions(PermissionFlagsBits.BanMembers | PermissionFlagsBits.KickMembers);` will require the member to have both the ban BanMembers and KickMembers permission.

### To Reproduce

1. Create a slash command with `.setDefaultMemberPermissions(PermissionFlagsBits.BanMembers | PermissionFlagsBits.KickMembers);`
2. Give a member only the KickMembers permission.
3. They are not allowed to use the command, as they miss the BanMembers permission.

### Device (please complete the following information)

N.A.

**Comment by monbrey** [comment]
Thanks, this makes sense, not sure what example I was going for when I wrote this. I'll review and make changes.
