### ISSUE TITLE
Wrong anchor on Thread guide

### ISSUE THREAD

**Issue by DylanDelobel** [discordjs/guide#1367]
### Describe the bug

From this page:
https://discordjs.guide/popular-topics/threads.html#creating-and-deleting-threads

Link with Anchor goes no-where
ThreadManager doesn't have these methods

[ThreadManager#create()](https://discord.js.org/#/docs/main/main/class/ThreadManager?scrollTo=create)
[ThreadChannel#delete()](https://discord.js.org/#/docs/main/main/class/ThreadChannel?scrollTo=delete)

I'm pretty sure this would have to link to `GuildTextThreadManager`
I'm here to double-check, otherwise, I'm happy to make the PR to fix this :)

### To Reproduce

1. Open [thread guide](https://discordjs.guide/popular-topics/threads.html#creating-and-deleting-threads)
2. Click `ThreadManager#create()`

### Screenshots

![image](https://user-images.githubusercontent.com/5182186/205897980-d54a33f3-259b-4e0f-ad7f-3a3a4f0b25a5.png)

### Device (please complete the following information)

Chrome 107
W10

**Comment by Jiralite** [comment]
> I'm pretty sure this would have to link to `GuildTextThreadManager`
> I'm here to double-check, otherwise, I'm happy to make the PR to fix this :)

Yep, that would seem to be the case. `ThreadManager` is now an abstract class - `GuildTextThreadManager` and `GuildForumThreadManager` are what should be used (as appropriate).

**Comment by DylanDelobel** [comment]
@Jiralite Thanks for the double-check! PR is on the way!
