### ISSUE TITLE
StringSelectMenuBuilder is not a constructor

### ISSUE THREAD

**Issue by Banaanae** [discordjs/guide#1371]
### Describe the bug

On the [Select menu page](https://discordjs.guide/interactions/select-menus.html#building-and-sending-select-menus) the first code box says to use the `StringSelectMenuBuilder` builder. Running a command with this gives the following error: `TypeError: StringSelectMenuBuilder is not a constructor`

This also continues to [handling interactions](https://discordjs.guide/interactions/select-menus.html#receiving-select-menu-interactions) as  `isStringSelectMenu()` isn't a method.

### To Reproduce

1. Create a command using `StringSelectMenuBuilder`
2. Run the command on Discord
3. Receive error `TypeError: StringSelectMenuBuilder is not a constructor`

### Device (please complete the following information)

- Node.js v19.1.0
- Npm v9.1.2
- discord.js v14.6.0
- @discordjs/builders v1.3.0

### Additional notes

Seems to be fixed by replacing "StringSelectMenuBuilder" with "SelectMenuBuilder" and "isStringSelectMenu()" with "isSelectMenu()"

**Comment by Idris1401** [comment]
you need to update discord.js to the latest version (14.7.1)

**Comment by Banaanae** [comment]
Probably should've checked that before creating this, thank you!
