### ISSUE TITLE
Links on README.md not correct

### ISSUE THREAD

**Issue by stephen-silveira** [discordjs/guide#1380]
### Describe the bug

![image](https://user-images.githubusercontent.com/16563148/208322664-ac2e824d-dcce-4b9b-ad06-0fe99208ff62.png)
 those links in blue are not correct, not pointing to where should be.

### To Reproduce

go to https://github.com/discordjs/guide/tree/main/guide scroll down and click the first link `up and running` for example.

### Device (please complete the following information)

Chrome.

**Comment by Jiralite** [comment]
The links are intended to be used on the [website](https://discordjs.guide/). This is not a bug.

**Comment by stephen-silveira** [comment]
sorry for the misunderstanding.
