### ISSUE TITLE
MongoDB Section

### ISSUE THREAD

**Issue by VexFortnite** [discordjs/guide#1381]
### Is your feature request related to a problem? Please describe.

I believe there should be a section on MongoDB, even though there are many other tutorials on youtube, it would be nice to connect it in the same project file, not having to create a second project file just for that, and it can get very confusing, having no idea how to connect MongoDB.

### Describe the solution you'd like

There should be a strong section on the code required, and which files to put the MongoDB code in, whether you should create 
a new file for it, or put it in the `.env` file, meaning someone can have a clear understanding on how to use MongoDB

### Describe alternatives you've considered

I could use Youtube, but again, it can be confusing, considering we're using different files.

**Comment by jaw0r3k** [comment]
its **DJS** guide

**Comment by almostSouji** [comment]
We do not plan to cover more flavors of databases in the guide at this time.
