### ISSUE TITLE
Broken Link to interactions for ContextMenu Commands

### ISSUE THREAD

**Issue by Moros0741** [discordjs/guide#1389]
### Describe the bug

In the Guilde, The link to Both `UserContextMenuInteraction` and `MessageContextMenuInteraction`  under the Interactions > ContextMenu take you to a non-existent page on the Documentation. 

**The Current Links are:**
UserContextMenuInteraction: `https://discord.js.org/#/docs/main/main/class/UserContextMenuInteraction`
MessageContextMenuInteraction: `https://discord.js.org/#/docs/main/main/class/MessageContextMenuInteraction`

### To Reproduce

Visit: https://discordjs.guide/interactions/context-menus.html#extracting-data-from-context-menus
Choose one of the above mentioned redirects 

### Device (please complete the following information)

Windows 11 x64
Chrome

### Additional notes

**What I expected:**
To be brought to the proper pages: 
UserContextMenuInteraction: https://discord.js.org/#/docs/discord.js/main/class/UserContextMenuCommandInteraction
MessageContextMenuInteraction: https://discord.js.org/#/docs/discord.js/main/class/MessageContextMenuCommandInteraction

**What Actually Happens:**
I am redirected to a blank page.

**Comment by jaw0r3k** [comment]
actually the issue there is that the name is 
MessageContextMenu**Command**Interaction

**Comment by Jiralite** [comment]
Resolved with #1408.
