### ISSUE TITLE
Text select highlight colour

### ISSUE THREAD

**Issue by GreySkySpin** [discordjs/guide#1393]
### Is your feature request related to a problem? Please describe.

In dark mode, the highlight colour is almost the same as the text in the Brave browser.

### Describe the solution you'd like

Could the colour been changed so there is a greater difference between text font colour and the highlight colour when selecting the text.

### Describe alternatives you've considered

It could be a browser issue, but different browsers seem to have different text highlighter colours.

**Comment by Jiralite** [comment]
Can you show what you're seeing?

**Comment by almostSouji** [comment]
Feel free to respond to re-open, I cannot reproduce an issue with highlight colors on my end.
