### ISSUE TITLE
difference between site and repository

### ISSUE THREAD

**Issue by katiebuilder** [discordjs/guide#1394]
### Part of the guide or code sample the question is about

[Event handling](https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files)

### Question

The "Event Handling" page has a difference when compared to the repository
Repository:
https://github.com/discordjs/guide/blob/6bea5078bc76911f9600d0ef80448610a73b8f61/code-samples/creating-your-bot/event-handling/events/interactionCreate.js#L2
Guide:
```js
	name: Events.InteractionCreate,
```

I'm not really sure if this matters or not but it's kind of confusing.

**Comment by Jiralite** [comment]
It should reflect it. I'd say this is a bug.

**Comment by keatonbuilder** [comment]
> It should reflect it. I'd say this is a bug.

ok, just didnt know what to put it under
