### ISSUE TITLE
Event handler error

### ISSUE THREAD

**Issue by Fulwing** [discordjs/guide#1409]
### Part of the guide or code sample the question is about

I follow the code till [here](https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files)

### Question

`TypeError: Cannot read properties of undefined (reading 'get')
    at Object.execute (D:\Discord-Bot\discord-bottest\events\interactionCreate.js:6:47)
    at Client.<anonymous> (D:\Discord-Bot\discord-bottest\index.js:18:44)
    at Client.emit (node:events:512:28)
    at InteractionCreateAction.handle (D:\Discord-Bot\discord-bottest\node_modules\discord.js\src\client\actions\InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (D:\Discord-Bot\discord-bottest\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (D:\Discord-Bot\discord-bottest\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (D:\Discord-Bot\discord-bottest\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)    at WebSocketShard.onMessage (D:\Discord-Bot\discord-bottest\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (D:\Discord-Bot\discord-bottest\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (D:\Discord-Bot\discord-bottest\node_modules\ws\lib\event-target.js:209:9)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:393:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)`

and I got this error, I am sure I got every code correct, I don't know why do I have this error

**Comment by Fulwing** [comment]
`client.commands = new Collection();
const commandsPath = path.join(__dirname, 'commands');
const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
	const filePath = path.join(commandsPath, file);
	const command = require(filePath);
	client.commands.set(command.data.name, command);
}`

I added this to the index that solves the problem, but I don't know do I suppose to do that

**Comment by Fulwing** [comment]
`client.commands = new Collection();
const commandsPath = path.join(__dirname, 'commands');
const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
	const filePath = path.join(commandsPath, file);
	const command = require(filePath);
	client.commands.set(command.data.name, command);
}`

**Comment by almostSouji** [comment]
looks like - in doing up to here - you skipped half of the command guide, for example, this section: https://discordjs.guide/creating-your-bot/command-handling.html#loading-command-files

**Comment by Fulwing** [comment]
this is the [source code](https://github.com/discordjs/guide/tree/main/code-samples/creating-your-bot/event-handlingl)

I copy and paste them into my work(everything is the same as the guide), and by that error appears. If I add the code I comment on the top in `index.js` that will work.

**Comment by Fulwing** [comment]
> 

Ok, so this will be included in the `index.js`? When I got to [Event handler](https://discordjs.guide/creating-your-bot/event-handling.html#resulting-code) the `index.js` in the resulting code don't have that, so I deleted it.

**Comment by almostSouji** [comment]
i see, looks like this scrapped most of the command loader without mentioning it at all
we generally recommend following the guide, not just hoping the resulting code samples work
in any case, even after a potential fix, the event handler will not have as in-depth code (perhaps even an empty command list).

it should however not throw an error - or at the very least have a comment referencing to the other section

tracking in https://github.com/discordjs/guide/issues/1411 with a clear description of the error

**Comment by Fulwing** [comment]
Yeah, I understand we need 

```js
client.commands = new Collection();
const commandsPath = path.join(__dirname, 'commands');
const commandFiles = fs.readdirSync(commandsPath).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
	const filePath = path.join(commandsPath, file);
	const command = require(filePath);
	client.commands.set(command.data.name, command);
}
```
It is just a bit confusing if the resulting code is not the same, because I would think that should be the code I am having right now if I follow the guide. The guide teaches really well, I think it is better to add this part of the code to the `index.js` of the Event Handler resulting code. Easier to understand. I deleted that part because when I check the resulting code, that part is gone so I think it should be deleted from my `index.js`. Just advise on the reader's side. That will give a better understanding, but you could decide. Thank you so much for solving my problem! Have a nice day!
