### ISSUE TITLE
Updating to v14: Missing changes

### ISSUE THREAD

**Issue by githubUser982** [discordjs/guide#1414]
### Describe the bug

here are the inconstancies between "changes-in-v14" and the real things that have been broken:

- String intents no longer work, such as 'GUILD_MESSAGES', => GatewayIntentBits.GuildMessages,

 - Same for partials: 'CHANNEL' => Partials.Channel
 
 - no replacement for 'DIRECT_MESSAGES' is shown in the GatewayIntents section. Would be helpful.
nothing =>  GatewayIntentBits.DirectMessages

"Common Button Data changes" looks like it applies to button objects only when it applies to builders too.
 
- guild.me is removed. guild.me => guild.members.me

- Checking permissions with .has("perm") now also needs the enums: guild.members.me.permissions.has("SEND_MESSAGES") => guild.members.me.permissions.has(PermissionsBitField.SEND_MESSAGES)

-addFields example does not do the same thing. inline: true has been removed. .addField('Inline field title', 'Some value here', true); => .addFields([ { name: 'one', value: 'one', inline: true },]);

- setFooter now only accepts objects: setFooter("string") => setFooter({text: "string"}) 

### To Reproduce

1. Go to https://discordjs.guide/additional-info/changes-in-v14.html
2. Try to port v13 code to v14

### Device (please complete the following information)

OS: Microsoft Windows Server 2019 Standard
Node: v16.13.1
Browser: Any

**Comment by Jiralite** [comment]
> * String intents no longer work, such as 'GUILD_MESSAGES', => GatewayIntentBits.GuildMessages,
> * Same for partials: 'CHANNEL' => Partials.Channel

> * Checking permissions with .has("perm") now also needs the enums: guild.members.me.permissions.has("SEND_MESSAGES") => guild.members.me.permissions.has(PermissionsBitField.SEND_MESSAGES)

These are already listed (as well as examples given) here:

- https://discordjs.guide/additional-info/changes-in-v14.html#new-enum-differences
- https://discordjs.guide/additional-info/changes-in-v14.html#common-client-initialization-changes

> * no replacement for 'DIRECT_MESSAGES' is shown in the GatewayIntents section. Would be helpful.
>   nothing =>  GatewayIntentBits.DirectMessages

I'm not sure what you're referencing here, but this seems really obvious—especially from reading the above example.

> "Common Button Data changes" looks like it applies to button objects only when it applies to builders too.

Each old builder has its own section detailing it is now a builder.

> * guild.me is removed. guild.me => guild.members.me

https://discordjs.guide/additional-info/changes-in-v14.html#guild

> -addFields example does not do the same thing. inline: true has been removed. .addField('Inline field title', 'Some value here', true); => .addFields([ { name: 'one', value: 'one', inline: true },]);

That is one thing to add. To be clear to others reading, the example under [`MessageEmbed`](https://discordjs.guide/additional-info/changes-in-v14.html#messageembed) does not have the correct difference for `inline`.

> * setFooter now only accepts objects: setFooter("string") => setFooter({text: "string"})

https://discordjs.guide/additional-info/changes-in-v14.html#messageembed

<hr>

Overall, it looks like there is only one missing change in your provided list. If you think I have been unclear about anything, feel free to comment.

**Comment by githubUser982** [comment]
I suppose 

> Any areas that used to accept a string or number type for an enum parameter

  Could be taken to mean that these things are broken but previously they were not enums they were "just strings".
With retrospect I can see how it is implied that the inputs have changed, now that you point it out, but before it I could not determine that this was something that was going to break. Examples would have helped a lot not only in solving the breakage but primarily in determining that it would happen at all. In my brain: "something something Enums" - not relevant, I used strings.


> I'm not sure what you're referencing here, but this seems really obvious—especially from reading the above example.
Hmm I think my bad.

> Each old builder has its own section detailing it is now a builder.
Yes, the MessageButton => ButtonBuilder was very understandable, the problem as I see it is that the "Common Button Data changes" which details button.style changing implied that it only affect button objects, since the guide otherwise uses builder functions and not button objects. When the guide then shows button objects as the example it implies only those are affected.

> https://discordjs.guide/additional-info/changes-in-v14.html#guild
Hmm good point. I didn't find it because I searched for guild.me (and not guild#me)... Which makes me wonder why it's written as guild#me... 

For footers yes again it was not clear to me that it meant that. Examples are good. Actually I think it would be best if the document was almost only examples. Yes it might be a bit long, but then it is clear what you need to do. And the length will make the required effort to port the code clear.

**Comment by githubUser982** [comment]
Anyway thanks for the swift reply c:

**Comment by almostSouji** [comment]
> Which makes me wonder why it's written as guild#me...

In this form of notation (https://discordjs.guide/additional-info/notation.html#classes) `#` refers to instance methods while `.` refers to static methods.

**Comment by almostSouji** [comment]
If you find any other missing changes, please open a new issue, so we can consistently track this internally.
