### ISSUE TITLE
Limits Section

### ISSUE THREAD

**Issue by kankurodev** [discordjs/guide#1417]
### Is your feature request related to a problem? Please describe.

While I'm aware that you can find the limits for things under their relevant sections on either the DJS Guide, DJS Docs, or Discord's Dev site, but having to search up specific things to view the limits you have to maintain can get very tedious.

### Describe the solution you'd like

It would be extremely helpful if there was a section within the DJS Guide site that simply lists all of the limits users/bots have to abide by such as nickname character limit, embed fields limit, presence character limit, etc.

I think a good spot for this would either be in "Popular Topics" or "Miscellaneous Topics".

**Comment by megatank58** [comment]
all of these limits (and more) are already listed on [discord developer docs](https://discord.dev). it would be a hassle to maintain all of these limits changing.

**Comment by almostSouji** [comment]
We decided to not document upstream (read: discord API) limits within our guide or docs, as they can and historically have changed. Discord can (and evidently does) change these without prior warning or notice.
