### ISSUE TITLE
Scrollbar color does not change upon changing theme settings

### ISSUE THREAD

**Issue by TetieWasTaken** [discordjs/guide#1430]
### Describe the bug

When switching to either the blue or green theme on the guide the scrollbar does not change colors until the page is reloaded. See video for more context

https://user-images.githubusercontent.com/74485845/224560236-a428602d-16de-4606-a17d-95b269ab231d.mov

### To Reproduce

1. Go to any page of the [guide](https://discordjs.guide/)
2. Click the "settings" dropdown on the left
3. Select the theme that you're not currently on
4. See scrollbar on the right (incorrect color)
5. Refresh page
6. See scrollbar again (correct color)

### Screenshots

<img width="281" alt="Schermafbeelding 2023-03-12 om 17 56 14" src="https://user-images.githubusercontent.com/74485845/224559932-03dc99b8-1c2c-4384-a5c7-300ba2184da2.png">
<img width="228" alt="Schermafbeelding 2023-03-12 om 17 59 20" src="https://user-images.githubusercontent.com/74485845/224560079-4362cf9d-8836-4e09-a420-2430b4c2cc32.png">

### Device (please complete the following information)

MacOS Big Sur 11.5.2
Chrome v110.0.5481.177

**Comment by Jiralite** [comment]
Well, that's interesting. For what it's worth, I'm unable to reproduce this on Safari 16.3 and Firefox 111.0. I'm able to reproduce this issue on Google Chrome 110.0.5481.177, though. Possibly a Chromium issue?

**Comment by TetieWasTaken** [comment]
After posting that, I tried it on Opera. Which has the same issue and also runs on Chromium. So this is very likely to be a Chromium issue.
