### ISSUE TITLE
Something to add to the discord.js Guide 'Running your application' Constituent

### ISSUE THREAD

**Issue by HuguesKalin** [discordjs/guide#1450]
### Is your feature request related to a problem? Please describe.

I spent a good 10 minutes trying to figure out why my node index.js prompt keeps returning an error
Until I thought it was something to do with not being logged onto discord and having no server connection. And now it works.

### Describe the solution you'd like

Can you just add a little line that says: "Make sure you are logged on to discord, otherwise it will not function."
This is just something to help other newbies. 

### Describe alternatives you've considered

The most it says is: "This is how you create a client instance for your Discord bot and log in to Discord." But these are not instructions for you to log on to discord.

**Comment by Idris1401** [comment]
the application owner doesn't need to be online to put his bot online

**Comment by HuguesKalin** [comment]
Hm, that is true I have just tested it, but why did it not work before?

**Comment by Idris1401** [comment]
actually you didn't even send the error you've got before
