### ISSUE TITLE
When I say "npm run dev" and enter, the server does not open.

### ISSUE THREAD

**Issue by koderbilal** [discordjs/guide#1464]
### Describe the bug

in Contributing
The local development part does not work, the files are downloaded to your computer, but lastly, it does not work when I say npm run dev

### To Reproduce

1.) git clone https://github.com/discordjs/guide.git
2.) cd guide
3.) npm install
4.) npm run dev
See error
and 
When I say "http://localhost:8080/" and open it, I get the error in the picture below

### Screenshots

![image](https://github.com/discordjs/guide/assets/69713944/a201ae25-4beb-45da-89a6-c1b526b79910)
![image](https://github.com/discordjs/guide/assets/69713944/a32d5818-aa6d-4d70-86b8-b833d58ce7e5)
![image](https://github.com/discordjs/guide/assets/69713944/c7f72706-3488-4c2e-870e-43c7ce1358f6)

### Device (please complete the following information)

device: windows 11
browser: chrome
node.js version: v20.1.0
npm version: 9.1.1

**Comment by monbrey** [comment]
I found that on Windows I needed to downgrade the vite dependency to 2.5.0 in order to get this version of the guide to run.

Having said that, since the guide has been rebuilt on React and we're in the process of porting across content, it unlikely this is going to be fixed.
