### ISSUE TITLE
missing interactionCreate.js in cooldowns section of repo

### ISSUE THREAD

**Issue by emkirsh** [discordjs/guide#1474]
### Describe the bug

In the guide, I'm instructed to create an interactionCreate.js file for the event listeners, but in the repo, additional-features doesn't have an interactionCreate.js file.

Instead, in the repo, additional-features has cooldown code in index.js, making it harder to check code.

This is an issue because while I'm pretty sure I put the code in the right place, I can't say for certain and I have no reference to go by due to the missing interactionCreate.js file in the repo. I'm also getting "ReferenceError: client is not defined" when following the code as I think I'm supposed to, but again am unable to check what I must be missing because there is no file to reference.

### To Reproduce

1. go to [additional-features/cooldowns](https://discordjs.guide/additional-features/cooldowns.html) in the guide
2. follow instructions using interactionCreate.js
3. click the link at the bottom of the cooldowns guide to go to [the additional-features/cooldowns folder](https://github.com/discordjs/guide/tree/main/code-samples/additional-features/cooldowns) in the repo
4. notice a lack of any interactionCreate.js file in the repo
5. look in the index.js file to find similar code but not quite the same

also:
6. run the bot using the code the guide instructed you to write
7. try a command
8. get a referenceerror because client is not defined

### Screenshots

The github repo not having interactionCreate.js
<img width="665" alt="interactionCreate.js is nowhere to be found" src="https://github.com/discordjs/guide/assets/62123997/e9e519e8-778f-417a-92e6-7425f2432c83">

similar code in index.js
<img width="656" alt="similar code in index.js" src="https://github.com/discordjs/guide/assets/62123997/7bcdc5ce-f73c-4e5b-8a0f-b3481af77eaf">

------------------

My specific problem that could hopefully be solved with a reference file and/or update to the guide:

The guide clearly telling me to add `const { cooldowns } = client;` to interactionCreate.js
<img width="498" alt="the guide telling me to add this to interactionCreate.js" src="https://github.com/discordjs/guide/assets/62123997/00289568-fb51-4d14-9fbe-f8ec6fc48f72">

`const { cooldowns } = client;` throwing a ReferenceError
<img width="496" alt="the const { cooldowns } = client; failing" src="https://github.com/discordjs/guide/assets/62123997/342f6a2b-7816-46c3-b272-17983e6514df">

ESLint showing an error for client being undefined because it's in interactionCreate.js and not index.js where client was defined. 
<img width="337" alt="screenshot of const { cooldowns } = client" src="https://github.com/discordjs/guide/assets/62123997/e4f0aeb8-4ad3-4934-94a2-753f6bc0c4fe">

### Device (please complete the following information)

- Device/OS: Macbook Air M1 (2020) running MacOS 13.1
- NodeJS 18.16.0
- Visual Studio Code 1.78.2

### Additional notes

I want to mention that while having the sample code not up to date with the guide is frustrating, I'm really grateful for the fact that an official guide and sample code exists in the first place to help me learn. Despite this issue, the process of learning how to use discord.js has been so much friendlier thanks to the guide and I want to make sure you know I don't take it for granted. Thank you!

**Comment by TheKurara** [comment]
Not sure if you still need help but you can define Client in the InteractionCreate.js file. But there might be a better way than what I did, I am not really good at coding, just know a little bit about it. 
About the const {cooldowns} = client; the guide told you to add it in the InteractionCreate Event (in the index.js) and not in the InteractionCreate.js file because it did not use the InteractionCreate.js. I just added the first 3 lines in the attached image to the InteractionCreate.js and for me its working. 
![image](https://github.com/discordjs/guide/assets/104858885/226e9b2f-95a3-4bd7-9518-08e57ba95b99)

if you added client.cooldowns = new Collection() to index.js then you can remove it as you can add it in the InteractionCreate.js

**Comment by Idris1401** [comment]
> Thanks for the info, just out of interest why is it wrong? for me it worked the way I did. But as I said, I am not good at coding, I just tried to find a solution for it.

you're initializing a new client instead of getting the client instantiated this interaction

**Comment by thegamingsoul** [comment]
I am facing the same issue @emkirsh  (#1512).
If you have resolved the issue please let me know.

Also, @Idris1401 is right @TheKurara , initializing a new client in the interactionCreate.js file may not be the best idea as the context will change. 

I tried exporting the client variable to the interactionCreate.js file but it did not work.

**Comment by sdanialraza** [comment]
> I am facing the same issue @emkirsh (#1512). If you have resolved the issue please let me know.
> 
> Also, @Idris1401 is right @TheKurara , initializing a new client in the interactionCreate.js file may not be the best idea as the context will change.
> 
> I tried exporting the client variable to the interactionCreate.js file but it did not work.

Have you tried what Idris said? Using `interaction.client` instead of `client`?

**Comment by thegamingsoul** [comment]
@sdanialraza Yes, I tried that. I think just using `client` instead of `interaction.client` works when the interaction function is in the index file.

**Comment by sdanialraza** [comment]
Yes as `client` is defined in the index file, but otherwise, most structures have a `client` property, like `message.client`, `interaction.client`, etc.

**Comment by TheKurara** [comment]
> I am facing the same issue @emkirsh  (#1512).
> 
> If you have resolved the issue please let me know.
> 
> 
> 
> Also, @Idris1401 is right @TheKurara , initializing a new client in the interactionCreate.js file may not be the best idea as the context will change. 
> 
> 
> 
> I tried exporting the client variable to the interactionCreate.js file but it did not work.
> 
> 

Yes I know. Idris already wrote me why it's wrong.

**Comment by thegamingsoul** [comment]
Since this issue looks similar, please see  #1512 @emkirsh 
I was able to resolve the issue with some minor changes.
Please feel free to close the issue if it works.

**Comment by emkirsh** [comment]
@thegamingsoul I'll try it by the end of the week if not sooner!
