### ISSUE TITLE
DiscordAPIError[50001]: Missing Access

### ISSUE THREAD

**Issue by thdoan** [discordjs/guide#1481]
### Part of the guide or code sample the question is about

https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands

### Question

I followed the guide up to the step above, but when I executed `node deploy-commands.js` I got this error:

```
rawError: { message: 'Missing Access', code: 50001 },
```

The guide states "Your application will need the applications.commands scope authorized in a guild for any of its slash commands to appear, and to be able to register them in a specific guild without error" but there weren't instructions on how or where to define this scope. Here were the steps I took to try and set the scope:

1. Clicked on OAuth2
2. Changed AUTHORIZATION METHOD = In-app Authorization
3. Checked "application.commands"

However, when I clicked "Save Changes" button I got this error at the top:

**Private application cannot have a default authorization link**

I would like to deploy my test bot as a private bot if possible.

**Comment by thdoan** [comment]
I figured it out for those who got stuck at this step. Here's what you need to do:

1. Go to OAuth2 / URL Generator
2. Check "application.commands" and "bot" scopes
3. Copy the generated URL
4. Paste it into the browser
5. Follow instructions to add the bot to your server
6. `node deploy-commands.js`

**Comment by megatank58** [comment]
This is covered at https://discordjs.guide/preparations/adding-your-bot-to-servers.html
