### ISSUE TITLE
Slash command: "The application did not respond"

### ISSUE THREAD

**Issue by thdoan** [discordjs/guide#1482]
### Part of the guide or code sample the question is about

https://discordjs.guide/creating-your-bot/command-deployment.html

### Question

I've successfully followed [the guide](https://discordjs.guide/creating-your-bot/command-deployment.html) and I can see the slash command autocomplete. However, when I press Enter I get the "The application did not respond" error. In the console I see `[Flux] Dispatching MESSAGE_SEND_FAILED`.

My command file looks like this:

```
const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('ping')
    .setDescription('Test command'),
  async execute(interaction) {
    await interaction.reply('pong!');
  },
};
```

The bot has `bot` and `applications.commands` scopes.

**Comment by megatank58** [comment]
Please post full errors and ask common questions/issues in the (discord.js discord server)[https://discord.gg/djs).

**Comment by thdoan** [comment]
@megatank58 thanks, I'll do that. Do you have any advice on how to log more detailed error messages because all I see in Discord is "The application did not respond"?
