### ISSUE TITLE
How to build secret/hidden commands

### ISSUE THREAD

**Issue by WangHansen** [discordjs/guide#1490]
### Part of the guide or code sample the question is about

It looks like the `hidden command` was [implemented](https://github.com/discordjs/Commando/pull/206). But I couldn't find where in [class](https://discord.js.org/docs/packages/builders/main/SlashCommandBuilder:Class) I can specify it as hidden.

### Question

Commands should be able to be flagged as "hidden", preventing them from being listed in the built-in help command entirely.

**Comment by monbrey** [comment]
This is a 5 year old PR for a discord.js framework that is no longer functional.

Discord does not support any sort of "hidden command".
