### ISSUE TITLE
Status and Custom Status Message change

### ISSUE THREAD

**Issue by repiatx** [discordjs/guide#1491]
### Is your feature request related to a problem? Please describe.

I want to change to User Status and Custom messages. With the given permission this should not be a problem.

Im building a bot for Businesses which changes the User status on meetings or slash commands or other activities which im handling.

### Describe the solution you'd like

With this feature i believe lot's of people may have oppurtunity to came up with new ideas.

**Comment by Jiralite** [comment]
> Im building a bot for Businesses which changes the User status 

Bots can only modify their own custom status. Can you clarify what you mean?

**Comment by repiatx** [comment]
![image](https://github.com/discordjs/guide/assets/48159043/adf51faf-c249-4abd-b3aa-12eaad81a024)

I want my bot to change Users status. specified here.

**Comment by jaw0r3k** [comment]
Discord doesnt allow that

**Comment by Jiralite** [comment]
That is not possible as I've said. Also, what does this have to do with the guide?

**Comment by repiatx** [comment]
Ows sorry i thought this is discordJS feature request. ⭕  Sorry all.
