### ISSUE TITLE
MessageId changing when message is sent?

### ISSUE THREAD

**Issue by CookieHosting** [discordjs/guide#1499]
### Describe the bug

Unsure what exactly is going on but when i console log the message id or interaction id before the message is sent and then when the message i sent the message id changes. Is there a reason for this and if so whats a fix for this as i need it so i can edit the message from the id when a request is made.

### To Reproduce

```
module.exports.execute = async (client, interaction) => {
        const embed = new EmbedBuilder()
            .setColor(0x5FE88D)
            .setDescription(`**Successfully sent playerstats request**`)
            .setTimestamp();

        const message = await interaction.deferReply()
        message.edit({ embeds: [embed] })
        console.log(interaction.id, message.id)
};
```

### Device (please complete the following information)

Device: PC
OS: Windows 11
Browser: Using the desktop application but Brave is the browser i do use.
Version: Stable 225873 (a779bd2)

**Comment by almostSouji** [comment]
you are comparing a message id to an interaction id
