### ISSUE TITLE
guide-event-handling-interactionCreate.js

### ISSUE THREAD

**Issue by thegamingsoul** [discordjs/guide#1512]
### Part of the guide or code sample the question is about

https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files

Under the topic 'Event handling' two files need to be created i.e., ready.js & interactionCreate.js in a folder 'events'.

<img width="1020" alt="Screenshot 2023-10-16 at 12 47 53 AM" src="https://github.com/discordjs/guide/assets/72296875/11366734-b6b2-49c8-b66a-ef64e297b573">

### Question

This github repository has the interaction function in the index file.
However, as per the guide (linked above), I created two separate files.

ready.js runs fine, but as soon as I try slash command in the discord server, it throws an error  <ReferenceError: client is not defined> at the line: const command = interaction.client.commands.get(interaction.commandName);
[Screenshot attached]

I tried exporting the client variable separately.

Also, the Tip in the guide says: _In most cases, you can access your client instance in other files by obtaining it from one of the other discord.js structures, e.g. interaction.client in the interactionCreate event. You do not need to manually pass it to your events._

**Comment by Idris1401** [comment]
line 16 my man, not line 9

**Comment by thegamingsoul** [comment]
Oh, yes. I see @Idris1401 thanks for that. It is line 16.

**Comment by thegamingsoul** [comment]
@Idris1401 Thanks man. It works fine now. Till now I was under the assumption that it is line 9.
`const {cooldowns} = interaction.client;` along with the import statement `const { Collection } = require("discord.js");`
<img width="892" alt="Screenshot 2023-10-16 at 3 37 10 PM" src="https://github.com/discordjs/guide/assets/72296875/1ed044f6-afe1-4d6f-b0c0-096943023c08">

**Comment by thegamingsoul** [comment]
**Resolves  #1512**
This repository doesn't have a separate interactionCreate.js file as mentioned in the guide `https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files`. Which is why client doesn't need a reference but using client in other / separate files would need a reference i.e. `interaction.client` in place of `client`.

1. Go to the interactionCreate.js file
2. when declaring cooldown in the execute function, assign `const {cooldowns} = interaction.client` in place of `const {cooldowns} = client`.
3. This will work just fine, but you might also require `Collections` class from discord.js. Therefore, add `const {Collections} = require ("discord.js")`

Refer to the above screenshot.
Closing the issue.

Thanks @Idris1401 for your observation.

**Comment by Idris1401** [comment]
> **Resolves #1512 & #1474** This repository doesn't have a separate interactionCreate.js file as mentioned in the guide https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files Which is why client doesn't need a reference but using client in other / separate files would need a reference i.e. `interaction.client` in place of `client`.
> 
> 1. Go to the interactionCreate.js file
> 2. when declaring cooldown in the execute function, assign `const {cooldowns} = interaction.client` in place of `const {cooldowns} = client`.
> 3. This will work just fine, but you might also require `Collections` class from discord.js. Therefore, add `const {Collections} = require ("discord.js")` at the top
> 
> Refer to the above screenshot. Closing the issue.
> 
> Thanks @Idris1401 for your observation. I think this should be added in the documentation.

that was just a mistake from you
