### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by wmslei** [discordjs/guide#1516]
### Describe the bug

Send one file with AttachmentBuilder in a message, but sometimes two are displayed in discord. I'm not sure if this is a problem with discord UI or the discord.js SDK.

### To Reproduce

https://discord.com/channels/1080050008235188316/1145682916177887243/1171274069170208929

### Screenshots

![20231107-110259](https://github.com/discordjs/guide/assets/1061488/96d1583f-984d-4c8a-8725-bd3493050a24)
![20231107-110327](https://github.com/discordjs/guide/assets/1061488/c42c4584-3f04-4b08-b45c-95462e580cf4)

### Device (please complete the following information)

node v18.18.2
discord.js v14.13.0

### Additional notes

My code like below:

await channel.send(
{
    content: 'some message',
    files: [new AttachmentBuilder(url, {name: 'filename.mp4'})],
    components: [
      new ActionRowBuilder<ButtonBuilder>().setComponents(
        new ButtonBuilder().setStyle(ButtonStyle.Link).setURL(url).setLabel(name)
      ),
      new ActionRowBuilder<ButtonBuilder>().setComponents(
        new ButtonBuilder().setStyle(ButtonStyle.Secondary).setCustomId('custom_id').setEmoji('🔄');
      ),
    ],
  }
)

**Comment by Jiralite** [comment]
We cannot look over message links we do not have access to. We also cannot read minds (we do not know what you are doing, your Node.js version, your discord.js version, any sample or reproducible code, etc.).

**Comment by wmslei** [comment]
> We cannot look over message links we do not have access to. We also cannot read minds (we do not know what you are doing, your Node.js version, any sample or reproducible code, etc.).

I updated the report information, the same code normally should look like the screenshot below, but sometimes the above screenshot appears.

**Comment by Jiralite** [comment]
Issue duplicated over at https://github.com/discordjs/discord.js/issues/9972.
