### ISSUE TITLE
Issue in retrieving reactions while processing old messages

### ISSUE THREAD

**Issue by ibrahimahmed443** [discordjs/guide#154]
I have followed [this](https://github.com/discordjs/guide/blob/master/code-samples/popular-topics/reactions/raw-event.js) snippet to retrieve reactions on old/uncached messages from discord. While this works fine, I am facing a problem in retrieving users list who reacted on the message.

My goal is to be able to receive reactions on messages, as well as usernames who reacted. For this, I am using `messageReactionAdd` and `messageReactionRemove` events; then inside the event, I use `message.reactions.users`. This works fine on cached messages, i.e I am able to retrieve users list who reacted. However, when working with the raw event as described in the snippet, `message.reactions.users` is always an empty list.

I hope I made myself clear. Please let me know if you need any more information.

**Comment by PLASMAchicken** [comment]
You need to fetch the Reactions

**Comment by almostSouji** [comment]
The referenced snippet is not fully applicable for all usecases.
You might want to look at #165 for a workaround or try fetching the reactions as chicken recommended above.

We decided to pause handling of this topic on the guide until partial structures land on a stable version of discord.js and then provide a proper way to handle it. Sorry for the inconvenience!
