### ISSUE TITLE
Unclear documentation - what does 'target' mean

### ISSUE THREAD

**Issue by Lauro235** [discordjs/guide#1541]
### Part of the guide the question is about

There are a number of times that the term 'target' is used to explain a method, however in most if not all cases this term is not given context. In the getRole('target') example, it would be helpful to know if the 'target' was the role id or the the role name provided as a string.

It would also be helpful if the getRole method could be officially written about in the documentation. It's all too vague for me. The same applies for the other methods like getMentionable, getMember etc.

## Examples

[guide/slash-commands/parsing-options.md](https://github.com/discordjs/guide/blob/44c0c4891c18d55d12c43ea6c76fe85947bd2200/guide/slash-commands/parsing-options.md?plain=1#L45)

…in the guild where the command is being run, you can also use `.getMember('target')` to get their `GuildMember` object.

[guide/popular-topics/faq.md](https://github.com/discordjs/guide/blob/44c0c4891c18d55d12c43ea6c76fe85947bd2200/guide/popular-topics/faq.md?plain=1#L53)

`### How do I add a role to a guild member?`
```js
53 | const role = interaction.options.getRole('role');
54 | const member = interaction.options.getMember('target');
55 | member.roles.add(role);
```

At a minimum, please update so that we know if 'target' is a stand in. If it is a stand in, then please provide information on what it is a stand in for.

Thank you for reading.

### Question

Please can we provide more context for the meaning of the word 'target' in its various contexts?

**Comment by sdanialraza** [comment]
`'role'`, `'target'`, etc. are the option names you want to get the value of, these methods are documented [here](https://discord.js.org/docs/packages/discord.js/14.14.1/CommandInteractionOptionResolver:Class).

**Comment by Lauro235** [comment]
Thank you for your response. I think there was another issue with my code so I will mark this as resolved. Thanks again for your time.
