### ISSUE TITLE
Let's comfortably reach more communities

### ISSUE THREAD

**Issue by LscWFr713** [discordjs/guide#1545]
### ¿Why do I write to you?

Since I started on the internet, **I had to talk about the majority most of sites I visited being in English**. I had always needed many guides, tutorials and resources to _strengthen my empirical knowledge_ and get into different areas of programming (which is a branch of study and practice that I love). Unfortunately, **almost everything was in English**, and a few years ago (when I was much smaller), I used just google translator to understand those resources that would allow me, for example, to build my first Discord bot. 

I remember very well the satisfaction I felt when I realized that (**after having had problems and leaving him for a few weeks**) I had finally managed to follow his guides correctly and start my first Discord bot, in front of the visual guides on YouTube that They gave me a lot of problems when monitoring. 

But the problem lies in my problems (excuse me for redundancy), **it took me months to get a bot built with your guide**, and it wasn't because there had been any problem on your page, but because of the problems you experienced with my accessibility. **Google translator** can be useful, but it has **ambiguous translations**, is **extremely inopportune at times** (translates syntax) and **warps the code sections on the page**. 

> I'm sure if, it weren't for those problems, I would have calmly continued developing my bot in the same mood as the first time, instead of leaving it until years later.

### What I want to improve

In the guide I have not been able to notice or find any button or option that allows me to change the language natively (if it exists please let me know), it seems that **Spanish speakers like me can only use the useful and imperfect Google translator as an almost instinctive solution**.

### As I think it can be improved

So it came to mind to write to them about this problem and propose a new **language support** I recently learned of its new update as a page, and _I was hoping to find support at last, but it wasn't included_ (or at least I didn't notice it in sight). 

That is why I would like and it seems to me that it would be a great improvement with **great benefits that would add multi-language support**, something not so simple (_because I know how difficult and laborious it can be to implement that on a large page_), but that If done, it would have significant and valuable weight in the discord guide.

First of all and more high-profile, **they would increase page traffic**. Like me, there must be many more people who become demotivated by having to learn how to create their first bot on an all-English page having started programming and, for a change, without the slightest knowledge in English. 

I know I'm being very sentimental maybe, but I think that even if the programming world forces you to learn English (just as I did and I can enjoy its guide by "patching" the errors of the Google translator), you **shouldn't be very perfused to initiates in this world to simultaneously learn English to learn a programming language**. As happened to me.

**I don't know any other guide**, at least in my language (and that is easy to find), **that is as clear, complete and organized as yours**. When I discovered it, 5 years ago, it was like a hobby to start reading it and researching how to create a discord bot while learning more and more JS. 

> I think this big page only needs multi-language support, because of the rest of the things, it is already perfect.

### Additional notes

Finally, if this proposal is very laborious to implement for you, and you are thinking of ignoring it in the face of that difficulty **I propose and give my full support to translate the page**, at least in my language and voluntary mode, in a coherent, punctual and organized way. **I would very much like to collaborate with this page** that helped me strengthen my notions of JS years ago and causes me greater interest in programming: the career I planned to study.  **Thank you very much for reading until the end**, Lusasaja says goodbye.

**Comment by almostSouji** [comment]
We are not planning to offer native translations for the guide at this point. 
This has to do with how the guide is currently set up, iterated, and maintained.

You are free to fork the project and host your translation (as done by the discord.js japan user group, for example, <https://github.com/discordjs-japan/guide>) following the MIT license <https://github.com/discordjs/guide/blob/main/LICENSE>

**Comment by Monoverde888** [comment]
hay una version parcialmente traducida al español, es https://github.com/NejireSupremacy/guide
https://discordjs-guide-es.netlify.app/#antes-de-empezar

**Comment by Lusasaja23** [comment]
Nice
