### ISSUE TITLE
Use glob instead of fs

### ISSUE THREAD

**Issue by mallusrgreatv2** [discordjs/guide#1547]
### Is your feature request related to a problem? Please describe.

Most people have a problem understanding the structure of the folders when it comes to command handlers in the guide. 

### Describe the solution you'd like

Using glob will help with nested folders as well has non-nested folders, but making the guide just a little harder to understand.
https://www.npmjs.com/package/glob
Glob can also be promisified using node:util. Node supports top-level await as well.

**Comment by Qjuh** [comment]
There‘s a PR for that already: #1486

**Comment by Jiralite** [comment]
https://github.com/discordjs/guide/pull/1486#issuecomment-2336398839
