### ISSUE TITLE
Sequential Steps

### ISSUE THREAD

**Issue by TinnyTerr** [discordjs/guide#1564]
### Is your feature request related to a problem? Please describe.

In the section, creating your bot, the steps aren't sequential, dropping things previously added (eg after deploying commands, event handler only uses command handling and drops the in-between completely)

### Describe the solution you'd like

It should be step by step instead of going back and having to figure out what changed and what differences you need to put in.
![Untitled1](https://github.com/discordjs/guide/assets/168141209/d6bf0659-c96f-4591-86c3-d6bc86b63dfd)

### Additional notes

I'm happy to make the fix if this isn't intended. Just getting feedback to see if this is intended or not.

**Comment by Jiralite** [comment]
> eg after deploying commands, event handler only uses command handling and drops the in-between completely

Can you elaborate on this, please?

**Comment by TinnyTerr** [comment]
> Can you elaborate on this, please?

## In command handling
You create a collection and push commands to it.
```js
client.commands = new Collection();
// ...
if ('data' in command && 'execute' in command) {
	client.commands.set(command.data.name, command);
}
```
## In command deployment
You create an array of commands and push to it, completely disregarding the collection:
```js
const commands = [];
// ...
if ('data' in command && 'execute' in command) {
	commands.push(command.data.toJSON());
}
```
## In Event handling
You go back to command handling, using the collection and completely removing anything relating to deploying the commands
```js
client.commands = new Collection();
// ...
if ('data' in command && 'execute' in command) {
	client.commands.set(command.data.name, command);
}
```

# Picture side by side, the bit I am getting at is highlighted:
![image](https://github.com/discordjs/guide/assets/168141209/b78e1c8a-3601-4a50-b49c-2dbe79fae702)

**Comment by Jiralite** [comment]
> You create an array of commands and push to it, completely disregarding the collection:

> You go back to command handling, using the collection and completely removing anything relating to deploying the commands

In command deployment, a standalone file is created called deploy-commands.js. It does not disregard the earlier collection. In fact, they are not related. These statements are not correct.

This seems to be an issue of how you are reading the guide. Registering commands tells you to create a file called deploy-commands.js—not put it all in index.js. It even states this:

> This script is intended to be run separately

It will not affect your main file.

Once you finish creating commands, you are to create a deploy-commands.js file. This file is what you run to deploy your commands. Then, you may proceed to event handling, which returns to index.js. Notice how in event handling there is a [deploy-commands.js](https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files) file in the individual event files section.
