### ISSUE TITLE
Option Support For Modals

### ISSUE THREAD

**Issue by Debuglt** [discordjs/guide#1566]
### Is your feature request related to a problem? Please describe.

There is no direct problem with the lack of support for options in modals, however this would greatly improve my development on a recent project I've been working on.

I have managed to make an account/subscription management and auth system using Discord.js and Express.js combined with the bot controlling registered account management while the Express API controls the authentication in combination with oAuth.

Part of this system I've created there is a lot of management one example being for configuring product staff members & their specific permissions for managing products, for configuring permissions it would be a great improvement if options were supported similar to slash command preset string options but in modals.

### Describe the solution you'd like

I would like ModalBuilder to support adding preset options in a drop down so when configuring staff members specific product management permissions in my system the configure permissions modal can be something along the lines of;

(Option Title)
Extend Subscriptions
(Option Choices)
true / false

(Option Title)
Revoke Subscriptions
(Option Choices)
true / false

... Other Options Here

I feel this wouldn't be incredibly hard to implement to Discord.js and would greatly improve the quality of life my system I've setup, the logic is already in place for options on slash commands but I would love to see it on modals!

### Describe alternatives you've considered

I've considered just using text inputs in the configure modal where the configuring user would have to type out true/false, with this solution requires extra content validation to ensure the configuring user entered true/false or what ever the modal expects but this is extra validation work & less convenient.

### Additional notes

I tried searching for this in the Discord.js documents & have discovered it to be not currently possible, if I am incorrect in believing options in modals isn't possible please state the source.

**Comment by Qjuh** [comment]
discord.js as a wrapper library for the Discord API can only provide you with what Discord itself supports. So your feature request is addressing the wrong people here, ask Discord. Like many other users haver done before and none of them have been heard.
