### ISSUE TITLE
Add a description field to the modals

### ISSUE THREAD

**Issue by Dreamwxve** [discordjs/guide#1584]
### Is your feature request related to a problem? Please describe.

No, it is not.

### Describe the solution you'd like

I feel like having a description under the title of a modal would be very useful as having long placeholders or extra information on an interaction/embed can me moved to on the modal, if that makes sense

### Describe alternatives you've considered

N/A

### Additional notes

Obviously, a character limit would be required and I'm proposing 250

**Comment by monbrey** [comment]
discord.js cannot implement new functionality to Discord - please direct your feature request to Discord.
