### ISSUE TITLE
Possible misspell in tutorial #basic-arguments

### ISSUE THREAD

**Issue by blackborg89** [discordjs/guide#176]
https://discordjs.guide/creating-your-bot/commands-with-user-input.html#basic-arguments

Shouldn't there be **if** at the beginning? Because it doesn't work with else if, but works with if. Took me a while to figure it out.

```
// using the new `command` variable, this makes it easier to manage!
// you can switch your other commands to this format as well
else if (command === 'args-info') {
	if (!args.length) {
		return message.channel.send(`You didn't provide any arguments, ${message.author}!`);
	}

	message.channel.send(`Command name: ${command}\nArguments: ${args}`);
}
```

**Comment by tipakA** [comment]
I believe that's intended, due to fact that in that point of guide (if you would follow it) you would most likely already have few commands in format if () {} else if () {}.

**Comment by blackborg89** [comment]
Following the guide and testing the code as illustrated, gives an error, unless i replace it with **if**

```
client.on('message', message => {
	if (!message.content.startsWith(prefix) || message.author.bot) return;

const args = message.content.slice(prefix.length).split(' ');
const command = args.shift().toLowerCase();

// using the new `command` variable, this makes it easier to manage!
// you can switch your other commands to this format as well
if (command === 'args-info') {
	if (!args.length) {
		return message.channel.send(`You didn't provide any arguments, ${message.author}!`);
	}

	message.channel.send(`Command name: ${command}\nArguments: ${args}`);
}
});
```

**Comment by tipakA** [comment]
Well, note above clearly says that this part reuses code from previous one.

**Comment by Danktuary** [comment]
The first two lines in that codeblock:
```js
// using the new `command` variable, this makes it easier to manage!
// you can switch your other commands to this format as well
```
That page, as previously mentioned, states that it bases its code off of the previous one. It does tell you to add a few lines, but doesn't tell you to remove any. If you look at the page before, you'll notice some codeblocks also start with `else if()`, because we've already made a few commands at that point and are only adding on to them. It's all intentional.

**Comment by blackborg89** [comment]
Totally my fault, thanks guys.
