### ISSUE TITLE
More specified help command

### ISSUE THREAD

**Issue by ClashWithMeYT** [discordjs/guide#186]
Hello, in your Command Handler: Additional Features page, you only specified how to list all commands, but can you also explain how to list a category of commands, like utility commands only or fun commands only etc.

**Comment by almostSouji** [comment]
Thank you for the suggestion! 
The help command guide is more meant as a general idea and can be expanded upon in many different ways, covering all of which is not job of this guide.

However I think it is worth adding a tip on custom command properties and the filterable nature of the commands Collection, which i have done in ef79fc7
