### ISSUE TITLE
(node:3208) UnhandledPromiseRejectionWarning: ReferenceError: applyText is not defined

### ISSUE THREAD

**Issue by Zel9278** [discordjs/guide#198]
I tried to put the code into my bot, but I get an error.

**Comment by Monbrey** [comment]
This doesn't seem like a problem with the guide. Please close this issue and go to the Discord.js support server for assistance.

**Comment by Zel9278** [comment]
https://github.com/discordjs/guide/blob/master/guide/popular-topics/canvas.md
I did see this.

**Comment by Monbrey** [comment]
The applyText function is defined in the second codeblock of the Adding in Text section
https://github.com/discordjs/guide/blob/master/guide/popular-topics/canvas.md#adding-in-text

Please dont open issues on Github because you copy pasted some, but not all, of the code.

**Comment by idk-pixel** [comment]
Ah, this happened to me too! Thanks!
