### ISSUE TITLE
Adding information on long arguments.

### ISSUE THREAD

**Issue by garageagleMC** [discordjs/guide#200]
I'm trying to make a command with what I call _long arguments_. When I do `!args-info "This is a long arg"` it responds with
 `Arguments: "This,is,a,long,arg"
Arguments length: 5`
but If a user puts words in quotes, I want to make it be one long argument. eg:
`Arguments: This is a long arg
Arguments length: 1`
I think there should be a section on this.

**Comment by Danktuary** [comment]
What you want could be achieved through some regex and an argument parser. The guide just gives you a basic outline to get you started, you should use a framework for more complex features. Commando handles this and we have [a page explaining arguments in Commando](https://discordjs.guide/commando/args.html), so I'd recommend you check that out. 😄
