### ISSUE TITLE
Web Dashboard Tutorial Request

### ISSUE THREAD

**Issue by 1337gamerman** [discordjs/guide#215]
A tutorial on how to make a super simple HTML base for a web dashboard and how to connect to it from a website would be really nice. I can't find one and I've been trying to do this for a while. I'm new to website stuff and I've been told WebSockets and stuff are necessary but a simple example would be really cool.

**Comment by Danktuary** [comment]
I have an [unfinished dashboard project](https://github.com/Danktuary/discord-bot-dashboard) that I wanted to finish and make it so that anybody can clone and easily use it, but I haven't touched it in a while. If someone with Vue or Discord OAuth experience wants to help, I'd put some more work towards it too.

**Comment by TheOnlyArtz** [comment]
I have an example called ["Seday"](https://github.com/TheOnlyArtz/Seday)

**Comment by IntelligentPickle** [comment]
Sorry if this counts as bumping, but I also want to try building a dashboard for my bot. I'm not exactly sure how to do something like that, so I'm wondering is anybody here knows how to. :)

**Comment by CamdanMead** [comment]
It's really straightforward, you just need to create a website that uses the same database as your bot. (I.E. Keyv, Sequelize, MongoDB, MySQL, etc.)

There's other ways, but that's the most straightforward.

**Comment by conqr2** [comment]
Working on one, please be patient.

**Comment by conqr2** [comment]
Takes a long time due to the fact you must migrate to a VPS, add a (sub)domain, add express, add oauth, db, etc.

**Comment by code913** [comment]
I made a website for my bot by running an `expressjs` instance in my `index.js` file (i love messy stuff) and I can easily connect my configs by using my `quick.db` database to set a config for the server that the logged in user decided. Never tried tho, [you can fork my public repo](https://github.com/@code913/codeco-backup-repo) and test it. (yes I made my whole bot public)

**Comment by mainboiii** [comment]
Would love to take a look but it says there is no repo with that link?

**Comment by code913** [comment]
> Would love to take a look but it says there is no repo with that link?

oops put `@` in my name

**Comment by almostSouji** [comment]
This issue is about a feature request for the discord.js guide, please don't use the space to advertise your own projects.
