### ISSUE TITLE
Multiples folders for Command Handler

### ISSUE THREAD

**Issue by Asviix** [discordjs/guide#225]
I currently have about 80 commands, so 80 js files in my commands folder, I wonder if there's a way for fs to loop through each folder in the command folder to have categories like "Moderation", "Fun" etc... so it's less a mess in there.

Any ideas ?

**Comment by recapitalverb** [comment]
I guess `fs.readdir` will do what you are looking for.
https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback

**Comment by Asviix** [comment]
Yep, worked, thanks !
