### ISSUE TITLE
help command says function map of undefined cannot be read

### ISSUE THREAD

**Issue by kuenzif** [discordjs/guide#236]
ive done it exactly as it is listed in the guide and i still get an TypeError: Cannot read property forEach of undefined.
Does anyone have an idea why this error happens and how i can resolve it?

Attached are error logs & a code snippet (help.js) where the error happens.

Thank you very much in advance!

Help.js code snippet
![codesnippet](https://user-images.githubusercontent.com/49710677/60153452-8fa7fe80-97e4-11e9-9be7-bff45a570722.PNG)

Error Log (PM2)
![consoleerror](https://user-images.githubusercontent.com/49710677/60153453-8fa7fe80-97e4-11e9-8520-0313374a0bd6.PNG)

**Comment by Monbrey** [comment]
That errors suggests that `cmds` is undefined - no property with that name was destructured from `msg.client`

**Comment by kuenzif** [comment]
yes, just noticed it. Changed the name to commands and now it works! thanks for your help <3
