### ISSUE TITLE
Issue with example on reacting to emojis

### ISSUE THREAD

**Issue by k9thebeast** [discordjs/guide#243]
```
const filter = (reaction, user) => {
	return ['👍', '👎'].includes(reaction.emoji.name) && user.id === message.author.id;
};
```

Should be

```
const filter = (reaction, user) => {
	return ['👍', '👎'].includes(reaction.emoji.name) && user.id !== message.author.id;
};
```

Notice the not equals sign

https://discordjs.guide/popular-topics/reactions.html#awaiting-reactions

**Comment by Danktuary** [comment]
This change wouldn't match with the rest of the code though. The replies start with "you" and use `message.reply()`, which prepends a ping to the message author.

**Comment by k9thebeast** [comment]
But the message author is the bot in this example, the bot doesnt want to reply to itself. Which it was doing before I changed it.

**Comment by tipakA** [comment]
Then you most likely skipped part when we react to the message *before* awaiting any reactions, or did it in different way than in the example.
