### ISSUE TITLE
Discord Bot API Incorporation

### ISSUE THREAD

**Issue by 26841** [discordjs/guide#250]
I'm interested in working on a bot that, for the time being, can read data from a Google Sheets document and also send a message on a specific date every year. The latter will involve sending different messages on different dates.

I was referenced to these APIs to use, but I'm not sure how to incorporate them to the bot code:
https://www.npmjs.com/package/node-schedule
https://www.npmjs.com/package/google-drive-sheets

I'm less concerned about code elegance and more on actually getting it to work.

**Comment by Monbrey** [comment]
Not really sure what this has to do with our guide. I'd recommend you go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9

Might be able to ask about these packages in the #other-js-questions channel

**Comment by 26841** [comment]
Alright, thank you.
