### ISSUE TITLE
Misleading guide page

### ISSUE THREAD

**Issue by megastary** [discordjs/guide#251]
guide/miscellaneous/parsing-mention-arguments.md

contains function getUserFromMention which in the first part is made error proof and returns undefined when no user is mentioned or args aren't mention.

Later in that page there is remake of that function with RegEx, which is literally commented:"See? That is much shorter, and not that complicated. If you run your bot again now everything should still work the same."

But this function lacks basic error handling and crashes bot when provided with invalid args(not mention)

**Comment by tipakA** [comment]
I think that simple `if (!matches) return;` after the line with `match()` with would fix all issues that occur when arg that was passed is not a mention.
However, not sure if adding a check if anything was passed, since in example without regex above, function only gets called if there is `args[0]`

**Comment by megastary** [comment]
You are indeed right that simple `if (!matches) return;` before `const id = matches[1];` fixes the code and it most certainly should be added to the code in wiki page. Otherwise it doesn't work same way as function without RegEx as that function can handle both no args and args without mention or other unexpected args. 

RegEx example however is called if there is **any** arg and tries to return match[1] which doesn't exist if the RegEx didn't match any user ID.

Example command: 
`!avatar thisisnotmention`

Result:
`TypeError: Cannot read property '1' of null`
