### ISSUE TITLE
ready status.

### ISSUE THREAD

**Issue by Uthsho** [discordjs/guide#261]
how to show how many shards a bot has on status?

**Comment by almostSouji** [comment]
Setting the status: <https://discordjs.guide/popular-topics/common-questions.html#how-do-i-set-my-playing-status>
Shard count: <https://discord.js.org/#/docs/main/stable/class/ShardClientUtil?scrollTo=count>

For future problems:
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9

This issue tracker is only for bug reports and enhancement suggestions.
