### ISSUE TITLE
Discordjs.guide website not responding...?

### ISSUE THREAD

**Issue by NovaLynxie** [discordjs/guide#277]
Hi there DiscordJS,
I have been using your site recently for reference to code in discord.js but today for some reason I cannot get to the site at all or navigate to other pages on your site from currently open pages from the website. I was able to load the website page yesterday.
I've tried refreshing my browser page and using other browsers with no luck.
I don't know where else I can report this other than here, is anyone else unable to access the site?

**Comment by Danktuary** [comment]
Hey, sorry, seems like the domain expired today and apparently wasn't on auto-renew for some reason. Should be back now!
