### ISSUE TITLE
Sending a message to a specific guild/channel

### ISSUE THREAD

**Issue by zXRennyXz** [discordjs/guide#280]
Could you do a guide for this?

**Comment by almostSouji** [comment]
Thank you for the suggestion, however there is already one: <https://discordjs.guide/popular-topics/common-questions.html#how-do-i-send-a-message-to-a-certain-channel>.

To send to a specific guild you'd still need to find a channel on said guild. You can do this by utilizing [Collection#find](https://discord.js.org/#/docs/main/stable/class/Collection?scrollTo=find) on the guilds `.channels` collection, where you can search for the respective criteria (channel type, certain permissions so you can even send there etc... for which you find approaches in later chapters of the guide).
