### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: applyText is not defined 

### ISSUE THREAD

**Issue by goldentg** [discordjs/guide#288]
`UnhandledPromiseRejectionWarning: ReferenceError: applyText is not defined
    at Client.client.on (C:\Golden Gate\index.js:49:2)`

**Comment by almostSouji** [comment]
I suggest reading the full guide, or at least the complete relevant chapter, not starting midway through. The utility function `applyText` is defined in the section [Adding in text](https://discordjs.guide/popular-topics/canvas.html#adding-in-text) (second code block) of the canvas guide.

If you are unsure if you followed everything correctly you can review the code sample linked in the [Resulting Code](https://discordjs.guide/popular-topics/canvas.html#resulting-code) section.
