### ISSUE TITLE
Not working Canvas welcome

### ISSUE THREAD

**Issue by namekinggamerboy** [discordjs/guide#298]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**

**Additional notes**

**Comment by tipakA** [comment]
This issue is invalid in its current form. Please add any details regarding "not working" of the example.
The issue template is there for a reason and shouldn't be removed nor left empty.

You can also join [Discord server](https://discord.gg/bRCvFy9) and explain the issue in faster and easier way.

**Comment by namekinggamerboy** [comment]
So me errors
![Screenshot_2019-12-18-16-52-40-716](https://user-images.githubusercontent.com/53903319/71082309-e18b7900-21b6-11ea-8e99-9a37b331a02d.jpeg)
![Screenshot_2019-12-18-16-52-28-248](https://user-images.githubusercontent.com/53903319/71082312-e18b7900-21b6-11ea-912f-b4e3ca01877b.jpeg)
![Uploading Screenshot_2019-12-18-16-52-17-065.jpeg…]()
![Uploading Screenshot_2019-12-18-16-52-03-650.jpeg…]()
![Uploading Screenshot_2019-12-18-16-51-52-830.jpeg…]()

**Comment by namekinggamerboy** [comment]
![Screenshot_2019-12-18-16-52-17-065](https://user-images.githubusercontent.com/53903319/71082374-01bb3800-21b7-11ea-8538-19f164af0455.jpeg)
![Uploading Screenshot_2019-12-18-16-52-03-650.jpeg…]()
![Uploading Screenshot_2019-12-18-16-51-52-830.jpeg…]()

**Comment by namekinggamerboy** [comment]
![Screenshot_2019-12-18-16-51-52-830](https://user-images.githubusercontent.com/53903319/71082398-0d0e6380-21b7-11ea-98ed-d1b853a2e940.jpeg)

**Comment by namekinggamerboy** [comment]
![Screenshot_2019-12-18-16-52-17-065](https://user-images.githubusercontent.com/53903319/71082407-11d31780-21b7-11ea-93e5-155a7eb32a21.jpeg)

**Comment by namekinggamerboy** [comment]
How to fix sir please help me

**Comment by vzwGrey** [comment]
For questions about the library please see [our Discord server](https://discord.gg/bRCvFy9).
This issue tracker is only for bugs, faults and suggestions for the library, not for individual support.

**Comment by namekinggamerboy** [comment]
I am already join
![Screenshot_2019-12-18-17-09-01-867](https://user-images.githubusercontent.com/53903319/71083497-26b0aa80-21b9-11ea-8175-3fe16389a041.jpeg)

**Comment by almostSouji** [comment]
We quite recently evaluated that the canvas guide - if followed correctly - does indeed produce a working outcome. If you really did find a bug in the guide please provide more information about the issue, the code used and in an easier to read form. *

Before you do so please make sure to again fully follow the guide example and start modifying it just after you had it working as it is provided. For an evaluation of these modifications the #other-js-questions channel on the discord server is more suited than this issue tracker.

The bug preset is meant for bugs in guide code, not any bugs you might encounter in your own interpretation of it. For a quicker feedback please ask your question on the discord server, as suggested by others.

If you actually find a bug with the guide code feel free to re-open this issue or create a new one. At the current time however I can not see any fault in the guide.

_\* For example uploading the __full__ error including its stack-trace to a gist/hastebin/pastebin or however else these services might be called. In the current form it is quite hard to deduce any meaning from the provided screenshots_

**Comment by namekinggamerboy** [comment]
Welcome not send photo or message log check out error show

**Comment by namekinggamerboy** [comment]
Dm. Me in ⏺️NAME BOY⏺️#2751

**Comment by almostSouji** [comment]
The same issue has turned up for other people: for example here https://github.com/Automattic/node-canvas/issues/1073 and seems to be happening due to a mis-match in the version of canvas you use, please make sure you use 2.6 or later as suggested by our canvas guide, we can only guarantee the provided solutions to work with that version.

**Comment by namekinggamerboy** [comment]
Ya i am check out and edit but not working code my other friends try but not working

**Comment by namekinggamerboy** [comment]
Please dm me

**Comment by almostSouji** [comment]
Please understand that we do not provide support via direct message and make sure you used the correct version of canvas with your code

**Comment by namekinggamerboy** [comment]
I am use Canvas my bot use Canvas

**Comment by namekinggamerboy** [comment]
But not working your code
My Canvas code working but all other  servers send my server send photo

**Comment by almostSouji** [comment]
Again, suggested by your error you are using the wrong **version** of canvas. The guide is written with 2.6 in mind, the behavior of the import and the resulting error tell me that you very likely do not use that version but an older one, which results in the shown error because canvas changed their public facing methods.
