### ISSUE TITLE
Unavailable in Russia

### ISSUE THREAD

**Issue by asc11cat** [discordjs/guide#302]
The following sites are currently unavailable in Russia:
- https://discordjs.guide/
- https://anidiots.guide/
Is there any info about it? I dont see any blocks in RKN blacklist(https://eais.rkn.gov.ru/en/#form) with this ip addresses/domain names. VPN is a thing, but still.

**Comment by asc11cat** [comment]
After a small research i can see what cloudflare ip(104.31.65.82) of https://anidiots.guide/ is currently [banned by RKN](https://i.imgur.com/0IwViWV.jpg), so https://discordjs.guide might have the same issue?

**Comment by asc11cat** [comment]
As i see https://discordjs.guide/ changed IP and now its working fine! Thanks!

**Comment by asc11cat** [comment]
Aaaaand its stopped working again.

**Comment by DevYukine** [comment]
I can't reproduce this behavior, both websites work perfectly fine for me and as you mentioned that you live in Russia i assume this is a block from your government/ISPs (On some Cloudflare IPs) and there is nothing we can do about that.

**Comment by asc11cat** [comment]
> I can't reproduce this behavior, both websites work perfectly fine for me and as you mentioned that you live in Russia i assume this is a block from your Government/ISPs (On some Cloudflare IPs) and there is nothing we can do about that.

Yeah, thats a government(RKN) block, and thats why im asking if its possible to change cloudflare ip so it will be available, because only cloudflare ip is banned. As i said - if devs cant do it, i will try to  send request to RKN, thats why i was waiting for answer.

**Comment by Danktuary** [comment]
We use [Netlify](https://www.netlify.com/) to host the guide, we don't have control over the IP settings.
I think you should send a request to the RKN to get it solved.

**Comment by asc11cat** [comment]
> We use [Netlify](https://www.netlify.com/) to host the guide, we don't have control over the IP settings.
> I think you should send a request to the RKN to get it solved.

Okay, got it, thanks for feedback anyways.
