### ISSUE TITLE
XP/Level System

### ISSUE THREAD

**Issue by shahoob** [discordjs/guide#303]
Basically what i mean is:

- A bot that has leveling system
- which you gain xp by messaging
- And You will level up when you gained some xps (Like 10 xps)

I searched on google, I get a system that's using JSON.
I don't want it, I only want the Sequelize.
Search again, Same, SQLite, Done.
But With SQLite only (Means Queries).

So i wanted a guide to make a XP/Level System that's made with Sequelize.

**Comment by Monbrey** [comment]
Theres already a pretty good example on another community guide: https://anidiots.guide/coding-guides/sqlite-based-points-system

This can be combined with the Sequelize guides in this one:
 - https://discordjs.guide/sequelize/
 - https://discordjs.guide/sequelize/currency.html

**Comment by shahoob** [comment]
Ok. right now i'm using JSON file to make XP/Level System.
Maybe next time, I'll move from JSON file to sequelize.
