### ISSUE TITLE
Random Word Generator

### ISSUE THREAD

**Issue by NightDrago9893** [discordjs/guide#307]
I wish there was an area where it explained how to make a random output from your input command. So say I have set my prefix to ! and have it set so when I type "random" it gives me one of x amount of outputs randomly.

so something like this except 'random' gives a random output of the amount the coder specifies.

`
const PREFIX = 'n!';

bot.on('ready', () =>{
 console.log('Online, Night\'s Fishing has no been turned on and commands are now active!');
})

bot.on('message', message=>{

	let args = message.content.substring(PREFIX.length).split(" ");

	switch(args[0]){
		case 'random
			message.reply('test number 1 completed')
			break;
`

Sorry I am so vague with this, I am completely new to coding and such. Sorry if this already exists somewhere, tell me where please if it does.

**Comment by RDambrosio016** [comment]
I personally believe this is not in the scope of the discord.js guide, this is a js subject, and it can be solved by having an understanding of js and simply looking it up.

**Comment by NightDrago9893** [comment]
> I personally believe this is not in the scope of the discord.js guide, this is a js subject, and it can be solved by having an understanding of js and simply looking it up.

ok

**Comment by Monbrey** [comment]
Generating a random array index is basic JavaScript, is incredibly easy to Google (not that anyone bothers) and doesn't belong in a Discord.js guide.

<https://stackoverflow.com/questions/4550505/getting-a-random-value-from-a-javascript-array>
