### ISSUE TITLE
Required arguments

### ISSUE THREAD

**Issue by shausi** [discordjs/guide#313]
im lost at this part of the guide. could use some help plz.

**Comment by RDambrosio016** [comment]
Please use the discord server (https://discord.gg/bRCvFy9) instead of submitting an issue, issues are for issues with the guide, not if you have are misunderstanding something, also be clear about what part, thanks

**Comment by shausi** [comment]
the title says it but i will move to the discord server

**Comment by almostSouji** [comment]
If you have a **specific** part you experience problems with it would be mighty helpful to specify that exact part in your request and **why** you do have issues with understanding it.
We can not really re-explain the entire guide in scope of an issue.

I will close this, if you do have a more specific request feel free to re-open it.
