### ISSUE TITLE
A reaction role guide would be great :)

### ISSUE THREAD

**Issue by asadhum2005** [discordjs/guide#321]
**Is your feature request related to a problem? Please describe.**
The feature isn't related to an issue; however; it is something which i'm pretty sure _used_ to be here, however it isn't on the guide anymore? A v12-compatible version would be great as we'll all be on the latest and greatest soon.

**Describe the solution you'd like**

A guide to reaction roles 
> React to a message and get a role

**Describe alternatives you've considered**
*Can't really think of many alternatives for reaction roles*...
add roles on command usage (fairly basic)

**Additional notes**

**Comment by RDambrosio016** [comment]
This is just a specific implementation of the reaction/message partials guide for v12. There are a lot of ways to use partials, and i believe adding something like that would border on feature creep

**Comment by almostSouji** [comment]
As discord staff has stated multiple times reactions are not to be used as buttons; we don't plan on promoting it.

The guide explains how to use [partials ](https://discordjs.guide/popular-topics/partials.html#enabling-partials) for [reactions ](https://discordjs.guide/popular-topics/reactions.html#listening-for-reactions-on-old-messages) and how reactions work in general.

Applying that knowledge to the specific use case is left as exercise for the reader.

**The general approach is the following:**

1. Identify the `reaction.emoji` to be what you want via its name or id
1. fetch the GuildMember from the `reaction.message.guild` via Guild#[fetchMember](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchMember)/Guild#members#[fetch ](https://discord.js.org/#/docs/main/master/class/GuildMember?scrollTo=fetch)or the partial [fetch ](https://discord.js.org/#/docs/main/master/class/Message?scrollTo=fetch)
1. apply a role to them via GuildMember#[addRole ](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=addRole)/GuildMember#roles#[add ](https://discord.js.org/#/docs/main/master/class/GuildMemberRoleStore?scrollTo=add)
