### ISSUE TITLE
Force to end createReactionCollector using the stop method

### ISSUE THREAD

**Issue by galoncyryll** [discordjs/guide#329]
**Part of the guide or code sample the question is about**

```
// Create a reaction collector
const filter = (reaction, user) => reaction.emoji.name === '👌' && user.id === 'someID'
const collector = message.createReactionCollector(filter, { time: 15000 });
collector.on('collect', r => console.log(`Collected ${r.emoji.name}`));
collector.on('end', collected => console.log(`Collected ${collected.size} items`));
```

**Question**

Is there a way I can manually end a createReactionCollector? Because I have a voting system that members can vote through thumbsup and thumbsdown, And, the collector only ends within the time specified in the options.

Here is an example:
```
message.channel.send(emoteEmbed)
  .then((m) => {
    m.react('👍').then(() => {
      m.react('👎');
    });
    const filter = (reaction, user) => ['👍', '👎'].includes(reaction.emoji.name) && user.id !== 
    message.author.id;

    const collector = m.createReactionCollector(filter, { time: 1800000 });
    collector.on('end', (collected) => {
      //some logic about voting here
    });
});
```

Let's say i want to manually end this "voting for emote". How can I end this reaction collector using the stop method?

**Comment by almostSouji** [comment]
Yes, totally possible! <https://discord.js.org/#/docs/main/stable/class/ReactionCollector?scrollTo=stop>

For future reference: if you have questions about discord.js usage head over to the support server: https://discord.gg/bRCvFy9
