### ISSUE TITLE
For someone named 1261

### ISSUE THREAD

**Issue by GithubUser123456789-dot** [discordjs/guide#353]
**Is your feature request related to a problem? Please describe.**
Not specified.

**Describe the solution you'd like**
Adding a chatbot guide to Discord.js Guides.

**Comment by anandre** [comment]
Besides being wildly uninformative about what you'd actually like, something like this is outside the scope of the guide.  It exists to give a beginner information about the library and how to build the basics of a bot, not provide code and tutorials for specific bot designs.

**Comment by GithubUser123456789-dot** [comment]
Oh, sorry. Closing the issue.
