### ISSUE TITLE
when am giving command. multiple replies coming including previous msgs 

### ISSUE THREAD

**Issue by Shivamtyaagi** [discordjs/guide#355]
`const Discord = require('discord.js');
const client = new Discord.Client();

client.once('ready', () => {
	console.log('Ready!');
});
client.on('message', message => {
	if (message.content === 'hello')                                                                                                           
	// send back "Pong." to the channel the message was sent in
		message.channel.send('how are you');
		
});'

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
