### ISSUE TITLE
Reloading Commands with Alias

### ISSUE THREAD

**Issue by 000Lonewolf** [discordjs/guide#358]
# The Problem
Following this [Guide page](https://discordjs.guide/command-handling/adding-features.html#reloading-commands)
When reloading commands, if the command alias is used, there is an error.
# The Fix
The problem can be fixed simply by replacing `commandName` on line 14 and 17 with `command.name`.

Line numbers according to this page: [GitHub Page](https://github.com/discordjs/guide/blob/master/code-samples/command-handling/adding-features/12/commands/reload.js)

**Comment by tipakA** [comment]
Thanks for reporting! Looks like i missed that when i was writing that part of the guide, but should be fixed when #359 will get merged.
