### ISSUE TITLE
How do I view web pages in JSON?

### ISSUE THREAD

**Issue by AlexRockHead** [discordjs/guide#364]
I just started learning JavaScript, and as far as now, I have only stumbled across one problem. I read your guide on REST API, but that already assumes I know how to view files in JSON. Well, I don't and I would very much appreciate if you would add that to your guide.

**Comment by RDambrosio016** [comment]
The guide assumes you have a solid understanding of javascript, JSON format is part of it (JavaScript Object Notation).

**Comment by almostSouji** [comment]
If you use a rest API you should familiarize yourself with the documentation of the service or through other means than a bot.
- In the case of <https://aws.random.cat/> you can find the hint in the side panel, clicking the link <https://aws.random.cat/meow> (which we use to make the request in the guide) will show the json format nicely formatted for any modern browser.
- For the urban dictionary API (while it is not public) there is a well known unofficial API which you can find out through a bit of googling, resulting in `http://api.urbandictionary.com/v0/define?term=` which is appended by the query-string for the query you want to search for.
- For the query string we use `const querystring = require('querystring');` , the native [Node API](https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options)

Tools you can use (apart from using a modern web browser) are for example [Postman](https://www.postman.com/) or [Insomnia](https://insomnia.rest/)

You can then structure the requests your bot is supposed to do based on this exploration (or preferably official documentation to exclude edge cases) as it will receive the same information.

As mentioned in the article `response.json()` returns a promise resolving with the parsed json output (like you see in your browser or rest client) . Of course you can also console.log this result.
