### ISSUE TITLE
Invalid/incomplete description in the guide in Getting your bot up an Running

### ISSUE THREAD

**Issue by flowed8** [discordjs/guide#365]
This occurs in https://discordjs.guide/creating-your-bot/#logging-in-to-discord

If you follow the steps in "Creating Your Bot", it throws a TOKEN_INVALID (1) error instead of the mentioned "Ready!" (2) message. If I use the correct token of my bot in line 8 instead of the default "your-token-goes-here", the code works as explained. Therefore, the guide should be changed to mention that you have to use a valid token for the code to work as intended.

(1) Full Error Message:
PS D:\#ProgrammierProjekte\Discord\Schnopsn by Flowed\Schnopsn by Flowed v1> node test1.js
(node:13360) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (D:\#ProgrammierProjekte\Discord\Schnopsn by Flowed\Schnopsn by Flowed v1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:135:26)
    at Client.login (D:\#ProgrammierProjekte\Discord\Schnopsn by Flowed\Schnopsn by Flowed v1\node_modules\discord.js\src\client\Client.js:221:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(2) If I use a correct token instead of the default one in the brackets, this is the successful result:
PS D:\#ProgrammierProjekte\Discord\Schnopsn by Flowed\Schnopsn by Flowed v1> node test1.js
Ready!

Device/OS: Windows 10 Pro
version 1903
 - Browser: [e.g. chrome, safari]

**Comment by SketchyLxve** [comment]
Examples are examples, we don't provide you the actual token of your client, you're suppose to do that. You're *suppose to* provide your own token from the developer portal after creating a new application. The guide is not misleading.

**Comment by Monbrey** [comment]
> Therefore, the guide should be changed to mention that you have to use a valid token for the code to work as intended

So what, in your mind, does `your-token-goes-here` mean? To me, if means that's you have to use a valid token for the code to work as intended.

I'm terribly sorry that you had to actually do something instead of copy and pasting every code snippet, but programming is just like that sometimes.
