### ISSUE TITLE
client.users.has is not a function

### ISSUE THREAD

**Issue by ToDevlalala** [discordjs/guide#368]
I have this error. Please help!

**Comment by almostSouji** [comment]
Please make sure you use the right version of the guide for the version of discord.js you have installed (run `npm list discord.js` in your console if unsure). Also refer to <https://discordjs.guide/additional-info/changes-in-v12.html#managers-cache> for an updating guide.

For future questions about library usage please join the discord.js discord server:
  https://discord.gg/bRCvFy9
