### ISSUE TITLE
Make The Help Command Guide In The Command Handler Section Use Embeds

### ISSUE THREAD

**Issue by diligamer** [discordjs/guide#371]
Since Embeds Are Mostly Used To Send Lots Of Data, The Help Command Should Use Embeds. This Would Also Avoid The 2000 Character Limit.

**Comment by Darqam** [comment]
You are free to modify the code as you want it; the guide is not intended to provide a custom pre-built bot. Adding embeds to a command should very well be in the scope of things you can do yourself by following and reading the embeds guide pages (https://discordjs.guide/popular-topics/embeds.html#embed-preview). 

The goal of https://discordjs.guide/command-handling/adding-features.html#a-dynamic-help-command is more so to demonstrate how one can use properties in each file to describe the system/commands. Customization of the return is entirely up to the users.

Additionally, adding embeds at this steps brings a "new" feature into the equation new users may not know about yet, or how to properly use it. There's no need to complicate something further than necessary.
