### ISSUE TITLE
Discord.js concepts - Cient Login and Ready event

### ISSUE THREAD

**Issue by chtnunes** [discordjs/guide#374]
What the client.login('token') does exactly? When should I use it? Where in the code? I have the same doubt about the client.on('ready', () => {} event

**Comment by Naim2000** [comment]
`client.login('token')`: Logs in the bot, just like how you log in a user.
`client.on('ready', () => {})`: Fired when the bot is ready. **This doesn't specifically mean when logged in.**

**Comment by Sardonyx78** [comment]
It starts the ws connection with discord api and the bot. and when discord fires "READY" event via ws ready event occurs

**Comment by chtnunes** [comment]
> `client.login('token')`: Logs in the bot, just like how you log in a user.
> `client.on('ready', () => {})`: Fired when the bot is ready. **This doesn't specifically mean when logged in.**

Shall I log in before or after the ready event is completed? Or it doesn't matter?

**Comment by Monbrey** [comment]
The complete process of logging in your bot is what causes the ready event to fire.

If you have further questions, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue**

**Comment by chtnunes** [comment]
> The complete process of logging in your bot is what causes the ready event to fire in the majority of situations. It will almost always mean that it is in fact "logged in".
> 
> If you have further questions, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue

Will do. Appreciate the help.
