### ISSUE TITLE
.env config example(s)

### ISSUE THREAD

**Issue by asadhum2005** [discordjs/guide#376]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
An example of .env files usage and config. ie the use of `dotenv`. Maybe an owner-only command which uses IDs stored in a `.env` separated by commas to limit the command.
**Describe alternatives you've considered**
JSON Files `which can corrupt`
**Additional notes**

**Comment by almostSouji** [comment]
duplicate of #100 

---
 
sidenote: JSON Files are absolutely fine to store credentials, as long as they're not committed.
The corruption only becomes an issue with simultaneous read and write access from multiple sources
