### ISSUE TITLE
Add Keyv Provider tutorial to Commando guide

### ISSUE THREAD

**Issue by Shqrp** [discordjs/guide#399]
**Is your feature request related to a problem? Please describe.**
I recently discovered the beauty of Commando, so I would like to know more. I chose MongoDB as the database for my bot, and I'd love to switch to Commando.

**Describe the solution you'd like**
The best would be a tutorial on how to set up MongoDB with Commando, but as I know some developers of Discord.JS don't like Mongo, I'd love a tutorial about how to use Keyv, as you showed it also in the main Discord.JS guide.

**Describe alternatives you've considered**
I thought about downloading an already made MongoDB (probably not as the implementations that I found look like they're unmaintained) or Keyv (there is one that is still maintained) provider implementation or make my own, but I'm still not really into Node.JS (I have previous coding experience so I'm trying to learn by doing) so I'd prefer an official guide.

**Additional notes**
If I ever make one (probably not) I would try to put in Commando with a pull request.

**Comment by almostSouji** [comment]
@dragonfire535 maintains the commando part of the guide
would this be wanted/feasible to do in scope of the commando guide?

**Comment by Shqrp** [comment]
> @dragonfire535 maintains the commando part of the guide
> would this be wanted/feasible to do in scope of the commando guide?

Yes, of course. (Sorry for late response)
