### ISSUE TITLE
Role guide 

### ISSUE THREAD

**Issue by SkySourced** [discordjs/guide#402]
**Describe the solution you'd like**
A guide to creating roles, adding them, and modifying them.
There isn't much info on the site about how to create roles in the guide or any specifics in the docs.

**Comment by conqr2** [comment]
Check the common-questions page

**Comment by almostSouji** [comment]
Revisiting this idea I'm really not too sure what a role section should cover.

The only thing past permissions (which are extensively covered already) to do with roles are modifying existing roles and modifying GuildMembers to change their roles. Both of which are quite fundamentally understood by reading their respective documentation and retrieved from the respective managers at Guild#members, Guild#roles:

- https://discord.js.org/#/docs/main/stable/class/Role
- https://discord.js.org/#/docs/main/stable/class/GuildMember
- https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=members
- https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=roles
