### ISSUE TITLE
Cache guide

### ISSUE THREAD

**Issue by karizma** [discordjs/guide#403]
**Is your feature request related to a problem? Please describe.**
I am unsure whether a fetch is needed when trying to obtain users/roles/channels/guilds. 

**Describe the solution you'd like**
Guide on how discord.js caches, like when they do update the cache or when they don't. For example, on guildMemberAdd, would this update `<guild>.members.cache` ?

**Describe alternatives you've considered**
Always fetching for certainty, since if it's cached it would just retrieve the cache. But this is async 
and error handling gets ugly when trying to call multiple fetchs one after another.

**Additional notes**
This is one example: 
Where `args[1]` can be a dynamic argument to fetch for a user

```javascript
let user = msg.mentions.first();
if (!user) { 
    try {
        user = await msg.guild.members.fetch(args[1]);
    } catch (e) { 
        try {
            user = await msg.guild.members.fetch({ query: args[1] });
        } catch (e2) { 

        }
    }
}

if (!user) return;

//code only after user found
```

**Comment by Clemens-E** [comment]
In my Opinion, you should always use fetch, because it falls back to the cache anyway (when available)
and the error handling does not get ugly, as long as you don't chain those try catches.
I would do it like this:
```js
let user = msg.mentions.first();
if (!user) {
    user = await msg.guild.members.fetch(args[1])
        .catch(() => msg.guild.members.fetch({
            query: args[1]
        }))
        .catch(() => msg.guild.members.OtherWaysToFindTheMember())
        .catch(() => undefined);
}

if (!user) return;
```
But for stuff like roles/channels/guilds/emojis you could write a guide that those (under normal circumstances) are all cached, while users/members/messages probably aren't

**Comment by didinele** [comment]
> because it falls back to the cache anyway (when available)

This is incorrect, it tries to get from cache first and actually falls-back to the API if the member is not cached.

**Comment by Clemens-E** [comment]
Yeah, sorry, that's what I was trying to say.

**Comment by didinele** [comment]
Generally speaking if a fetch by ID fails it probably means API failure, in which case you should just stop. Other forms of resolving a member, should IMO only be used for user-input convinience (i.e try to get by similar username to user input).

To rephrase, if I had an id, I would just `.fetch(...).catch(() => null)`

**Comment by almostSouji** [comment]
If you want only strictly cached data you access the cache
If you want data you fetch, as said correctly it does hit the API if nothing is cached
Manager#fetch, that is.

Structure#fetch completes the partial.

What would a guide page for this cover? I'm not too sure i see the use case in this request so far
