### ISSUE TITLE
Umm

### ISSUE THREAD

**Issue by manfredix64** [discordjs/guide#404]
I have a question. So i have made like a server info command and it works but i only have it to say the server name and merber count but is there a way to get the bot to also say whats the server owner because that would be great?

**Comment by Monbrey** [comment]
**The issue tracker is only for suggestions or reporting issues with the guide. If you have a discord.js question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
