### ISSUE TITLE
Discord.MessageEmbed() addfield not working

### ISSUE THREAD

**Issue by RobbieVerdurme** [discordjs/guide#406]
**Describe the bug**

When i wanted to add an settings command i used the Discord.MessageEmbed() class to do this. I mainly used it for the styling. But if i wanted to add some fields it just gives undefined. Even after copy pasting the example of https://discordjs.guide/popular-topics/embeds.html#embed-preview.

**To Reproduce**

this is the code i used to run the messengeEmbed()
```
const Discord = require('discord.js');

module.exports = {
    name: 'settings',
    description: 'settings page',
    execute(message, args, giphy, commands) {
        // configure default messageSettings
        const embedMessageSettings = new Discord.MessageEmbed()
            .setTitle('Settings')
            .setDescription('Here are all the different commands you can use')
            .setFooter('Thanks for using portal-bot')

        // add commands
        commands.forEach((f) => {
            let props = require(`./${f.name}.js`)

            embedMessageSettings.addField(
                `**${props.name}**`,
                `${props.description} \n ${props.usage}`
            )
        });

        // send message to author
        message.author.send(embedMessageSettings)
    },
};
```

**Screenshots**

This image is the output from the code above
![image](https://user-images.githubusercontent.com/25928398/82822760-99c7f680-9ea6-11ea-9b8b-b8adb073ac57.png)

Can you help me find the problem?

**Comment by FirezzzZ** [comment]
props is not defined correctly

**Comment by RobbieVerdurme** [comment]
@FirezzzZ how would you define props if it isn't correctly defined ?

its not specific to my example it also doesn't work if you copy and past the code from the example site: https://discordjs.guide/popular-topics/embeds.html#embed-preview
```
// at the top of your file
const Discord = require('discord.js');

// inside a command, event listener, etc.
const exampleEmbed = new Discord.MessageEmbed()
	.setColor('#0099ff')
	.setTitle('Some title')
	.setURL('https://discord.js.org/')
	.setAuthor('Some name', 'https://i.imgur.com/wSTFkRM.png', 'https://discord.js.org')
	.setDescription('Some description here')
	.setThumbnail('https://i.imgur.com/wSTFkRM.png')
	.addFields(
		{ name: 'Regular field title', value: 'Some value here' },
		{ name: '\u200B', value: '\u200B' },
		{ name: 'Inline field title', value: 'Some value here', inline: true },
		{ name: 'Inline field title', value: 'Some value here', inline: true },
	)
	.addField('Inline field title', 'Some value here', true)
	.setImage('https://i.imgur.com/wSTFkRM.png')
	.setTimestamp()
	.setFooter('Some footer text here', 'https://i.imgur.com/wSTFkRM.png');

channel.send(exampleEmbed);
```

**Comment by almostSouji** [comment]
Please elaborate on "doesn't work"
If i execute this exact sample i can not see any of the symptoms you describe above, which are quite definitely due to whatever "props" is causing an empty embed.

To still be able and send this embed discord.js replaces empty field titles and values with a `'undefined'` string (which - in hindsight - I probably should've removed in development of v12 when i did the field change)

**Comment by RobbieVerdurme** [comment]
**I found the solution**
The solution was to update node.js to the latest version i was still on version 10.16.3
thx for helping

**Comment by TMNS025** [comment]
does anyone know how to remove the "undefined" and just have nothing there?
