### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by pigmaster871** [discordjs/guide#410]
i want to install discord.js but if i do the cmd then it says npm error unexpected of JSON input while parsing near. What do i do or have i done something wrong? Im new to discord.js so can anyone please help me out.

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by pigmaster871** [comment]
thank you
