### ISSUE TITLE
Sell Items and use items

### ISSUE THREAD

**Issue by KartikeSingh** [discordjs/guide#418]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by almostSouji** [comment]
The purpose of our guide is to introduce a bsic idea about concepts to the reader. We explain a basic currency system here: <https://discordjs.guide/sequelize/currency.html> including a shop example where you can [buy](https://discordjs.guide/sequelize/currency.html#zeta-buying-an-item) an item.
Further expanding on this idea (using and selling items) is left as exercise to the reader. In essence those use cases too will require you to read and write data, as is demonstrated in the guide.
