### ISSUE TITLE
A guide to scheduled tasks

### ISSUE THREAD

**Issue by Encarton** [discordjs/guide#420]
I'd be interested in seeing a guide on how to create a scheduled events.
Some examples of this would be things like:
- Creating a reminder command where you schedule a reminder in X amount of time or at a specified time 
(~remind #channel Cool thing happens 12h)
- A command that creates a repeating message, perhaps add in some random timing
(~announcement repeat 6h message contents for announcement type thing)
- Having the bot create a post once a day in a channel at a specific time
(~dailymessage #channel fancy embed message
- Have the bot scheduled to edit and update a post once every X amount of time
(~updatepost messageid new version of embed message
- Schedule a command to execute repeatedly at a specific time
(~schedule 24h ~prune #channel)

It would be some useful learning in terms of creating long running background tasks that have to persist through reboots, and tracking the ID of a past message to update it.

**Comment by conqr2** [comment]
Someone should add the package **node-cron** to useful packages

**Comment by almostSouji** [comment]
The goal of this guide is to explain in greater verbosity than possible on the library's documentation how to use it to write a functioning bot with some useful features. Having a section for absolutely any possible command out there is not part of this goal.

Adding a scheduler to useful-packages is the extent to which this will be covered.
