### ISSUE TITLE
sequelize.import doesn't work anymore

### ISSUE THREAD

**Issue by shane9b3** [discordjs/guide#426]
Could you please update the code as sequalize.import is out dated and doesn't work anymore.

**Comment by RichterCa** [comment]
After tons of searching, here is what I came up with that seemed to work:

**Comment by almostSouji** [comment]
> But it would be nice of them to update the Guide to something that actually works...

This is a community project, "them" can be absolutely everyone, feel free to open a pull request and take a look at our [contributing guidelines](https://github.com/discordjs/guide/blob/master/CONTRIBUTING.md)
