### ISSUE TITLE
Alternate emoji for example

### ISSUE THREAD

**Issue by illuminatedspace** [discordjs/guide#427]
**Is your feature request related to a problem? Please describe.**

Hi. I noticed you're using this emoji in the documentation for Reaction Collectors: 👌
I was wondering if you were aware that the Anti Defamation League classifies it as a hate symbol. https://www.npr.org/2019/09/26/764728163/the-ok-hand-gesture-is-now-listed-as-a-symbol-of-hate

**Describe the solution you'd like**

Could you use a different emoji as an example? 

**Describe alternatives you've considered**

✅ 

**Additional notes**

**Comment by illuminatedspace** [comment]
I'd be happy to make the PR if the maintainers are supportive of the idea.

**Comment by Monbrey** [comment]
No harm in changing it imo, I'd say go ahead and make the PR and it can be merged if accepted.

We use 👍 in the Reactions -> Awaiting Reactions section, not that it needs to be that consistent.

**Comment by rubybb** [comment]
this is dumb. is "okay" a symbol of hate?
👌👌👌👌👌👌👌👌👌👌👌👌👌

**Comment by Danktuary** [comment]
Sure, feel free to make a PR. I'd say change to 👍

**Comment by illuminatedspace** [comment]
Thank you! Will do.

**Comment by qwright10** [comment]
@illuminatedspace I already created a PR

**Comment by illuminatedspace** [comment]
@qwright10 Thanks.

**Comment by illuminatedspace** [comment]
I'll close mine I guess.

**Comment by Monbrey** [comment]
Sanc suggested that we use the thumbs-up, not the checkmark. So yours is probably the better PR

**Comment by PhoenixShay** [comment]
https://www.adl.org/education/references/hate-symbols/okay-hand-gesture
“Because of the traditional meaning of the “okay” hand gesture, as well as other usages unrelated to white supremacy, particular care must be taken not to jump to conclusions about the intent behind someone who has used the gesture.”

Can we rename the “master” branch next?

**Comment by almostSouji** [comment]
Thank you for the resource, we aware that this definitely falls under "unrelated".

We will follow the branch naming of the main discord.js repository `discordjs/discord.js`, which is being discussed for some time now but has to consider some more back end, tool configuration and dependency chains.
