### ISSUE TITLE
Oauth2, Doesnt "greet the user"

### ISSUE THREAD

**Issue by ItsMax123** [discordjs/guide#434]
**Describe the bug**

With the oauth2 guide: When I run the app, it doesnt edit the hoi! line to add the users name. Nothing happens but I can see all the right info in console.

**To Reproduce**
1. Use the files in this github
2. Add your oauth url
3. Add the token, secret, redirect url, scopes.
4. Run
5. When you get redirected to the main screen it is the exact same as the beginning exept for the url has a code and the console has the user info.

**Comment by conqr2** [comment]
@ItsMax123 try using express for the actual oauth flow.

**Comment by almostSouji** [comment]
Please try to follow the improved version introduced after #415. If you can still reproduce this please provide your code and some depiction of the unexpected behavior. I can not see any unexpected behavior.

**Comment by almostSouji** [comment]
Probably solved in #415, should it still persist feel free to re-open
