### ISSUE TITLE
Add a reboot segment to the guide

### ISSUE THREAD

**Issue by ShadowGamer3** [discordjs/guide#439]
Please add a segment on ways to reboot the bot, and have all changes take effect.  As it stands right now, there is no such segment.  The closest I can find is the reload command, but that can't reload the index.js file, nor does it load new commands.  A reboot segment would be very helpful, as it is a great way to update the whole bot with just one command.

**Comment by almostSouji** [comment]
A reboot is achieved by exiting the process and configuring a process manager to keep the process alive/restarting. As such this would be an addition to the [PM2 section](https://discordjs.guide/improving-dev-environment/pm2.html)

**Comment by almostSouji** [comment]
I completely missed that this [already exists](https://discordjs.guide/popular-topics/common-questions.html#how-do-i-create-a-restart-command).
