### ISSUE TITLE
Sell Command for Sequelize Currency system

### ISSUE THREAD

**Issue by NameLord** [discordjs/guide#444]
Title says everything..

**Comment by monbrey** [comment]
The guide is not supposed to provide complete implementations of things you can simply import into your own bot.

Given that it already includes a buy command which *adds* items and *subtracts* cash, it really shouldn't be very hard to make a command which does the opposite on your own.

**Comment by NameLord** [comment]
> The guide is not supposed to provide complete implementations of things you can simply import into your own bot.
> 
> Given that it already includes a buy command which _adds_ items and _subtracts_ cash, it really shouldn't be very hard to make a command which does the opposite on your own.

Are you sure about this? if yes i made by myself  but it is saying
TypeError: Cannot Read property of removeItem of null.
Code: https://hasteb.in/upenugup.js
dbObject Code: https://hasteb.in/gurefuzi.js

**Comment by almostSouji** [comment]
will be left as exercise to the reader
