### ISSUE TITLE
https://discordjs.guide/popular-topics/miscellaneous-examples.html#emoji-characters

### ISSUE THREAD

**Issue by BrandgrandRealMe** [discordjs/guide#448]
**Describe the bug**
`const emojiCharacters = require('./emojiCharacters');`
Should Be `const emojiCharacters = require('./emojiCharacters.js');`
**To Reproduce**

1. Go to 'https://discordjs.guide/popular-topics/miscellaneous-examples.html#emoji-characters'
3. Scroll down to 'const emojiCharacters = require('./emojiCharacters');'

**Screenshots**
[SCREENSHOT](https://prnt.sc/tvdo1w)

**Comment by tipakA** [comment]
It should not, as the file is not JSON.

**Comment by BrandgrandRealMe** [comment]
?

**Comment by tipakA** [comment]
!

**Comment by BrandgrandRealMe** [comment]
Oh

**Comment by BrandgrandRealMe** [comment]
@tipakA 
Now Look At it

**Comment by NotSugden** [comment]
there is no problem here, `require('file')` works just the same as doing `require('file.js')`

**Comment by BrandgrandRealMe** [comment]
WAT

**Comment by tipakA** [comment]
You can require JavaScript files wothout need to add the `.js` on end, assuming you pass correct path.
![image](https://user-images.githubusercontent.com/31581159/89591862-914b4f00-d84b-11ea-898d-e4da5b631e04.png)

**Comment by BrandgrandRealMe** [comment]
Oh. Did Not Know That!

**Comment by tipakA** [comment]
Also, for future, please do not scream and post random useless messages. This is not the place for that.

**Comment by BrandgrandRealMe** [comment]
Ok
