### ISSUE TITLE
Is this a typo in the guide?

### ISSUE THREAD

**Issue by JavascriptLearner815** [discordjs/guide#450]
**Part of the guide or code sample the question is about**
https://discordjs.guide/creating-your-bot/commands-with-user-input.html#caveats-2

**Question**
Why does the new version of the prune command say if (amount <= 1 || amount > 100) when it should be if (amount <= 1 || amount >= 100) according to definition?

**Comment by almostSouji** [comment]
amount is defined as the parsed argument + 1
if you supply 99 "amount" will be 100 => ok
if you supply 100 "amount" will be 101 => not ok
`> 100` covers this case, `>= 100` would forbid the argument `99`, which is okay to use.

**Comment by JavascriptLearner815** [comment]
#458 is an issue like this one, but the check is irrelevant to the reply 'you need to enter a number between 1 and 99.' as it forbids 1, go look at it.

**Comment by almostSouji** [comment]
An in-depth explanation of the caveat and how we deal with it, why we do it, as well as a gif showing the expected behavior after following the guide fully and correctly can be found in https://github.com/discordjs/guide/issues/458#issuecomment-681130889 .
