### ISSUE TITLE
You have written the code for commands both in index.js and also in the separate command file. Is that how its supposed to be?

### ISSUE THREAD

**Issue by Rayne231** [discordjs/guide#456]
**Part of the guide or code sample the question is about**

**Question**

**Comment by monbrey** [comment]
They are different sections of the guide.

It starts out with code in index.js, then transitions forward to a modular command handling approach step by step.

**Comment by Rayne231** [comment]
so the code is supposed to be in both places?

**Comment by monbrey** [comment]
No, you're supposed to read through the guide step-by-step as it introduces new concepts and builds upon itself, not copy and paste every file/snippet into your own bot.

The command handling chapters detail changing your index.js as appropriate.

**Comment by Rayne231** [comment]
Yes, I know. I am following the guide only. So the answer is no right?

**Comment by Rayne231** [comment]
@monbrey my index.js looks like this. 
`const fs = require('fs');
const Discord = require('discord.js');
const { prefix, token } = require('./config.json');

const client = new Discord.Client();
client.commands = new Discord.Collection();

const commandFiles = fs.readdirSync('./commands').filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	client.commands.set(command.name, command);
}

client.once('ready', () => {
    console.log("Connected to Da Baddest " + client.user.tag);
    
    client.user.setActivity(";help 😀", {type: "WATCHING"});
});

client.on('message', message => {
	if (!message.content.startsWith(prefix) || message.author.bot) return;

	const args = message.content.slice(prefix.length).trim().split(/ +/);
	const command = args.shift().toLowerCase();

});

client.login(token);`

**Comment by Rayne231** [comment]
the ping.js file is the same as in this repositroy. but the bot is not responding. so i am trying to find the issue

**Comment by tipakA** [comment]
It would be way easier if you would explain it in more detail in the [Discord server](https://discord.gg/bRCvFy9)

**Comment by Rayne231** [comment]
ok i am heading over to the server

**Comment by almostSouji** [comment]
resolved on discord
