### ISSUE TITLE
Block command

### ISSUE THREAD

**Issue by DemonWolfFang** [discordjs/guide#460]
I'd love to see a command(s) to block a user from a discord bot. Or block from a specified server.

**Comment by codedipper** [comment]
You can block a user by using:
`if (<message>.author.id == "ID") return;`
Or by guild:
`if (<message>.guild.id == "ID") return;`

Yes, the `<message>` represents the message parameter.

**Comment by tipakA** [comment]
That is not helpful at all, as it would mean that you have to hardcode the id, and have only one id in one if. Any changes would also require restart of the bot.

**Comment by suhd00d** [comment]
That definitely does point you in the right direction, if you know basic JavaScript you would know how to make an array of IDs to match it with the message.author.id if it’s on the blacklist. A simple google search will tell you how to blacklist users -__-
