### ISSUE TITLE
Random Messages

### ISSUE THREAD

**Issue by TheBunnyMan123** [discordjs/guide#462]
There should be a section that is basically how to send random messages, For example an 8ball command

**Comment by anandre** [comment]
Such a concept is achieved used basic concepts in JS, namely accessing [array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) elements and using [Math.random()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) to get a random element, resulting in [this sort of code](https://stackoverflow.com/questions/4550505/getting-a-random-value-from-a-javascript-array).  The library and guide both assume you have a solid understanding of JS, so being able to apply basic concepts like this should be doable on your own.  The guide cannot cover every possible command idea out there.
