### ISSUE TITLE
Const path shows wrong in console ;(

### ISSUE THREAD

**Issue by sayantan300** [discordjs/guide#465]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**

**Additional notes**

I tried this on npm and it WORKED!!!
```js
var path = require('path');
console.log(path);
```

This worked, so you all team can change **const** to **var** to make it work !

Contact me: Progamer 😎#3286 (id: 602902050677981224)

I'm banned on discordjs server :/

**Comment by sayantan300** [comment]
I found that **var** dosen't works too on heroku

**Comment by sayantan300** [comment]
Does anyone knows why that error is going on in my heroku console?

**Comment by sayantan300** [comment]
@almostSouji why did u close it? What happened with `const path` ?

**Comment by almostSouji** [comment]
This is not an issue with the guide
