### ISSUE TITLE
OAuth2 guide not showing authorized user username#discrim

### ISSUE THREAD

**Issue by hanahaneull** [discordjs/guide#466]
**Describe the bug**

Website didn't show user username#discrim

**To Reproduce**

1. Follow OAuth2 guide
2. Run the project
3. Authorize the app
4. Result will be ``Hoi!`` instead ``Hoi! username#discrim``

**Screenshots**

**Device (please complete the following information):**

- Device/OS: Manjaro Linux
- Browser: Google Chrome
- Version: 84.0.4147.125 (Official Build) (64-bit)

**Additional notes**

It seems the script cant find ``access_code``, thats why it cant get user info

**Comment by monbrey** [comment]
Please provide a reproducible code sample (your own, not the guide) which demonstrates the issue.

If it "can't find access_code" please also show the error and stack trace indicating this.

**Comment by hanahaneull** [comment]
Sorry if I didn't make it clear.

I am using discord.js guide code as my source code. you can view them in [here](https://github.com/discordjs/guide/tree/master/code-samples/oauth/simple-oauth-webserver)


After authorizing the app, you will be redirect back to the website, with ``code`` and ``state`` parameter added.
![image](https://child-porn.nothing-to-see-he.re/5ac4H2.png)

By looking the index.html source, the script trying to find ``access_code`` parameter to be able fetch user info. Meanwhile in the url parameter we get before, there is no ``access_code`` parameter.

**Comment by monbrey** [comment]
`access_code` does not appear in either index.html or index.js that you linked to here.

It does make reference to an `access_token` which is obtained by posting the `code` URL parameter provided in your screenshot above, along with the `client_id` and `client_secret`, to the `https://discordapp.com/api/oauth2/token` endpoint. The guide explains this process quite well [here](https://discordjs.guide/oauth2/#oauth2-flows)

**Comment by hanahaneull** [comment]
Sorry for my mistake.

I mean ``access_token`` instead of ``access_code``. Sure, I able to generate those in the nodejs console. But I am not able to fetch user info in website, because  I didn't have ``access_token`` to make request to Discord API. Do I need some redirect thing so the website able to get ``access_token`` by appending ``access_token`` parameter in the url?

**Comment by monbrey** [comment]
The access token is returned from the request made to the `https://discordapp.com/api/oauth2/token` endpoint.

**The issue tracker is only for bug reports and enhancement suggestions. For further support with this, please ask in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue.**

**Comment by SpaceEEC** [comment]
You seem to have missed an important detail from the heading [Putting it together](https://discordjs.guide/oauth2/#putting-it-together):
> If you want to do this, make sure the `response_type` in the url is `token`.

See for more info about that response type in RFC 6749 (also linked from the guide page):
- [Section 3.1.1](https://tools.ietf.org/html/rfc6749#section-3.1.1)
- [Section 4.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.1)
- [Section 4.2.2](https://tools.ietf.org/html/rfc6749#section-4.2.2)

**Comment by KurokuTetsuya** [comment]
I think the guide should use express instead of HTTP native library
cause the native library is very complicated for newbie/example, and express is easier than native library/
Just suggestion, don't mind me.
Server-side: https://bin.frutbits.xyz/tahezekozi.js
HTML: https://bin.frutbits.xyz/nezejaqura.xml

**Comment by almostSouji** [comment]
> I think the guide should use express instead of HTTP native library
> cause the native library is very complicated for newbie/example, and express is easier than native library.
> Just suggestion, don't mind me.
> Server-side: https://bin.frutbits.xyz/tahezekozi.js
> HTML: https://bin.frutbits.xyz/wiyixiluja.xml

i moved this into its own issue #472 where you can track the suggestion and its status, as this issue is already closed and resolved and will likely not receive any attention going forward

**Comment by KurokuTetsuya** [comment]
Avoid expired hastebin:
Server-side: https://pastebin.com/RvtZBTZ3
HTML: https://pastebin.com/mZwYQwi3
