### ISSUE TITLE
Addition of javascript.info to Introduction documentation

### ISSUE THREAD

**Issue by virenb** [discordjs/guide#473]
**Part of the guide or code sample the question is about**
https://discordjs.guide/#before-you-begin

**Question**
I was wondering if [https://javascript.info/](https://javascript.info/) could be added into the list of JavaScript resources? I'm not an author or have any relation to the project but I find it to be a very helpful resource for learning JavaScript.

Would be happy to add it and create a pull request if needed.

**Comment by almostSouji** [comment]
Thank you for the suggestion! Applied in https://github.com/discordjs/guide/commit/e5a3d879f4e55a38ac42c02a13920063df4fa466
