### ISSUE TITLE
Track Invite Codes and What Codes Members use to Join

### ISSUE THREAD

**Issue by AtaraxiaCodes** [discordjs/guide#484]
Perhaps make a guide on how to track the invite codes that a certain server has and what codes members use to join the server. This could be useful if you want to make an invite manager bot or if you wanted to award a role to people who use a certain invite (the project that I’m working on!).

**Comment by anandre** [comment]
[An Idiot's Guide](https://anidiots.guide/coding-guides/tracking-used-invites) has a pretty well-written page on this topic, and the pitfalls of such a system.  Discord doesn't provide the data in a clear manner, making it really difficult to effectively implement.

**Comment by almostSouji** [comment]
unless discord at some point provides the data required to do this cleanly and reliably this will not be added.
