### ISSUE TITLE
Provide an additional features -> Custom Prefix Command

### ISSUE THREAD

**Issue by GamerCoder215** [discordjs/guide#492]
I've learned how to make a custom prefix command, and feel like this is a highly-wanted feature and would be appreciated from thousands of users. Using a database (quick.db), you can create a customizable prefix for the bot.

Sample Steps
"To create a prefix, you're going to need to use the module Quick.db".
"Once installed, enter code [...]. This will check [...]."
"After that, put this n: [...]."

**Comment by monbrey** [comment]
I'm not quite sure why you closed this but:
- we don't support or recommend quick.db
- custom prefixing is already covered by the keyv guide
