### ISSUE TITLE
fetchPinned(cache) function is mis-documented

### ISSUE THREAD

**Issue by Mo9a7i** [discordjs/guide#494]
**Describe the bug**
fetchPinned(cache) function is mis-documented

**To Reproduce**
```javascript
message.channel.fetchPinned();
````
**Additional notes**
Correct call is:
```javascript
message.channel.**messages**.fetchPinned();
```

**Comment by almostSouji** [comment]
Which portion of the guide are you referring to? All mentions of that function i can find detail the change from TextChannel#fetchPinnedMessages to MessageManager#fetchPinned - and do so correctly.

**Comment by Mo9a7i** [comment]
Sorry, I thought this is the repo for <https://discord.js.org/#/docs/main/stable/class/MessageManager?scrollTo=fetchPinned>
I will look for that one.
