### ISSUE TITLE
 Guide says that Discord requires sharding at 2500 guilds but it is not mentioned on docs

### ISSUE THREAD

**Issue by kislball** [discordjs/guide#497]
The official gateway documentation(https://discord.com/developers/docs/topics/gateway#sharding) doesn't mention that shard cannot be connected to gateway with 2500+ guilds, nevertheless the guide says that it is cannot(https://discordjs.guide/sharding/#when-to-shard).
I can submit the PR if necessary
P.S. i am resubmitting issue #496

**Comment by monbrey** [comment]
The 2500 limit is mentioned on the Github for the documentation here: https://github.com/discord/discord-api-docs/issues/17#issue-147517364

This has proven to be accurate in practice. I see no reason to remove this from our guide.

**Comment by kislball** [comment]
Ah, ok then. Should I close the issue?
