### ISSUE TITLE
add a page regarding a "fetch" bot

### ISSUE THREAD

**Issue by kaknight23** [discordjs/guide#502]
Recently in my discord my friends and I were wanting a way to "subscribe" to sites and have relevant information posted in a "Game News" channel. My description of this would be as such:

A bot that will check a specific website every ~30 minutes for any new articles (like pcgamer.com for example, or a game's patch notes page etc.) and if anything new has come out, it will post it to this Game News channel in discord. I browsed through the discord.js guide and didn't see anything like this. I'm also not sure if a bot like this exists out there already. 

I've got some programming in my background but not much JavaScript so learning the syntax has been a learning experience. With that said, I've been trying to tackle this problem for my friends and I by myself but haven't gotten far. Currently I just have the generic !ping pong! bot implemented in the discord. I would love to see a guide on how to do what I described above or if there's already a guide out there, a link to that :)! 

Thanks!

**Comment by monbrey** [comment]
Webscraping is not related to Discord.js bot development in any way and is not a topic that should be covered by the guide.

**Comment by almostSouji** [comment]
Thank you for the suggestion, however I don't think this finds a place in our guide:

This feature only very marginally uses the discord.js library in some new way. The goal of this guide is to give an insight into how to use this library to then later build new features based on the newfound understanding. 

The proposed section would mostly consist of interval polling/third party API's (maybe websockets or other event tracking, if available) and the part using discord.js basically just sending a message, which is covered in sufficient depth in what we already have on the guide.
