### ISSUE TITLE
Sistema de configuração do bot por reação

### ISSUE THREAD

**Issue by Antoniozw** [discordjs/guide#517]
<! -- Um sistema de configuração do bot por reação, para poder mudar o prefixo, canais onde mensagens automáticas serão enviadas etc. --!>

**Comment by IDjinn** [comment]
Bom vamos lá, 
1- Aqui é bom sempre falar em inglês...
2- Isso você mesmo pode fazer no seu código, a lib já tem métodos para você mesmo criar tais funções seria desnecessário adicionar isso se você mesmo pode fazer

**Comment by IDjinn** [comment]
É sempre melhor usar inglês nos repositórios do d.js

Isso não é muito útil, é algo muito excepcifico de código para código, além de mudar dependendo da database. Caso a pessoa quiser fazer isso ela tem que ter o mínimo de conhecimento, e usando os métodos da lib já consegue fazer por conta própria (já que é algo básico) não é bom criar isso no Guide, porque então quem não sabe iria apenas copiar e colar, e quando não funcionasse iria reclamar no servidor de suporte.

**Comment by Antoniozw** [comment]
oh ok I understand

Em sáb., 31 de out. de 2020 às 18:43, IDjinn <notifications@github.com>
escreveu:
