### ISSUE TITLE
A little help...

### ISSUE THREAD

**Issue by Devinic123** [discordjs/guide#529]
I know this may seem a little far-fetched, but...

Is there a way to check if a Minecraft Server is online?
And if so, can I see which players are online?

Thanks!

**Comment by almostSouji** [comment]
We do not provide support or write guides for specific games integrations and APIs. You can take a look at https://discordjs.guide/additional-info/rest-api.html#making-http-requests-with-node our rest API topic, which might come in handy, should you find an API to interact with.
