### ISSUE TITLE
Can not get all user IDs on a server.

### ISSUE THREAD

**Issue by mtrucc** [discordjs/guide#531]
**Part of the guide or code sample the question is about**

```
let channels = client.guilds.cache;
console.log('channels', channels);

for (let [key, value] of channels) {
  value.members
    .fetch()
    .then(console.log)
    .catch(console.error);
}
```

**Question**

can not get all user IDs on a server.

but use 

```
let channels = client.guilds.cache;
console.log('channels', channels);

for (let [key, value] of channels) {
  value.members
    .fetch({ user: '123456' })
    .then(console.log)
    .catch(console.error);
}
```

can get the user

I want to get all user IDs on a server.

**Comment by almostSouji** [comment]
The endpoint to fetch all members is restricted and requires granting the privileged GUILD_MEMBERS intent (read more here: https://github.com/discordjs/discord.js/issues/4961). Fetching a specific user is not guarded, hence the second example works (does however not what you stated as goal, it tries to fetch a single member on all guilds instead).

- Sidenote1: `<Guild>.members.fetch("id")` works, no need to construct a semi-member with `{user: "id"}`
- Sidenote2: If you want all the ids of members of a server `<Guild>.members.fetch().then(members => members.keyArray())` will instead return a Promise which resolves with the ids of all members. (Again, requires the guild members intent to be granted, see above)

I would also suggest not calling guilds channels, a guild is a server and channels are text- voice- and categorychannels people use inside a server, discord terminology wise.

If you have more questions pay a visit to our discord server, we do not provide support for discord.js usage through GitHub:
https://discord.gg/bRCvFy9
