### ISSUE TITLE
Page request: rank system

### ISSUE THREAD

**Issue by Random-Branz** [discordjs/guide#540]
Could you show us how to make a rank system as well commands showing rank and adding points

**Comment by almostSouji** [comment]
We explain the base case of a currency system <https://discordjs.guide/sequelize/currency.html> here, how you use that number (if you call it a currency or rank points) is up to you, the principles of persistent storage stay the same. This can easily be extended with other way so gain currency (points) as you deem fit.

Ranks would then be computed through a ranking function based on these points. Which we'll leave as exercise to the reader and other resources (entire whitepapers are written on level up scaling and why various dampening and boosting in early phases can be beneficial to overall user experience).

Overall i don't really see added benefit in more specifically covering this use case of currency/points on the guide.
