### ISSUE TITLE
Help/Ayuda

### ISSUE THREAD

**Issue by mrbaneador333creator** [discordjs/guide#542]
How do I put more than 1 command to my bot?
como hago para poner mas de 1 comando a mi bot?
![image](https://user-images.githubusercontent.com/75536741/101266573-41748a00-3750-11eb-8ef9-b0466b987e9e.png)

**Comment by almostSouji** [comment]
I would recommend to actually read the guide, we explain a simple [command handler](https://discordjs.guide/command-handling/) in later chapters, where adding new commands would work via new files in the respective folder with the required structure, as explained in the article.
