### ISSUE TITLE
currency system 

### ISSUE THREAD

**Issue by lady0001** [discordjs/guide#547]
i’ve tried this before and everything worked fine but now my bot is responding to every command showing my balance

**Comment by tipakA** [comment]
And that is an issue with guide in which way?  
Given that you give absolutely no details, there isn't much to help with.

**Comment by lady0001** [comment]
i’m sorry i didn’t mean there was an issue with the guide i meant i need help fixing this 
i followed the guide and install/updated everything and checked my file and my bot continues to show my balance when i use other commands 
i thought this was only an issue with commands in the app.js file but it’s happening to my other commands

**Comment by vBread** [comment]
This is the wrong place to ask for support and unrelated to the guide. Please join the [discord server](https://discord.gg/bRCvFy9) for help instead.
