### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FraneB666** [discordjs/guide#549]
Hi i copied this code and i have this error 
![image](https://user-images.githubusercontent.com/56093055/102272928-d716d300-3f21-11eb-8e4c-5d6fcd01b85a.png)

**Comment by almostSouji** [comment]
please read section completely and carefully from the beginning. you seem to have missed [creating the models](https://discordjs.guide/sequelize/currency.html#create-models) and/or [initializing the database](https://discordjs.guide/sequelize/currency.html#initialize-database).
