### ISSUE TITLE
Slash Commands (as per the new addition, if possible currently)

### ISSUE THREAD

**Issue by alexhowell2a** [discordjs/guide#550]
**Is your feature request related to a problem? Please describe.**
It is not necessarily a problem, but it is wanted.

**Describe the solution you'd like**
A new category under the **Command Handler** tab with these new commands.

**Describe alternatives you've considered**
Haven't considered any alternatives yet other than the current command capabilities of Discord.JS

**Additional notes**
As per these two links:
Reddit - [We can now make custom slash commands using bots!! discordapp](https://www.reddit.com/r/discordapp/comments/ke1p8b/we_can_now_make_custom_slash_commands_using_bots/)
Discord Developer Portal - [Documentation - Slash Commands](https://discord.com/developers/docs/interactions/slash-commands)

**Comment by tipakA** [comment]
The feature itself isn't even added to library yet, so there is currently nothing to write guide about.

The PR for the feature is at [discord.js#5106](https://github.com/discordjs/discord.js/pull/5106), and there is no ETA on where it's going to be merged and/or released.
