### ISSUE TITLE
canvas.applyText() is undefined

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/guide#552]
**Describe the bug**
canvas.applyText() is undefined

**To Reproduce**
Copy and paste the code from [https://discordjs.guide/popular-topics/canvas.html#adding-in-text](https://discordjs.guide/popular-topics/canvas.html#adding-in-text). Everything else works, except you get the following error:

**Screenshots**
I would include a screenshot, but I don't have a place to host images. Here's the error I get:
```
Fontconfig error: Cannot load default config file
(node:388) UnhandledPromiseRejectionWarning: ReferenceError: applyText is not defined
(node:388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Device (please complete the following information):**
It's on Repl.it, so it's some distribution of Linux.

**Additional notes**

**Comment by monbrey** [comment]
I would suggest if you intend to copy and paste code that you continue to scroll down the page and copy the next section of code also, which defines the `applyText` function.

Or better yet, read and understand what the guide is explaining to you.

**Comment by YodaLightsabr** [comment]
> I would suggest if you intend to copy and paste code that you continue to scroll down the page and copy the next section of code also, which defines the `applyText` function.
> 
> Or better yet, read and understand what the guide is explaining to you.

Then I would suggest adding a different code block for it, or at least include it in the final code block, because I read the whole thing and looked over that section because it only appeared in one code block, where as everything else was revised in the further code blocks.

**Comment by monbrey** [comment]
https://discordjs.guide/popular-topics/canvas.html#resulting-code
