### ISSUE TITLE
ERROR WHEN WRITING NODE .

### ISSUE THREAD

**Issue by Steeee3** [discordjs/guide#554]
![bo](https://user-images.githubusercontent.com/76598913/103141765-675ed000-46f9-11eb-8cd7-75720c9b6680.jpg)
Hi,
I was wondering if you could help me, I was trying to create a currency system by literally copying and pasting all the files but it gives me this error.
The files are the same of the repository here with the base files (created by npm init), app.js is set as index.
I also read a user that had the same question but, as the files are exactly this ones, I don't understand what to do.
Thank you

**Comment by zaida04** [comment]
You might have missed the [Initialize Database](https://discordjs.guide/sequelize/currency.html#initialize-database) section.

**Comment by almostSouji** [comment]
It's recommended to start tutorials at the top and not leave out any steps (as in this case the setup)
- <https://discordjs.guide/sequelize/currency.html#create-models>
- <https://discordjs.guide/sequelize/currency.html#initialize-database>
