### ISSUE TITLE
Section about event handlers

### ISSUE THREAD

**Issue by almostSouji** [discordjs/guide#557]
**Is your feature request related to a problem? Please describe.**
Many different event callbacks cluttering the main file

**Describe the solution you'd like**
a dynamic event handler, similar to the command handler already in place in the guide which loads and executes event modules dynamically.

**Describe alternatives you've considered**
N/A

**Additional notes**
This is a new issue for request tracking without imposing already existing projects as a template

**Comment by ThatGuyJamal** [comment]
Yes an event handler would be a nice addition!
