### ISSUE TITLE
discordjs.guide handler does not work on linux

### ISSUE THREAD

**Issue by XNexusPrimeX** [discordjs/guide#558]
**Describe the bug**
I always use windows to program, but when I put my bot on DisCloud, I had unexpected behavior. I went to search and it seems that many are having this same problem that I had, the discloud has hosts in linux, and the handler crashes in linux .. I don't know why, but it was this answer that I found with other people who had the same problem.
I don't know how to solve this problem

**To Reproduce**
1. Have a linux
2. Make the discordjs.guide handler

**Screenshots**
![image](https://user-images.githubusercontent.com/64230454/103226628-58e80280-490b-11eb-936a-395736795ce0.png)

**Device (please complete the following information):**
- linux

**Additional notes**
well, I talked to some discloud moderators (not a discord, discloud is a powerful host for discord bots), and they said the problem was with the handler. Which makes sense, because my event handler (which I didn't remove from the discord.js guide because it doesn't exist there) works perfectly, only the command handler in the discord.js guide doesn't work, and it doesn't work only on linux, on my pc it works because it is windows

I'm sorry if my English is not good :(

**Comment by iCrawl** [comment]
I would like to know how and why the discloud "team" thinks it is because of the handler.

Because I can assure you node.js code is pretty platform independent, especially what we do with discord bots.

**Comment by almostSouji** [comment]
Highly doubt this has anything to do with our code. If you can still reproduce (and provide more information as to what exactly is supposedly causing this) feel free to re-open
