### ISSUE TITLE
Cooldown command.name is undefined

### ISSUE THREAD

**Issue by Rayg65** [discordjs/guide#567]
undefined bug on colldown command
when the cooldown is not finished it says 'please wait 1.7 more second(s) before reusing the undefined command.' the 1.7 more second(s) is not bugging

**Screenshots**
![image](https://user-images.githubusercontent.com/75600016/104814884-bbb22700-5843-11eb-8c24-c9080a2021f0.png)

**Device:**
 - Device/OS: Windows]
 - Browser: Chrome
 - Version: discord.js v12

**Comment by tipakA** [comment]
This probably isn't a bug, as you didn't provide any code.

This means that you should go to the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue here.

**Comment by almostSouji** [comment]
Either you haven't followed the guide correctly in the cooldown section or at least one of your command objects is missing a "name" property
