### ISSUE TITLE
Multiple Prefixes

### ISSUE THREAD

**Issue by NamVr** [discordjs/guide#568]
**Is your feature request related to a problem? Please describe.**

Add spots for multiple prefixes for a bot like h!, H!, !h, !H.

**Describe the solution you'd like**

Currently in the guide we can only add one prefix in config.json maybe an array for multiple prefixes.

**Describe alternatives you've considered**

**Additional notes**

**Comment by vBread** [comment]
https://anidiots.guide/examples/miscellaneous-examples#multiple-prefixes

**Comment by almostSouji** [comment]
I don't really think this is a feature needed. We cover an approach to server-based prefixes in our [keyv section](https://discordjs.guide/keyv/). Any other application we'll leave as an exercise for the reader, as we don't aim to provide solutions to just about anything one might encounter as a feature request.
