### ISSUE TITLE
Introduce categories in command handlers.

### ISSUE THREAD

**Issue by Wise2006** [discordjs/guide#572]
**Is your feature request related to a problem? Please describe.**

As we keep adding commands, the `commands` folder seems untidy with the large number of files it contains.
I feel that it would be better if the commands were sorted out neatly.

**Describe the solution you'd like**

If there was a follow up on the main guide about this topic, people would easily implement this in their code instead of searching the internet for a long time, confused with the large number of options presented and unsure about what the best solution is.

**Additional notes**

This will be useful both to new learners, and old coders who are looking for an alternative.

**Comment by meister03** [comment]
This seems to be a good Suggestion. But starters on Discord.js should have a good start. Adding more code, would confuse them more. You could make it as additional feature. You have to weigh it up, when you start without categories. The problem is it will be then a habbit
