### ISSUE TITLE
Rename all images and remove stale images for better quality.

### ISSUE THREAD

**Issue by WiseDevHelper** [discordjs/guide#587]
**Is your feature request related to a problem? Please describe.**

A lot of the images are named like `ooaOAeu.png` or `qEIaiam.png`. It would be better if they had names like `sample-embed.png` and `avatar-cmd-demo.png`. Some other images in the repo are extremely out of date [like this one](https://raw.githubusercontent.com/discordjs/guide/master/guide/images/E1CZqFT.png) and [this one](https://raw.githubusercontent.com/discordjs/guide/master/guide/images/jnE3tVM.png).

**Describe the solution you'd like**

I'd like the images to be renamed to something related and meaningful instead of random characters. I'd also like it if the outdated (unused) images are removed/replaced as necessary.

**Additional context**
This will be added as an addition to #576 if approved.

**Comment by Wise2006** [comment]
@almostSouji I'd love it if you can review this and either approve or close it so that I can continue working on #576.
Thank you!

**Comment by Danktuary** [comment]
I agree with renaming the image files, but I do have some concerns. There are already images like [search.png](https://github.com/discordjs/guide/blob/master/guide/images/search.png) and [wallpaper.jpg](https://github.com/discordjs/guide/blob/master/guide/images/wallpaper.jpg). Obviously they belong to certain pages, but at a glance, it's not easy to tell which, and similar images from different pages will be more difficult to rename. 

Another problem with the current approach is that it bunches up everything inside a single `/images/` directory, which forces URLs like this: https://discordjs.guide/assets/img/BbcuyJ6.9ae33cf3.png
Ideally I'd like to have images stored inside their relevant page directories (e.g., `images/send.png` -> `additional-info/images/djs-docs-textchannel-send.png`, `images/wallpaper.jpg` -> `images/popular-topics/canvas-wallpaper.jpg`, etc). I think this would clean up the clutter in the images folder. Although I'm not sure what the generated image URL would result in, but that's not a huge concern. Do note that the markdown image reference will probably go from `![Image title](~@/images/image.png)` to `![Image title](./image.png)`, as `~@` is a webpack alias for the `/guide/` directory.

If you want to incorporate these changes into #576, that'd be great; I'll assign myself and review it. Or if you have any questions or concerns of your own, let me know. Thanks.

**Comment by Wise2006** [comment]
Alright, thanks for the confirmation.
I will try my best to incorporate these changes into #576.

**Comment by Wise2006** [comment]
Hello again,
I noticed that the is a `branding` folder inside the `images` folder.
Where should this folder be moved to?

**Comment by Danktuary** [comment]
Oh, good catch. They can remain there for the time being, since they're not related to specific pages. I may move them at a later date.

**Comment by Wise2006** [comment]
Okay, so I've managed to sort out all images into the respective folders.
I've also added an `images` folder to every category.

However, some images remain.
Some of these, are obviously, the outdated ones.
Others like [`discord-js-avatar.png`](https://github.com/discordjs/guide/blob/master/guide/images/discord-avatar-djs.png) are related to other files.

Yet others are files that have been replaced with the Vue.js made Custom Discord Layout like [`RMv88.png`](https://github.com/discordjs/guide/blob/master/guide/images/RMv88.png).

**Comment by Danktuary** [comment]
[RMv88.png](https://github.com/discordjs/guide/blob/master/guide/images/RMv88.png) can be turned into `<discord-embed>` components, [here's a complete example](https://vue-discord-message.netlify.app/examples.html#complete-embed) of how to use it.

**Comment by WiseDevHelper** [comment]
Since they've already been implemented as `<discord-embed>` components, I think I'll just delete them.
