### ISSUE TITLE
Transform images to custom format. (Reactions)

### ISSUE THREAD

**Issue by WiseDevHelper** [discordjs/guide#597]
**Is your feature request related to a problem? Please describe.**

I've been exploring the guide's source code (while working on #576) for a while and I noticed that most pages use the custom Vue.js Discord layout.
But, I see that, only in the [reactions section](https://deploy-preview-576--discordjs-guide.netlify.app/popular-topics/reactions.html), images have been used instead.

For example,
![Image](https://github.com/discordjs/guide/blob/master/guide/popular-topics/images/custom-emoji-reaction.png?raw=true)

**Describe the solution you'd like**

I'd like the images in the Reactions page to be transformed to the custom Vue.js layout used everywhere else in the guide.

**Additional notes**

I do think that this will require adding the reaction functionality to the Vue.js code if it doesn't exist already.
Thank you!

**Comment by iShibi** [comment]
I looked through the documentation of `vue-discord-message` package. It seems the package doesn't have this `reaction` feature. This must have been the reason that images were used in the first place.

**Comment by Danktuary** [comment]
Yeah, that is why images were used. I'll add reaction components in v3.1.0 of the package and make another PR to update the page. 👍

**Comment by Danktuary** [comment]
Closed in 9444d14
