### ISSUE TITLE
How to get the member's nickname in a guild?

### ISSUE THREAD

**Issue by zebia13** [discordjs/guide#598]
Using `message.author.username` I have the discord username, but it's different from the nickname the user has in the guild where he send the message.

A discord user, with James as username, but with Alison as nickname in the guild send the message :
!hello bot

a code with :
```js
message.reply(` hello ${message.author.username}!`
```
will result with :
Alison hello James!

How to have the result :
Alison hello Alison!

Using only ${message.author} works in this case, but in an embed message, it cause a bug, you have the member's id and not the nickname.

**Comment by advaith1** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
