### ISSUE TITLE
Can I Copy?

### ISSUE THREAD

**Issue by mtgsquad** [discordjs/guide#605]
**Part of the guide or code sample the question is about**

**Question**

This Looks Super Cool, So How Can I Copy The Site And Edit It At The End? It'll Make A Cool Documentation Page For My Web Host!

**Comment by monbrey** [comment]
You're literally posting an issue on the guide's open source code repository.

The [Contribution Guide](https://github.com/discordjs/guide/blob/master/CONTRIBUTING.md) tells you pretty much everything you'd need to know to develop your own.
