### ISSUE TITLE
Adding exact time to other day's format in Embed

### ISSUE THREAD

**Issue by Bhpsngum** [discordjs/guide#621]
Using timestamp in Embeds only shows the exact time (HH:MM) in today & yesterday, otherwise it doesn't show:
Today at 9:51 PM
Yesterday at 12:03 AM
03/24/2021   <--- No exact time included

Solution: Add the exact time format (HH:MM) in the other days too, like in older version:
03/24/2021 at 3:06 PM

**Comment by tipakA** [comment]
That is not what discord.js has any control over. Timestamp is rendered client-side.

**Comment by Bhpsngum** [comment]
alright, so where should i request feature for Dicord client?

**Comment by almostSouji** [comment]
https://dis.gd/feedback
