### ISSUE TITLE
hey so I am trying to make a help command but do not know how to add categories for it.

### ISSUE THREAD

**Issue by Tagliatellelol** [discordjs/guide#643]
So I used the help command that is given in the discord.js guide, but i want to make it so that the help command shows the categories of the commands, please help
[pastebin](https://pastebin.com/CYmyfa07)

**Comment by vBread** [comment]
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
