### ISSUE TITLE
Reload command breaks when no args specified

### ISSUE THREAD

**Issue by Fukur0u** [discordjs/guide#648]
**Describe the bug**
[https://github.com/discordjs/guide/blob/master/code-samples/command-handling/adding-features/12/commands/utility/reload.js](url)
Getting an error with this.
```
C:\Users\~\Desktop\DiscordBot\commands\reload.js:
                const commandName = args[0].toLowerCase();
                                            ^

TypeError: Cannot read property 'toLowerCase' of undefined

```
**To Reproduce**

Running through VSCode
1. In lines 16,17,19, and 22, make sure the directory is pointing to the right folders
2. Call the command in your discord server with NO ARGS
3. Get an error, kills the bot.

**Screenshots**
![2021-04-17_23-17-12](https://user-images.githubusercontent.com/26777336/115133045-20ac2300-9fd3-11eb-9607-aab444889ac6.png)

**Device (please complete the following information):**
 - Device/OS: Windows 10
 - Browser: Chrome
 - Version: 12

**Additional notes**

 **Fix**: 
On the website page for this command: [https://discordjs.guide/command-handling/adding-features.html#reloading-commands](url) the perfect fix is already included, it's just amongst the older version of the code I think. 
Simply added: ```if (!args.length) return message.channel.send(`You didn't pass any command to reload, ${message.author}!`);```
to be the first line under `execute(message, args) {` 

Problem was solved, AND it now properly sends a message when you don't specify a command to reload. 

Sorry if this shouldn't go here, not super comfortable submitting a pull request as I've never done it before.

**Comment by Danktuary** [comment]
I tried with both of the code samples provided for v11 and v12 and [they worked fine](https://i.imgur.com/L2YyuSX.png).

Something I did notice is that the guide page [doesn't use the `args: true` option](https://i.imgur.com/Env2hCd.png) (although it does use an `if (!args.length) return ...` line), but the code samples do. I'll update this to conform to the former.

**Comment by Fukur0u** [comment]
> I tried with both of the code samples provided for v11 and v12 and [they worked fine](https://i.imgur.com/L2YyuSX.png).
> 
> Something I did notice is that the guide page [doesn't use the `args: true` option](https://i.imgur.com/Env2hCd.png) (although it does use an `if (!args.length) return ...` line), but the code samples do. I'll update this to conform to the former.

Thanks for the help 😄

**Comment by tipakA** [comment]
The guide part was written in a way that it mentions args checker just above the said codeblock.
Code samples utilize args checker, so it wasn't included there
