### ISSUE TITLE
ecmaVersion error in Atom

### ISSUE THREAD

**Issue by Codeize** [discordjs/guide#655]
**Describe the bug**
In the code found [here](https://discordjs.guide/preparations/setting-up-a-linter.html#setting-up-eslint-rules) (the lower codeblock,) the ecmaVersion provides an `invalid ecmaVersion` error in Atom. All code in the below screenshot was taken straight from the guide for clarification purposes.

**Screenshots**
![eslint](https://user-images.githubusercontent.com/63158950/116003992-a72abb00-a5f8-11eb-9844-0c24fae64fb7.png)
![botjs](https://user-images.githubusercontent.com/63158950/116003995-aabe4200-a5f8-11eb-989c-ec5743966e3a.png)

**Device (please complete the following information):**
 - Text Editor: Atom.
 - OS: Windows 10.

**Comment by iCrawl** [comment]
Use a better editor:
https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options

This is supported by ESLint, it might not be by the ESLint plugin available on Atom.

**Comment by Danktuary** [comment]
As mentioned above, since this seems to be beyond us, I'll be closing this.
