### ISSUE TITLE
Custom prefix per user, channel or guild support with a !prefix cmd for Commando

### ISSUE THREAD

**Issue by MuhammadUsmanMithani** [discordjs/guide#662]
I don't think Commando has a way to put custom prefixes for a user, even if its single prefix. I was asking if something like this can happen in it:
[Video of sort of custom prefix per user](https://transfer.sh/DSgGU/slUTNeH4y1.mp4)
This is a feature request so that if someone executes !prefix xyz, we can change a this.client.customPrefix("<user|guild|channel>","userID|guildID|channelID", "newprefix"). this can work alongside norm prefix and mention prefix. id suggest that the db used for it is quickdb
note: i separated user, guild and channel so that ppl can select if they want to set that prefix for the guild, user, or channel, and thus the respective ids. if any this.client.cache.user|guild|channel with that id is not found, it can return an error

**Comment by Danktuary** [comment]
Commando supports a global command prefix, and a per-guild prefix through the [CommandoGuild#commandPrefix getter/setter](https://discord.js.org/#/docs/commando/master/class/CommandoGuild?scrollTo=commandPrefix). However, the rest seems like a more specific use case; users can implement that themselves if they see fit.
