### ISSUE TITLE
The OAuth guide page is unclear

### ISSUE THREAD

**Issue by nimit2801** [discordjs/guide#665]
**Describe the bug**
Recently I started working with Oath for discord applications and found out there was already a guide by discord.js for that.
But when I tried the code sample, I was not able to get the desired output D:
I even tried to use the same code in [here](https://github.com/discordjs/guide/tree/master/code-samples/oauth/simple-oauth-webserver).

**To Reproduce**
1. Goto to this [link](https://discordjs.guide/oauth2/#getting-started-with-oauth2).
2. Follow all steps and kaboom is not working I can't the 

Screenshots
SS 1:
![image](https://user-images.githubusercontent.com/53462249/117886057-4a075880-b2cc-11eb-9571-ca2bbe90bca5.png)
SS 2: Directed me to auth page
![image](https://user-images.githubusercontent.com/53462249/117886125-63100980-b2cc-11eb-99b4-ba534718a326.png)
SS3: Redirected back to my webapp with some code(access code)
![image](https://user-images.githubusercontent.com/53462249/117886286-9488d500-b2cc-11eb-8632-e27f646e8348.png)
No output shown for the person who was authenticated
SS4: Whats happening in the terminal?
![image](https://user-images.githubusercontent.com/53462249/117886406-c5690a00-b2cc-11eb-8b6b-9be18ffa544d.png)
Its showing the output correctly but I don't want the output there D:

**Device (please complete the following information):**
Device/OS: [e.g. iOS]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. latest]

**Additional notes**
I'll try to solve this my way and update with a PR,
mean while please help me with some code that might solve this 🧷

**Comment by monbrey** [comment]
Then it's functioning perfectly. The code you linked does not modify the HTML - it just console.logs the data.

Please follow the guide if you want to make modifications.

**Comment by monbrey** [comment]
Not via the `code` workflow it doesn't - that assumes youve changed the response type to `token` which again, is a step in the guide you seem to refuse to revisit.

The samples are not broken.

**Comment by Danktuary** [comment]
Closing this since #666 was merged
