### ISSUE TITLE
Bank system for the currency using sequelize

### ISSUE THREAD

**Issue by BrainyV** [discordjs/guide#669]
### Bank system for sequelize.

**I tried to make it like this:**

```js
module.exports = (sequelize, DataTypes) => {
    return sequelize.define('users', {
        user_id: {
            type: DataTypes.STRING,
            primaryKey: true,
        },
        balance: {
            type: DataTypes.INTEGER,
            defaultValue: 0,
            allowNull: false,
        },
    bank: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      allowNull: false,
    },
    }, {
        timestamps: false,
    });
};
```

```js
Reflect.defineProperty(client.currency, 'getBank', {
    value: function getBank(id) {
        const user = client.currency.get(id);
        return user ? user.bank : 0;
    },
});
```
But I get this error:

>  UnhandledPromiseRejectionWarning: SequelizeDatabaseError: SQLITE_ERROR: no such column: bank

**Comment by Drahcirius** [comment]
If you're trying to add a new column to the table, you'll either need to do a database migration (unfortunately not covered in the guide), force sync (deletes all your data), or manually add it in with a query (you'll need to know SQL).

Also, Github issues is not the place to get assistance for your own enhancements. Please don't post your errors here expecting us to help you fix them.
