### ISSUE TITLE
how to check a specific item in inventory? (currency bot using sequelize)

### ISSUE THREAD

**Issue by redocpacks** [discordjs/guide#673]
**Part of the guide or code sample the question is about**
```
} else if (command === 'sell') {
		const item = await CurrencyShop.findOne({ where: { name: { [Op.like]: commandArgs } } });
		if (!item) return message.channel.send('That item doesn\'t exist.');
		const items = await user.getItems();
		
		const user = await Users.findOne({ where: { user_id: message.author.id } });
		currency.add(message.author.id, item.cost);
		await user.removeItem(item);

		message.channel.send(`You've sold a ${item.name} and got ${item.cost} TKP`);
```

**Question**
sorry i know this is more about making people learn than answering questions, but ive set up a sell command by figuring out how to make a "removeItem()" function, which works surprisingly well, but i don't know how to see if a certain item is in a users inventory. i dont have much experience and theres nothing about it on the internet, so i was hoping if anyone knew it would be you guys?

**Comment by Drahcirius** [comment]
Firstly, Github issues is not the place to ask questions, especially ones that that that are for your own enhancements. Issues are for bug reports and other things that pertain to the guide.

Secondly, there is a function to display a user's inventory, you can extrapolate using that.
