### ISSUE TITLE
Documentation may be outdated

### ISSUE THREAD

**Issue by lejubjoteur** [discordjs/guide#686]
Hello, I think that documentation is outdated about : `const connection = await message.member.voice.channel.join();` which returns undefined https://discordjs.guide/voice/the-basics.html#joining-voice-channels 
but it works with `const connection = await message.member.voiceChannel.join();`

**Comment by iCrawl** [comment]
Yeah, if you are on v11 which is beyond outdated, that is correct.

In v12 its what you described in your first case and is completely removed from v13.
