### ISSUE TITLE
Community Frameworks

### ISSUE THREAD

**Issue by xHyroM** [discordjs/guide#703]
Don't you want to add something like community resources/frameworks where people could add their npm packages to make things easier? I've heard that commando is probably going to be shut down so I think that would be good.

**Comment by adrifcastr** [comment]
Sapphire replaces commando

**Comment by monbrey** [comment]
Given the poor quality of all of the community resources/frameworks that pop up in our support channels, no, I don't think we do.

**Comment by almostSouji** [comment]
Most community resources are unfortunately not up to our quality standards, badly maintained, and tend to fade in and out of existence. The other bunch we see tries to emulate core library functionality (for whatever reason) and causes more of a headache than they're useful, often not covering edge cases we then have to deal with in support (and find out what kind of nonsense people are using this time).

These circumstances would require us to constantly re-evaluate which packages and frameworks are useful (or even usable) and adapt the guide accordingly, which is not really a good use of anyone's time.

The only well maintained fully fledged framework at the moment seems to be sapphire, which we will likely address at some point.
