### ISSUE TITLE
help command

### ISSUE THREAD

**Issue by Savers123** [discordjs/guide#722]
can you make a page about creating a help command that gets all the names of the available commands and sends them to the channel?
and possibly channel help.

**Comment by SinisterDeveloper** [comment]
Ok so first off, ask help in the [Official Server](https://discord.gg/djs) of Discord.js, not here.

Second, the guide already has a page regarding a Dynamic help command. **[Read it here](https://discordjs.guide/command-handling/adding-features.html#a-dynamic-help-command)**

**Comment by almostSouji** [comment]
> Ok so first off, ask help in the Official Server of Discord.js, not here.

Feature suggestions surely go on the guide repository. Please cut back the constant seemingly obvious redirection.

For the feature request itself: We currently still have a dynamic help command in the guide, which will however move to slash commands going forward which completely removes the need for a command that lists commands, as discord will basically do that natively in the slash command UI.
