### ISSUE TITLE
The link to Gateway Intents on the Upgrade guide is broken

### ISSUE THREAD

**Issue by voidf1sh** [discordjs/guide#726]
**Describe the bug**

The link "Refer to our more detailed article about this topic." located [here](https://deploy-preview-680--discordjs-guide.netlify.app/additional-info/changes-in-v13.html#intents) is missing the `.html` extension, leading to a 404. The link is `https://deploy-preview-680--discordjs-guide.netlify.app/popular-topics/intents` but should be `https://deploy-preview-680--discordjs-guide.netlify.app/popular-topics/intents.html`

**To Reproduce**

![image](https://user-images.githubusercontent.com/10382512/126880873-dec69974-871e-49b2-9951-b1b8ae04b68e.png)
![image](https://user-images.githubusercontent.com/10382512/126880884-86cffc86-722e-4ba3-b7d1-1642b78c7861.png)

**Device (please complete the following information):**
 - Device/OS: Windows 10
 - Browser: Chrome
 - Version: 92.0.4515.107

**Additional notes**

**Comment by Danktuary** [comment]
#680 is still a work in progress; please leave a comment there instead.
