### ISSUE TITLE
Spelling Error in code on Discord.js-guide Voice 

### ISSUE THREAD

**Issue by SeenIsHere** [discordjs/guide#730]
**Describe the bug**

```
async function probeAndCreateResource(readableStream) {
	const { stream, type } = await demuxeProbe(readableStream);
	return createAudioResource(stream, { inputType: type });
}
```
`demuxeProbe` should be changed to `demuxProbe`

**To Reproduce**

1. Go to discord.js-guide audio section
2. Navigate to Audio Resources > Optimizations > Probing to determine stream type

**Screenshots**

![image](https://user-images.githubusercontent.com/48893550/126915027-cefdece3-8cf5-41df-b446-08dcc55352e2.png)

**Device (please complete the following information):**

-Browser: Chrome
- Version: Version 91.0.4472.164 (Official Build) (64-bit)

**Additional notes**
It is a spelling error

**Comment by Danktuary** [comment]
Fixed in the v13-prep branch, closing since this applies to only that branch and will be merged into master eventually.
