### ISSUE TITLE
Global commands with guild perms

### ISSUE THREAD

**Issue by YorkAARGH** [discordjs/guide#748]
With the up coming slash command section rewrite, would it be at all possible to cover setting guild permissions for global commands?

**Comment by WiseDevHelper** [comment]
This has already been covered in [this section of the guide.](https://discordjs.guide/interactions/slash-command-permissions.html)
You just have to fetch the global command instead of the guild command.

```js
const command = client.application.commands.fetch('123456789012345678');
```
Will add this as a tip in a PR later.
