### ISSUE TITLE
Link in `What's new?` leads to 404

### ISSUE THREAD

**Issue by papaia** [discordjs/guide#749]
**Describe the bug**
Clicking "Command handling" in the [`updated` part in the What's new? section](https://discordjs.guide/whats-new.html#updated) of the guide redirects to a 404.

**To Reproduce**
1. Go to https://discordjs.guide/whats-new.html#updated
2. Click on "Command handling"
3. 404

**Screenshots:**
![image](https://user-images.githubusercontent.com/43409674/127869592-1684d157-6982-410e-9766-db339b67f481.png)

**Device:**
 - Browser: chrome 92.0.4515.107, edge 92.0.902.62

**Additional notes**
I can make a PR to remove the `.md` in `whats-new.md` if needed
https://github.com/discordjs/guide/blob/76303256b96d34c3b8a563c60b175fd0080b3b39/guide/whats-new.md#L58

**Comment by Megatank58** [comment]
Command handling link in that part is apparently https://discordjs.guide/command-handling.html, it should instead be https://discordjs.guide/command-handling/
