### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by ToniTurnerr** [discordjs/guide#78]
So I've been trying to make my already functioning with a command handler however when trying to make my ping command, it doesn't work. Can anyone show me how to fix this?

https://i.imgur.com/C7py2Oa.png
https://i.imgur.com/6tnm8ym.png

Thanks.

**Comment by Danktuary** [comment]
It looks like you're trying to use `await` outside of an `async` function, i.e. you need to add `async` before `execute()`.
However, please don't use the issue tracker to ask about syntax error. Instead, you can join the [official Discord.js server](https://discord.gg/bRCvFy9) to ask any further questions, should you have questions relating to the library or JS itself. You'll receive a much faster response over there anyway. :)
