### ISSUE TITLE
Translate the guide to many languages

### ISSUE THREAD

**Issue by Ddongddi** [discordjs/guide#783]
**Is your feature request related to a problem? Please describe.**
Some discord.js users don't know or are not familiar with English, and they don't understand what this guide is saying. They ask questions to the people of their country with their languages. 

**Describe the solution you'd like**
I'd like to propose translating to other languages. People are translating the discord.js homepage because they have no official translation. If we translate the guide, it will make more people use the guide and make a bot. It will help people who don't know English.

**Describe alternatives you've considered**
We can just translate with google translator, but I feel that translating officially is the best solution

**Additional notes**
Please consider this request positively and decide. It can help many people who don't know or are not familiar with English.

**Comment by almostSouji** [comment]
We do currently not plan to use an internationalization framework for the guide, however, feel free to fork the project and host a translated version yourself under the given [license](https://github.com/discordjs/guide/blob/main/LICENSE). Maintaining, or even just evaluating, lots of different translations is at the moment not within our capacities, so please understand that we cannot list bootleg translations.
