### ISSUE TITLE
How o send a message when a button is clicked

### ISSUE THREAD

**Issue by devramsean0** [discordjs/guide#784]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
a added bit to the button section showing us how to reply to a certain message

**Describe alternatives you've considered**
a alternative to buttons

**Comment by almostSouji** [comment]
Already covered in https://discordjs.guide/interactions/buttons.html#responding-to-buttons
To do so on a certain message you could check the `.message` of the button interaction, before responding to it
