### ISSUE TITLE
guild.shardID -> guild.shardId change not documented

### ISSUE THREAD

**Issue by Ortovoxx** [discordjs/guide#785]
**Describe the bug**
In v12 the property was `guild#shardID` and in v13 it has been changed to `guild#shardId`

This is not currently documented

Please document this change

**Comment by DaStormer** [comment]
It’s documented, see [here](https://discordjs.guide/additional-info/changes-in-v13.html#thing-thingid)

**Comment by Danktuary** [comment]
It would help if all the affected property names were listed under that section, for the sake of being able to use `Ctrl +F` or the search bar to find it.
