### ISSUE TITLE
Sidebar Improvements

### ISSUE THREAD

**Issue by vzwGrey** [discordjs/guide#80]
Would be nice to see the currently open page being highlighted, like the currently open headline.
I think that would make navigating the sidebar a bit easier.
(The top most `Adding more commands` in this case)
![example](https://lolisafe.moe/lzhhnuqS.png)

Maybe even change the background of the currently open section in the sidebar a bit, so you can easily see where the next page is. Or indicate it some other way.

**Comment by Danktuary** [comment]
Just thought I'd comment and say I haven't forgotten about this. There's currently no easy way to do this with Docsify (or at least not that I know of), but I do have plans on converting the guide to use [VuePress](https://vuepress.vuejs.org/), which has this built-in.

![VuePress screenshot](https://i.imgur.com/GDZBE7Z.png)

Hopefully sometime this month I'll have that done. 😅
