### ISSUE TITLE
command handler

### ISSUE THREAD

**Issue by Zoh63392187** [discordjs/guide#811]
Your documentation on Discordjs.guide does not work on the command handler part.
I tested the entire guide on setting up a bot and the bot joins perfectly bot it does not respond to commands. (ping, beep ect.)

**Comment by Josh-Sul** [comment]
Yep. Just started with Discord.JS and can't get any of the guide tutorials to work apart from the logging in bit!

**Comment by Lombra** [comment]
I believe you're victims of the issue I opened yesterday.
https://github.com/discordjs/guide/issues/810

**Comment by Kivuliar** [comment]
I myself just got stuck at "registering slash commands" which also just got updated in the guide, my commands are detected (I think...) When I use for example command "ping", I can see in logs that bot properly recognizes via "InteractionCreate" event - what command I'm trying to use - "ping" command, but no code is executed and I get "This interaction failed".
