### ISSUE TITLE
Formatters.time() parameter type (style) should refer (link) to styles page

### ISSUE THREAD

**Issue by fasterplayer** [discordjs/guide#812]
**Is your feature request related to a problem? Please describe.**

https://discord.js.org/#/docs/main/stable/class/Formatters?scrollTo=s-time

https://discord.js.org/#/docs/main/stable/typedef/TimestampStylesString
**Describe the solution you'd like**

Should be a clickable link to the styles

**Comment by Danktuary** [comment]
This is an issue with the d.js typedocs, not the guide
