### ISSUE TITLE
On writing for beginners

### ISSUE THREAD

**Issue by merunno** [discordjs/guide#829]
⚠ I am Japanese and not very good at English. No offense.

**Part of the guide or code sample the question is about**

This is the code you were instructed to add in this guide.

```js
client.on('interactionCreate', interaction => {
    console.log(interaction);
});
```

The code that originally required Slash Command was raised as a tutorial, but there were no instructions in that tutorial to add Slash Command, so I added the instructions.

**Question**
But then I discovered this tip.

![image](https://user-images.githubusercontent.com/82575685/129889557-991e351f-5d07-4f99-a073-b9b229a156cb.png)

If you are using discord.js, this tip may be enough.

I thought this tip alone would be very difficult for a beginner to follow this tutorial.

Is it better to just use this tip, or should I add some text like [this pull request?](https://github.com/discordjs/guide/pull/828) I would like to know.

I'm sorry if my English is not good enough.

**Comment by WiseDevHelper** [comment]
Hi, Thank you for contributing.

It has been noted that the guide is currently a bit hard to understand. 
PRs #819 and #826 have been opened to resolve this issue and make it smoother for beginners to follow along.
Please make sure to check out the [section from the deploy preview](https://deploy-preview-826--discordjs-guide.netlify.app/creating-your-bot/) of #826.

**Comment by merunno** [comment]
Hi, Thanks for the reply.

I understand that this has already been done. Thank you very much.

Should I close this issue?

**Comment by WiseDevHelper** [comment]
Sure! You're welcome!
