### ISSUE TITLE
Slash Commands discordjs guide suggestion

### ISSUE THREAD

**Issue by ThatGenZGamer48** [discordjs/guide#844]
Make two seperate pages for "Registering slash commands with Builders" And "Registering slash commands with Application command manager"

For some people who do not want to use builders it will be useful.

**Comment by adrifcastr** [comment]
I don't see the correlation between the builders and the managers. Neither of those depend on eachother.

**Comment by Dragonizedpizza** [comment]
I think they meant with rest 😅

**Comment by almostSouji** [comment]
We use the tool best suited for the job for each guide section. Command deployment should not be dependent on a websocket connection (or even deployed with every bot restart). We recommend using the REST package approach to deploy commands on-demand, when you know you changed something.
