### ISSUE TITLE
Slash commands pages not using the Command Handler makes it confusing

### ISSUE THREAD

**Issue by EGGamer** [discordjs/guide#859]
**Is your feature request related to a problem? Please describe.**
The guide shows how to make a command and event handler, which is really great! Normally, a newbie to Discord.js would follow the guide in order, so they would add the command/event handler, and then, if they wanted, they would go to the specific Slash command pages (Registering, Replying, permissions etc). 

But there is a little problem that can cause confusion. Currently only the "Registering slash commands" page uses example code that utilizes the command/event handler created previously, the rest (replying, permissions, buttons...) don't use the handler, and put it all in the index.js making the syntax a little bit different, and confusing newbies (I even got confused at first too being more or less an intermediate Discord.js dev (first time working with interactions tho). 

**Describe the solution you'd like**
I would change the example code shown in **Replying to slash commands**, **Slash commands permissions**, **Buttons** and **Select Menus** pages to use the Command and Event handler created before in the guide.

**Describe alternatives you've considered**
If there is a major reason behind not using the command/event handler in these examples, maybe providing a Toggle to show example code WITH and WITHOUT the handler (though, I don't know why anyone would not consider a command handler, even in small projects)

**Comment by WiseDevHelper** [comment]
As you mentioned, the pages use `index.js` to be concise so that you can clearly understand the concepts explained and not worry about command handling and multiple files. However, I would love to hear the opinions of other contributors and collaborators on this matter.

**Comment by EGGamer** [comment]
Yeah, I understand the decision behind it, but the fact that the first page "Registering slash commands" uses the command handler but the rest doesn't, makes it super confusing. As I said, maybe you could add a toggle that shows code within the index.js or with the command handler, but I don't know how much work requires that.

**Comment by onekiguwolf** [comment]
I would also like this! I use the `messageCreate` intent for all of my commands within my one `index.js` file, but as a programmer new to discord.js (and javascript too! it's a crash course for me to learn more) I was wondering if it is also possible to show a guide for those using one file only.

**Comment by algotastic** [comment]
I also think it would be very helpful to have a guide that builds off of the previous sections.

Here's the specific example that's confusing me right now.  Currently, the Event Handling section doesn't use any of the code that was in the 'interactionCreate' event during the Command Handling section, so it's not clear how the client is supposed to be managed when extracting that event into a separate file.

The other inconsistencies mentioned above were also confusing.  I understand each section is meant to be concise and independent, but at least having the option of building on top of the previous section would be very helpful in my opinion.

**Comment by Dimensional** [comment]
I have to agree with this. The guide for Event Handling breaks the entire tutorial by not explaining how to change `client.on('interactionCreate'`, as explained in Command Handling, into something else. At the moment Command Handling has the commands parsed through an event written into index.js, but interactionCreate.js doesn't have anything for that.

I've been trying to build a bot using these libraries for the past 3 years, and the guides keep having these mistakes that completely halt all progress.

**Comment by JohannSuarez** [comment]
I came to this repo wanting to make an issue about this problem. I'm glad I'm not the only one being completely blocked by this.

**Comment by SuperDragonXD** [comment]
If you are using the dynamic command loader (the commands/<file>.js) stuff, you can add this:
```js
const eventFiles = fs.readdirSync('./events').filter(file => file.endsWith('.js'));

for (const file of eventFiles) {
	const event = require(`./events/${file}`);
	if (event.once) {
		client.once(event.name, (...args) => event.execute(...args));
	} else {
		client.on(event.name, (...args) => event.execute(...args));
	}
}
```

before the log on statement:
```js
// The above code

client​.​login​(​token​)​;
```

So the final code will be:
```js
// Dependencies
const​ ​fs​ ​=​ ​require​(​'node:fs'​)​; 
​const​ ​{​ Client​,​ Collection​,​ Intents ​}​ ​=​ ​require​(​'discord.js'​)​; 
​const​ ​{​ token ​}​ ​=​ ​require​(​'./config.json'​)​; 

// Load Client with the required intents
​const​ ​client​ ​=​ ​new​ ​Client​(​{​ ​intents​: ​[​Intents​.​FLAGS​.​GUILDS​]​ ​}​)​; 

// Command loader
​client​.​commands​ ​=​ ​new​ ​Collection​(​)​; 
 ​const​ ​commandFiles​ ​=​ ​fs​.​readdirSync​(​'./commands'​)​.​filter​(​file​ ​=>​ ​file​.​endsWith​(​'.js'​)​)​; 

 ​for​ ​(​const​ ​file​ ​of​ ​commandFiles​)​ ​{ 
 ​        ​const​ ​command​ ​=​ ​require​(​`./commands/​${​file​}​`​)​; 
 ​        ​client​.​commands​.​set​(​command​.​data​.​name​,​ ​command​)​; 
 ​} 
  
 ​client​.​once​(​'ready'​,​ ​(​)​ ​=>​ ​{ 
 ​        ​console​.​log​(​'Ready!'​)​; 
 ​}​)​; 
  
// Command handler
 ​client​.​on​(​'interactionCreate'​,​ ​async​ ​interaction​ ​=>​ ​{ 
 ​        ​if​ ​(​!​interaction​.​isCommand​(​)​)​ ​return​; 
  
 ​        ​const​ ​command​ ​=​ ​client​.​commands​.​get​(​interaction​.​commandName​)​; 
  
 ​        ​if​ ​(​!​command​)​ ​return​; 
  
 ​        ​try​ ​{ 
 ​                ​await​ ​command​.​execute​(​interaction​)​; 
 ​        ​}​ ​catch​ ​(​error​)​ ​{ 
 ​                ​console​.​error​(​error​)​; 
 ​                ​await​ ​interaction​.​reply​(​{​ ​content​: ​'There was an error while executing this command!'​,​ ​ephemeral​: ​true​ ​}​)​; 
 ​        ​} 
 ​}​)​;

// Event loader/handler
const eventFiles = fs.readdirSync('./events').filter(file => file.endsWith('.js'));

for (const file of eventFiles) {
	const event = require(`./events/${file}`);
	if (event.once) {
		client.once(event.name, (...args) => event.execute(...args));
	} else {
		client.on(event.name, (...args) => event.execute(...args));
	}
}

client​.​login​(​token​)​;
```

The above final code should be included somewhere in the guide, like a "Final code" or something page.
