### ISSUE TITLE
"registering slash commands" and "slash commands permissions" aren't consistent

### ISSUE THREAD

**Issue by Stonehoppers** [discordjs/guide#873]
**Describe the bug**
https://discordjs.guide/interactions/registering-slash-commands.html
uses the REST method to register commands

while on
https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands
it follows the old ApplicationCommandManager method
as such, the "defaultPermission" tag won't work for people who followed the updated REST method

for consistency's sake, "defaultPermission" should be changed to "default_permission" in that section of the guide, reflecting the new REST method shown in the "registering slash commands" section of the guide

**Screenshots**
https://cdn.discordapp.com/attachments/682245563193884710/889900690556739614/unknown.png

**Comment by wizo06** [comment]
#860 this PR includes refactor for permissions
