### ISSUE TITLE
Unregistering Slash commands

### ISSUE THREAD

**Issue by Empi3** [discordjs/guide#879]
I've followed your guide and a few others and it all works nicely.
Problem is, I have deleted some of the commands (like /ping /server /user) that were just for learning purposes.
Now I still have them registered on my server, and on another server the new commands that I created seem to be duplicated, probably because I registered them once as guild commands, then as client commands.

How do I clean up the registered commands?

sharing my deploy-commands.js
`const fs = require('fs');
const { REST } = require('@discordjs/rest');
const { Routes } = require('discord-api-types/v9');
const { clientId, guildId, token } = require('./config.json');

// 0 for guild, 1 for client.
const mode = 1;

// Populate commands list
const commands = [];
const commandFiles = fs.readdirSync('./commands').filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	commands.push(command.data.toJSON());
}

console.log('Registering commands:');
console.log(commands);

const rest = new REST({ version: '9' }).setToken(token);

if (mode === 0) {
	// update command list for guild (FreeSouls server). used for testing.
	rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands })
		.then(() => console.log('Successfully registered application Guild commands.'))
		.catch(console.error);
} else {
	// Globally updates commands on all servers. Cached commands take up to 1h to be updated.
	rest.put(Routes.applicationCommands(clientId), { body: commands })
		.then(() => console.log('Successfully registered application commands.'))
		.catch(console.error);
}`
![image](https://user-images.githubusercontent.com/66061113/134598037-cfcc15bc-7b8d-495c-b579-dfe271f98431.png)

**Comment by Underpants-dev** [comment]
Can you tell us which commands you want to delete?

**Comment by Empi3** [comment]
knowing how to delete them both would be best I believe, as I'll continue to test them in Guild, then push to client when I'm done. thanks ;j

**Comment by wizo06** [comment]
#860 includes a section for deleting commands

**Comment by WiseDevHelper** [comment]
Assuming you have the ids for the commands and you can evaluate this:
If you're trying to delete a `guild` command:
```js
const command = await client.guilds.cache.get('123456789012345678')?.commands.fetch('876543210987654321');
await command.delete();
```
If you're trying to delete a `global` command:
```js
const command = client.application?.commands.fetch('123456789012345678');
await command.delete();
```

If you're using the `@discordjs/rest` module (as you have shown), you can `PUT` (`rest.put()`) an empty array to delete all commands or exclude the commands you want to delete from the array. In this case, just delete the files for the commands you don't need or move them to a different folder (not in `commands`) and register them.

You should now only see a single set of commands.

**Comment by Empi3** [comment]
> If you're using the `@discordjs/rest` module (as you have shown), you can `PUT` (`rest.put()`) an empty array to delete all commands or exclude the commands you want to delete from the array. In this case, just delete the files for the commands you don't need or move them to a different folder (not in `commands`) and register them.
> 
> You should now only see a single set of commands.

That worked. 
Did a guild update of my test server to remove the old commands. Now the new commands are duplicated but that's fine for a test server. 
Update the other guild with an empty array as you said to clear the guild commands and that left only the client commands.

Thanks a lot.
Is this the right place to ask questions like the one above?

**Comment by WiseDevHelper** [comment]
> Thanks a lot.

You're welcome! 😄 
> Is this the right place to ask questions like the one above?

No, it's better to either use the Discord server or for questions like these, GitHub [Discussions](https://github.com/discordjs/guide/discussions)!

**Comment by rizuwan86** [comment]
> Assuming you have the ids for the commands and you can evaluate this: If you're trying to delete a `guild` command:
> 
> ```js
> const command = await client.guilds.cache.get('123456789012345678')?.commands.fetch('876543210987654321');
> await command.delete();
> ```
> 
> If you're trying to delete a `global` command:
> 
> ```js
> const command = client.application?.commands.fetch('123456789012345678');
> await command.delete();
> ```
> 
> If you're using the `@discordjs/rest` module (as you have shown), you can `PUT` (`rest.put()`) an empty array to delete all commands or exclude the commands you want to delete from the array. In this case, just delete the files for the commands you don't need or move them to a different folder (not in `commands`) and register them.
> 
> You should now only see a single set of commands.

Absolutely I recommend this to put/publish in discordjs.guide for Unregister/Delete commands which is accidentally registered (typo) or just removing some command that doesn't exists

**Comment by Empi3** [comment]
I have to admit that at first I didn't understand that Global and Guild commands were 2 separate sets and could coexist. The guide is a great help but a small note about this wouldn't hurt :p
