### ISSUE TITLE
add a page on args

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [discordjs/guide#888]
add a page on message arguments (args)

**Comment by almostSouji** [comment]
Discord prefers interactions as the primary way for users to interact with bots and requires verified bots to not rely on message content for command handlers [next year](https://support-dev.discord.com/hc/en-us/articles/4404772028055). In preparation we have removed message-content-based sections from the guide. We won't re-add them.

**Comment by SirEpiclyAmazing** [comment]
ok
