### ISSUE TITLE
"There was an error in the slash command" fails under "interaction already replied "

### ISSUE THREAD

**Issue by eyal282** [discordjs/guide#896]
If you reply to the interaction and then cause an error all of index.js will crash.

**Comment by WiseDevHelper** [comment]
Please provide the code and the complete error so we can help you identify where the issue occurs.

As per the title of this issue, this error seems to be caused due to you `.reply`ing twice. The second `.reply` should be replaced with `.followUp` or `.editReply` depending on what you'd like to do.

**Comment by eyal282** [comment]
> Please provide the code and the complete error so we can help you identify where the issue occurs.
> 
> As per the title of this issue, this error seems to be caused due to you `.reply`ing twice. The second `.reply` should be replaced with `.followUp` or `.editReply` depending on what you'd like to do.
> 
> Also, please use [GitHub Discussions](../discussions) or the [discord server](https://discord.g/djs).

I don't have the code anymore. But the missing followUp is missing in what this script provides. My fix appears here:
https://github.com/eyal282/Chess-ELO-Discord-Bot/blob/replit/index.js#L67
