### ISSUE TITLE
Dynamic help command for slash commands SUBCOMMANDS

### ISSUE THREAD

**Issue by NotDemonix** [discordjs/guide#899]
I have slash commands and its categorized to subcommands so i can have more commands, i want to get for example all subcommands for `/music` (the options are created as array)
I want it to show all subcommands for `/music`:
```
play, stop, and rest of commands
```

**Comment by NotDemonix** [comment]
I can write on my own but i dont want

**Comment by almostSouji** [comment]
I don't understand what your question is. If they are sub commands you just type `/music` and all the sub cmds will appear.

**Comment by StarL0st** [comment]
> I don't understand what your question is. If they are sub commands you just type `/music` and all the sub cmds will appear.

@almostSouji I think he is saying that he wants to have a guide on a dinamic help commnad, like the old one that you put the command and it shows all of the othet subcommands

**Comment by almostSouji** [comment]
With what's coming (and even what's already there), I see no need to have a help command anymore.
