### ISSUE TITLE
Code block line numbers overflow

### ISSUE THREAD

**Issue by Nciklol** [discordjs/guide#913]
**Describe the bug**
On most codeblocks on the guide, the line numbers will overflow onto the main page resulting in some really ugly ui. 

**To Reproduce**
Specific example [here](https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands)
Scroll down to the end of the codeblock
Observe when the line numbers end 

**Screenshots**
![Screenshot_20211013_190914](https://user-images.githubusercontent.com/42541753/137229365-2298d3b9-2a71-4ed1-9413-f14dd0938579.png)

**Device (please complete the following information):**

Arch Linux, Google Chrome version `94.0.4606.61` (Also reproducable on Firefox version `92.0.1`)

**Comment by isaacKenyon** [comment]
Original link is a 404, the [equivalent page](https://discordjs.guide/interactions/slash-commands.html#guild-commands) doesn't appear to have this issue anymore.

Tested on: Firefox `v102.0.1 (64-bit)`, Chrome `v103.0.5060.134 (64-bit)`.

**Comment by zayKenyon** [comment]
> Original link is a 404, the [equivalent page](https://discordjs.guide/interactions/slash-commands.html#guild-commands) doesn't appear to have this issue anymore.
> 
> Tested on: Firefox `v102.0.1 (64-bit)`, Chrome `v103.0.5060.134 (64-bit)`.

That equivilant page is now a 404, the [new](https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands) page does not have this problem. This issue should be closed.

**Comment by Jiralite** [comment]
I could not reproduce this issue in the first place. Furthermore, going back to fdbb7cb of the guide and running it locally yields the same results for me - still cannot reproduce it:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/33201955/198750344-1832c262-3003-44b4-b55b-6476523ba145.png">

I'm not inclined to believe this is actually fixed - merely some device-specific problems or other shenanigans. That being said, a new issue is welcome if this returns.
