### ISSUE TITLE
Referencing `client` from command files

### ISSUE THREAD

**Issue by haydennyyy** [discordjs/guide#92]
I notice there's no mention of referencing the `client` from within a command file in the `commands` folder. Documentation on how this works would be nice.

**Comment by Danktuary** [comment]
There's actually a very small reference to in the [adding features section](https://discordjs.guide/#/command-handling/adding-features?id=a-dynamic-help-command), at the top of the 3rd codeblock. So, whenever you need your client instance, you can use `message.client` inside any commands.

That being said, I understand that it could be a bit more obvious. Do you have a suggestion on where to place a hint about this?

**Comment by haydennyyy** [comment]
Perhaps in the Common Questions section?

**Comment by Danktuary** [comment]
Apologies for the delay. I decided to just add a `<p class="tip">` tag in one of the relevant pages, because it's not really a commonly asked question and fits better there.
