### ISSUE TITLE
The contrast of hyperlinks in warning containers looks bad

### ISSUE THREAD

**Issue by Jiralite** [discordjs/guide#928]
**Describe the bug**

Hyperlinks in containers don't look particularly good. At a first glance (at least to me), it's not immediately apparent something is a hyperlink. Take this for example:

![image](https://user-images.githubusercontent.com/33201955/138083869-55fa9a19-5d47-4db2-8931-28d7078975b5.png)

The link seems more like it is... highlighted over(?) which doesn't jump out as a link. The contrast of it with the background really isn't great too.

**To Reproduce**

1. Go to https://discordjs.guide/popular-topics/faq.html#how-do-i-find-all-online-members-of-a-guild
2. View the warning container

**Device (please complete the following information):**

 - Device/OS: MacBook Pro (Mid 2015): macOS Big Sur 11.6
 - Browser: Google Chrome
 - Version: 94.0.4606.81

**Comment by Bubalo1234** [comment]
perhaps change the text color or make it italic

**Comment by almostSouji** [comment]
Will be resolved with a more exhaustive rewrite of guide visuals
