### ISSUE TITLE
Guide FAQ: Incorrect code example

### ISSUE THREAD

**Issue by Astropilot** [discordjs/guide#961]
**Part of the guide or code sample the question is about**

Guide -> FAQ -> How do I DM a specific user?
Link: https://discordjs.guide/popular-topics/faq.html#how-do-i-dm-a-specific-user

**Question**

The example code given in the guide seems incorrect to me:
```typescript
const user = client.users.cache.get('id');
user.send('content');
```

To retrieve the user it would be better to use the `fetch()` method of the UserManager because otherwise it is possible that the desired user is not in the cache and that the given code fails. (This happened to me in one of my bot in which I copied this code).

The proposed correction:
```diff
- const user = client.users.cache.get('id');
+ const user = await client.users.fetch('id');
user.send('content');
```

What do you think about it?

**Comment by almostSouji** [comment]
Hm, both current and suggested fail if the user doesn't share a server with the bot or has DMs disabled. This removes the fail in current due to an uncached user.

Should probably be a PR then.
