### ISSUE TITLE
Slash Commands Guide Incorrect ID

### ISSUE THREAD

**Issue by asiangoldfish** [discordjs/guide#963]
**Describe the bug**
In this page of the DiscordJS tutorial ([click here](https://discordjs.guide/creating-your-bot/creating-commands.html#command-deployment-script)), the guide states that `applicationGuildCommands()` method of `Routes` requires a `clientID` and `guildID`. This is in the *deploy-commands.js* script. These variables for IDs are also found in *config.json*. Running the program with `node deploy-commands.js` results with the following error in terminal:
```
DiscordAPIError[10002]: Unknown Application
```

**To Reproduce**
Follow the guide up to this point and use command given by the guide: `node deploy-commands.json`

**Additional notes**
Replacing Client ID with the bot's Application ID solved the issue and logged to terminal:
```
Successfully registered application
```

**Comment by megatank58** [comment]
You need to replace the Ids with your own actual values.

**Comment by asiangoldfish** [comment]
Yes, absolutely. It was; however, stated that the method requires the user's client ID. Here's a little snippet of the code from [the guide](https://discordjs.guide/creating-your-bot/creating-commands.html#command-deployment-script):
```
rest.put(Routes.applicationGuildCommands(clientId, guildId), { body: commands })
	.then(() => console.log('Successfully registered application commands.'))
	.catch(console.error);
```
Replacing the variable `clientId` with my own client ID didn't work, so I had a look at the source code, which I found [here](https://github.com/discordjs/discord-api-types/blob/main/rest/v9/index.ts), and here's a small snippet of the method in the `Routes` class (line 700 in */discord-api-types/rest/v9/index.ts*):
```
	applicationGuildCommands(applicationId: Snowflake, guildId: Snowflake) {
		return `/applications/${applicationId}/guilds/${guildId}/commands` as const;
	},

	/**
	 * Route for:
	 * - GET    `/applications/{application.id}/guilds/{guild.id}/commands/{command.id}`
	 * - PATCH  `/applications/{application.id}/guilds/{guild.id}/commands/{command.id}`
	 * - DELETE `/applications/{application.id}/guilds/{guild.id}/commands/{command.id}`
	 */
```
I found the bot's application ID in the Discord Developer Portal under the application's General Information tab.

**Comment by megatank58** [comment]
`clientId` refers to your client's (bot's) Id and `guildId` refers to your Guild's Id respectively.

**Comment by johanalkstal** [comment]
I was confused by this as well, and can imagine others will be too.

Because `clientId` is not terminology used anywhere on Discord or Discord Apps, and what Discord actually means - as the source code clearly shows - is the `applicationId`.

If the docs had just said application id I would have easily found it. Now I got stuck a while trying to find something called client id anywhere, and then thinking what you could possibly mean.

Just some helpful feedback to make the docs as easy to follow as possible. 🙂

**Comment by iCrawl** [comment]
That's mainly because the "application id" wasn't a thing back then in your developer dashboard.

If you click on oauth2 you will still see them mentioning it via "client id", which is what we based it off.

Discord itself is pretty inconsistent with its wording here.
