### ISSUE TITLE
More content Guide For Timed message on interval command

### ISSUE THREAD

**Issue by ManicModder** [discordjs/guide#966]
**Is your feature request related to a problem? Please describe.**

**Describe alternatives you've considered**

**Additional notes**
<!-- This is code I wrote following a tutorial on how to achieve this goal but it does not work I and i think a lot of other people would really like a guide for a bot that does this --
[index.txt](https://github.com/discordjs/guide/files/7718605/index.txt)
[test.txt](https://github.com/discordjs/guide/files/7718611/test.txt)
>

**Comment by almostSouji** [comment]
Bots are supposed to react to a user's action, not do things on an interval on their own. We won't promote features with a high likelihood of encouraging API spam on the guide. If people are eager to implement this they can research timers in Node.js, for example: https://nodejs.org/en/docs/guides/timers-in-node/
