### ISSUE TITLE
when using canvas it says `TypeError: canvas.getContext is not a function`

### ISSUE THREAD

**Issue by Kay-Titulaer** [discordjs/guide#967]
**Describe the bug**
when following the canvas tutorial it gives an error: `TypeError: canvas.getContext is not a function`

**To Reproduce**
follow the canvas tutorial [here](https://discordjs.guide/popular-topics/canvas.html#basic-image-loading)

**Screenshots**
![Schermafbeelding 2021-12-15 130513](https://user-images.githubusercontent.com/76474615/146183566-7447add4-2b83-4adc-b506-01f0fd38e28e.png)

**Comment by almeidx** [comment]
The canvas guide was updated recently, and I am not able to reproduce your error (with the updated one)

**Comment by almostSouji** [comment]
If you can reproduce, feel free to re-open
