### ISSUE TITLE
Guide on Permissions

### ISSUE THREAD

**Issue by queezly** [discordjs/guide#97]
Common question: how does discords permission system work
And yeah, it's hard to wrap your head around at first. I played around with it for quite some time since discords beta through various changes and the question comes up a lot in the supportchannels as well.
Long story short: i'm going to write a guide on it.

Planned coverage:
- What are permissions 
- What are overwrites
- Explicit Allow/Deny
- How all of that works with the different Tiers 
- How do Categories play into all of that

Questions I have for you:
1) Where do you think this belongs? Common Questions? Popular topics?
2) Anything else you'd like to see covered?
3) What should an example for this look like in your opinion?
4) Should i include role hierarchy/Admin/Owner overwrites or do you think that deserves its own paragraph?

**Comment by Lewdcario** [comment]
1. popular topics
2. idunno, can just cover all of permissions... how they work with guild members... priority order... channels. can also make sure to cover implicit permissions that the api covers (like if you have no sview channel perms you can't send messages and anything else, similar with send messages).. also can cover how you cant deny role permissions, inheritance, etc. maybe also an example on how to combine permissions to a structure that can be resolved and get inserted into one of our methods. (like in the case where i want to combine x guild members and give them permissions to see a channel, but not the rest of the server)
3. just do what you'd do in code and we can review it. :)
4. all together in the main guide, but it can be on different pages as you see fit.

**Comment by appellation** [comment]
Discord already has some help articles on this topic, so you can save yourself some effort by not overlapping.

https://support.discordapp.com/hc/en-us/articles/206029707
https://support.discordapp.com/hc/en-us/articles/206141927

**Comment by queezly** [comment]
Change requests/amendments at #110
