### ISSUE TITLE
sqlite3 security vulnerabilities 

### ISSUE THREAD

**Issue by ManicModder** [discordjs/guide#972]
When following the guide on storing data with sequelize and using sqlite3, sqlite3 has issues at the moment and when I try to run nmp audit fix --force it fails to fix the issues and actually install so I don't know where to go from here is there someway to download a working version of sqlite3 or to fix the issue I am having with it currently I would really like to know if there is or if and or when the guide will be update to have steps that don't cause issues

**Comment by kyranet** [comment]
Mind you that `npm audit` isn't exactly good, see [this](https://overreacted.io/npm-audit-broken-by-design/).

**Comment by ManicModder** [comment]
So should I not worry about the security vulnerabilities and just press on with the guide or should they give me some concern

**Comment by kyranet** [comment]
While it's kinda bad to ignore security warnings (and I appreciate your concern), those are most likely false positives, so yeah, ignore `npm audit`.
