### ISSUE TITLE
Link Package Manager Command Tabs

### ISSUE THREAD

**Issue by mathstrains21** [discordjs/guide#973]
**Is your feature request related to a problem? Please describe.**
I find it annoying that if I switch the tab from npm to pnpm, it only does that for that one command entry.

**Describe the solution you'd like**
It should change it for all the command entries on the page at the very least, preferably the whole guide, but that may be harder to do.

**Comment by WiseDevHelper** [comment]
Good idea! I'd like to know what the maintainers think though.

**Comment by almostSouji** [comment]
Would need to introduce state here, vs. having each segment be it's own, secluded component.
I will assign sanc for this, but also close as I cannot see this happening.
