### ISSUE TITLE
How come none of the currency commands or sequeliz db related commands work

### ISSUE THREAD

**Issue by ManicModder** [discordjs/guide#974]
https://discordjs.guide/creating-your-bot/

https://discordjs.guide/creating-your-bot/command-handling.html

https://discordjs.guide/sequelize/

https://discordjs.guide/sequelize/currency.html

**Question**
How come when I make up the bot and complete everything none of the ! commands are working I have I line of code that checks the connection has been established and that says everything is find and there doesn't appear to be any issues also I have everything  set up the same except my main file for my currency system is still index.js because I am using the same bot that I built using the initial bot guide and commands guide but there are no error's and doesn't appear to be any problems except none of the ! commands which are all for the database related stuff work is it because of the command handler or what because I've seen other people have also had issues with this section so I'm thinking it's something to do with the code snippets 
[Index for bot.txt](https://github.com/discordjs/guide/files/7761084/Index.for.bot.txt)

**Comment by MaxMady** [comment]
I think the guide was for slash commands, not for messageCreate event. Also if your error is that you can't see slash commands, then you have to register it first
