### ISSUE TITLE
Add autocomplete options to guide

### ISSUE THREAD

**Issue by CoolJim** [discordjs/guide#979]
**Describe the solution you'd like**

Add a page about autocomplete interactions under the autocomplete sections (see [this page](https://discord.js.org/#/docs/main/stable/class/AutocompleteInteraction) in the discordjs docs)

**Describe alternatives you've considered**

Maybe just add a small note at the bottom of the "registering slash commands" page where it talks about options

**Additional notes**

N/A

**Comment by Underpants-dev** [comment]
check out this pull request: #943

**Comment by Underpants-dev** [comment]
check out this pull request: #943

**Comment by CoolJim** [comment]
> Check out this pull request: #943

Ah ok thanks
