### ISSUE TITLE
Inconsistent Code Between Website and Github

### ISSUE THREAD

**Issue by JamesTreloar** [discordjs/guide#991]
[On the "Command Handling" page. In the section Dynamically Executing Commands:](https://discordjs.guide/creating-your-bot/command-handling.html#dynamically-executing-commands)
Line 12 of the code is:
``await interaction.reply({ content: 'There was an error while executing this command!', ephemeral: true });``

Whereas the [resulting code on GitHub.](https://github.com/discordjs/guide/blob/main/code-samples/creating-your-bot/command-handling/index.js) 
The [corresponding line (30) has:](https://github.com/discordjs/guide/blob/31425b74e49c0f9a3e95a54415b6c2f499adf441/code-samples/creating-your-bot/command-handling/index.js#L30)
``return interaction.reply({ content: 'There was an error while executing this command!', ephemeral: true });``

This inconsistency, between return and await, may confuse those who have made error(s) in another part of the guide. Then they make the change as if this was a fix, but the program would still be not work. This problem may be amplified if they check with going over the guide also.

**Comment by auscoat** [comment]
There is also inconsistency at Command Handling. The guide states  to use 
```
for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	commands.push(command.data.toJSON());
}
```

while the github uses 

```
for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	client.commands.set(command.data.name, command);
}
```

**Comment by BenjammingKirby** [comment]
> There is also inconsistency at Command Handling. The guide states to use
> 
> ```
> for (const file of commandFiles) {
> 	const command = require(`./commands/${file}`);
> 	commands.push(command.data.toJSON());
> }
> ```
> 
> while the github uses
> 
> ```
> for (const file of commandFiles) {
> 	const command = require(`./commands/${file}`);
> 	client.commands.set(command.data.name, command);
> }
> ```

these are unrelated to each other since one is registering the commands and one is storing them locally in a collection for a later use, they're completely doing different things, this is not an inconsistency 
as a matter of fact
```js
client.commands = new Collection();
const commandFiles = fs.readdirSync('./commands').filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	// Set a new item in the Collection
	// With the key as the command name and the value as the exported module
	client.commands.set(command.data.name, command);
}
```
this is from the [guide](https://discordjs.guide/creating-your-bot/command-handling.html#reading-command-files)
